---
output:
  pdf_document: default
  html_document: default
---

# Works Cited {-}

These works cited include the textbooks I referenced when writing my personal introductory statistics notes, which eventually morphed into this text. They also include all of the R packages used in the writing and publishing of this text.

## Textbooks {-}

  Diez DM, Barr CD, & Çetinkaya-Rundel M (2019). OpenIntro Statistics (4th ed). OpenIntro. <https://www.openintro.org/book/os/>
  
  Weiss NA, & Weiss CA (2017). Introductory statistics (10th ed). Pearson. 

## R Packages {-}

  Auguie B (2017). _gridExtra: Miscellaneous Functions for "Grid" Graphics_. R package version 2.3,
  <https://CRAN.R-project.org/package=gridExtra>.

  Bryan J (2025). _gapminder: Data from Gapminder_. R package version 1.0.1,
  <https://CRAN.R-project.org/package=gapminder>.
  
  Chen H (2022). _VennDiagram: Generate High-Resolution Venn and Euler Plots_. R package version 1.7.3,
  <https://CRAN.R-project.org/package=VennDiagram>.
  
  Horst AM, Hill AP, Gorman KB (2020). _palmerpenguins: Palmer Archipelago (Antarctica) penguin data_. R package version
  0.1.0. <https://allisonhorst.github.io/palmerpenguins/>. doi:10.5281/zenodo.3960218.
  
  Neuwirth E (2022). _RColorBrewer: ColorBrewer Palettes_. R package version 1.1-3,
  <https://CRAN.R-project.org/package=RColorBrewer>.
  
  Pebesma E & Bivand R (2023). _Spatial Data Science: With Applications in R_. Chapman and Hall/CRC.
  <https://doi.org/10.1201/9780429459016>

  Pebesma E (2018). _Simple Features for R: Standardized Support for Spatial Vector Data_. The R Journal 10 (1), 439-446,
  <https://doi.org/10.32614/RJ-2018-009>

  R Core Team (2025). _R: A Language and Environment for Statistical Computing_. R Foundation for Statistical Computing,
  Vienna, Austria. <https://www.R-project.org/>.
  
  Venables WN & Ripley BD (2002) _Modern Applied Statistics with S. Fourth Edition_. Springer, New York. ISBN
  0-387-95457-0
  
  Wickham H. _ggplot2: Elegant Graphics for Data Analysis_. Springer-Verlag New York, 2016.
  
  Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen
  TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani
  H (2019). _Welcome to the tidyverse_. Journal of Open Source Software, 4(43), 1686. doi:10.21105/joss.01686
  <https://doi.org/10.21105/joss.01686>.
  
  Wickham H, Pedersen T, Seidel D (2023). _scales: Scale Functions for Visualization_. R package version 1.3.0,
  <https://CRAN.R-project.org/package=scales>.
  
  Xie Y (2024). _bookdown: Authoring Books and Technical Documents with R Markdown_. R package version 0.40,
  <https://github.com/rstudio/bookdown>.

  Xie Y (2016). _bookdown: Authoring Books and Technical Documents with R Markdown_. Chapman and Hall/CRC, Boca Raton, Florida.
  ISBN 978-1138700109, <https://bookdown.org/yihui/bookdown>.
