<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 12 ANOVA | Introduction to Statistics</title>
  <meta name="description" content="Module 12 ANOVA | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 12 ANOVA | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 12 ANOVA | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 12 ANOVA | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 12 ANOVA | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chi-square-tests.html"/>
<link rel="next" href="appendices.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Module 12</span> ANOVA<a href="anova.html#anova" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this module, we extend the concepts from Module 6 to answer questions like “is there a difference between these means?” We will also consider hypothesis tests for whether a sample represents the population or closely matches a particular distribution.</p>
<p><strong>Module Learning Outcomes/Objectives</strong></p>
<p>Perform and interpret inference for</p>
<ol style="list-style-type: decimal">
<li>Interpret an ANOVA.</li>
<li>Use the Bonferroni correction to conduct multiple comparisons.</li>
</ol>
<div id="what-is-the-analysis-of-variance-anova" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> What is the Analysis of Variance (ANOVA)<a href="anova.html#what-is-the-analysis-of-variance-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we’ve examined tests for one and two means, it’s natural to wonder about three or more means. For example, we might want to compare three different medications: treatment 1 (<span class="math inline">\(t_1\)</span>), treatment 2 (<span class="math inline">\(t_2\)</span>), and treatment 3 (<span class="math inline">\(t_3\)</span>). Based on what we’ve learned so far, we might think to do pairwise comparisons, examining <span class="math inline">\(t_1\)</span> vs <span class="math inline">\(t_2\)</span>, then <span class="math inline">\(t_2\)</span> vs <span class="math inline">\(t_3\)</span>, then <span class="math inline">\(t_1\)</span> vs <span class="math inline">\(t_3\)</span>. Unfortunately, this tends to increase our Type I error!</p>
<p>Think of it this way: if I set my confidence level to 95%, I’m setting my Type I error rate to <span class="math inline">\(\alpha=0.05\)</span>. In general terms, this means that about 1 out of every 20 times I run my experiment, I would make a type I error. If I went ahead and ran, say, 20 tests comparing two means, my <em>overall</em> Type I error rate is going to increase - there’s a pretty significant chance that at least one of those comparisons will results in a Type I error!</p>
<p>Instead, we will use a test that allows us to ask: “Are all these means the same?” This is called the <strong>an</strong>alysis <strong>o</strong>f <strong>va</strong>riance, or ANOVA.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The mean outcome is the same across all groups.</li>
<li><span class="math inline">\(H_A\)</span>: At least one mean differs from the rest.</li>
</ul>
<p>In statistical notation, these hypotheses look like:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2 = \dots = \mu_k\)</span></li>
<li><span class="math inline">\(H_A: \mu_i \ne \mu_j\)</span> for at least one pair <span class="math inline">\((i, j)\)</span></li>
</ul>
<p>where <span class="math inline">\(k\)</span> is the number of means being compared and the notation <span class="math inline">\(\mu_i\)</span> represents the mean for the <span class="math inline">\(i\)</span>th group (<span class="math inline">\(i\)</span> can take on any whole number value between 1 and <span class="math inline">\(k\)</span>).</p>
<p>For ANOVA, we have three key conditions:</p>
<ol style="list-style-type: decimal">
<li>Observations are independent within and across groups.</li>
</ol>
<p>Independence within groups is the way we’ve been thinking about independence already. We want to convince ourselves that for any particular group, the observations do not impact each other. For independence across groups, we want to convince ourselves that the groups do not impact each other. Note: if we have a simple random sample, this assumption is always satisfied.</p>
<ol start="2" style="list-style-type: decimal">
<li>Data within each group are approximately normal.</li>
</ol>
<p>If you make a histogram of the data for each group, each histogram will look approximately bell-shaped.</p>
<ol start="3" style="list-style-type: decimal">
<li>Variability is approximately equal across groups.</li>
</ol>
<p>Take the standard deviation for each group and check if they are approximately equal. A boxplot is an appropriate way to do this visually.</p>
<center>
<font size='4'><strong>Why Variance?</strong>
</center>
<p></font></p>
<p>You may have seen the name “analysis of variance” and wondered what the variance has to do with comparing many means. Consider the following boxplots:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-131-1.png" alt="" width="672" /></p>
<p>Is there a difference in the means for Experiment 1? What about Experiment 2?</p>
<p>In fact, the means are <span class="math inline">\(\mu_1 = \mu_4 = 2\)</span>, <span class="math inline">\(\mu_2 = \mu_5 = 1\)</span>, and <span class="math inline">\(\mu_3 = \mu_6 = 0.5\)</span>. But the variances for the Experiment 1 groups are much larger than for the Experiment 2 groups! The larger variances in Experiment 1 obscure any differences between the group means. It is for this reason that we analyze variance as part of our test for differences in means.</p>
<blockquote>
<p>Aside: Why can’t we look at the data first and just test the two means that have the largest difference?</p>
<p>When we look at the data <em>and then choose a test</em>, this inflates our Type I error rate! It’s bad practice and not something we want to engage in as scientists.</p>
</blockquote>
<p>In order to perform an ANOVA, we need to consider whether the sample means differ more than we would expect them to based on natural variation (remember that we expect random samples to produce slightly different sample statistics each time!). This type of variation is called <strong>mean square between groups</strong> or <span class="math inline">\(MSG\)</span>. It has associated degrees of freedom <span class="math inline">\(df_G = k-1\)</span> where <span class="math inline">\(k\)</span> is the number of groups. Note that <span class="math display">\[MSG = \frac{SSG}{df_G}\]</span> where <span class="math inline">\(SSE\)</span> is the <strong>sum of squares group</strong>. If the null hypothesis is true, variation in the sample means is due to chance. In this case, we would expect the MSG to be relatively small.</p>
<p>When I say “relatively small”, I mean we need to compare this quantity to something. We need some quantity that will give us an idea of how much variability to expect if the null hypothesis is true. This is the <strong>mean square error</strong> or <span class="math inline">\(MSE\)</span>, which has degrees of freedom <span class="math inline">\(df_E = n-k\)</span>. Again, we have the relationship that <span class="math display">\[MSE = \frac{SSE}{df_E}\]</span> where <span class="math inline">\(SSE\)</span> is the <strong>sum of squares error</strong>. These calculations are very similar to the calculation for variance (and standard deviation)! (Note: we will not calculate these quantities by hand, but if you are interested in the mathematical details they are available in the OpenIntro Statistics textbook in the footnote on page 289.)</p>
<p>We compare these two quantities by examining their ratio: <span class="math display">\[F = \frac{MSG}{MSE}\]</span> This is the test statistic for the ANOVA. (See Module 10 for an introduction to the F distribution.)</p>
<center>
<font size='4'><strong>The ANOVA Table</strong>
</center>
<p></font></p>
<p>Generally, when we run an ANOVA, we create an ANOVA table (or we have software create one for us!). This table looks something like this</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>df</th>
<th>Sum of Squares</th>
<th>Mean Squares</th>
<th>F Value</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>group</td>
<td><span class="math inline">\(df_G\)</span></td>
<td><span class="math inline">\(SSG\)</span></td>
<td><span class="math inline">\(MSG\)</span></td>
<td><span class="math inline">\(F\)</span></td>
<td>p-value</td>
</tr>
<tr class="even">
<td>error</td>
<td><span class="math inline">\(df_E\)</span></td>
<td><span class="math inline">\(SSE\)</span></td>
<td><span class="math inline">\(MSE\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Example</strong>: chick weights</p>
<p><code>R</code> has data on the weights of chicks fed six different feeds (diets). Assume these data are based on a random sample of chicks. There are <span class="math inline">\(n=71\)</span> total observations and <span class="math inline">\(k=6\)</span> different feeds. Let’s assume we want to test with a 0.05 level of significance.</p>
<p>The ANOVA hypotheses are</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: the mean weight is the same for all six feeds.</li>
<li><span class="math inline">\(H_A\)</span>: at least one feed has a mean weight that differs.</li>
</ul>
<p>The summaries for these data are</p>
</blockquote>
<pre><code>##         casein horsebean linseed meatmeal soybean sunflower
## n        12.00     10.00   12.00    11.00   14.00     12.00
## Mean    323.58    160.20  218.75   276.91  246.43    328.92
## Std Dev  64.43     38.63   52.24    64.90   54.13     48.84</code></pre>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-132-1.png" alt="" width="672" /><img src="IntroStats_files/figure-html/unnamed-chunk-132-2.png" alt="" width="672" /></p>
<blockquote>
<p>The group sizes are relatively small, so it’s difficult to determine how far from normality these data are based on the histograms. We may also run into some issues with constant variance. However, for the sake of the example, let’s push ahead with the ANOVA! Since we usually use software to calculate ANOVAs, I’ve used <code>R</code> to create the following ANOVA table:</p>
</blockquote>
<pre><code>## Analysis of Variance Table
## 
## Response: chickwts$weight
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## chickwts$feed  5 231129   46226  15.365 5.936e-10 ***
## Residuals     65 195556    3009                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>From the table, we can confirm that <span class="math inline">\(df_G = 6-1 = 5\)</span> and <span class="math inline">\(df_E = 71 - 6 = 65\)</span>. The F test statistic is <span class="math display">\[MSG/MSE = 46226 / 3009 = 15.365\]</span> Finally, the p-value is <span class="math inline">\(5.936\times10^{-10}\)</span>. Clearly <span class="math inline">\(5.936\times10^{-10} &lt; \alpha = 0.05\)</span>, so we will reject the null hypothesis and conclude that at least one of the feed groups has a mean weight that differs.</p>
</blockquote>
</div>
<div id="multiple-comparisons-and-type-i-error-rate" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Multiple Comparisons and Type I Error Rate<a href="anova.html#multiple-comparisons-and-type-i-error-rate" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s return for a moment to our ANOVA hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The mean outcome is the same across all groups.</li>
<li><span class="math inline">\(H_A\)</span>: At least one mean differs from the rest.</li>
</ul>
<p>If we reject <span class="math inline">\(H_0\)</span> and conclude that “at least one mean differs from the rest”, how do we determine which mean(s) differ? <em>If</em> we reject <span class="math inline">\(H_0\)</span>, we will perform a series of two-sample t-tests. But wait! What about the Type I error? Isn’t this exactly what we decided we couldn’t do when we introduced ANOVA?</p>
<p>In order to avoid this increased Type I error rate, we run these <strong>multiple comparisons</strong> with a modified significance level. There are several ways to do this, but the most common way is with the <strong>Bonferroni correction</strong>. Here, if we want to test at the <span class="math inline">\(100(1-\alpha)\)</span> level of significance, we run each of our pairwise comparisons with <span class="math display">\[\alpha^* = \alpha/K\]</span> where <span class="math inline">\(K\)</span> is the number of comparisons being considered. For <span class="math inline">\(k\)</span> groups, there are <span class="math display">\[K = \frac{k(k-1)}{2}\]</span> possible pairwise comparisons.</p>
<p>For these comparisons, we use a special pooled estimate of the standard deviation, <span class="math inline">\(s_{\text{pooled}}\)</span> in place of <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span>: <span class="math display">\[\text{standard error} = \sqrt{\frac{s_{\text{pooled}}^2}{n_1} + \frac{s_{\text{pooled}}^2}{n_2}}\]</span> Other than changing <span class="math inline">\(\alpha\)</span> to <span class="math inline">\(\alpha^*\)</span> and the standard error to this new formula, the test is exactly the same as that discussed in the previous section. Note that <span class="math display">\[s_{\text{pooled}} = \sqrt{MSE}\]</span> and the degrees of freedom is <span class="math inline">\(df_E\)</span>.</p>
<blockquote>
<p><strong>Example</strong>: chick weights</p>
<p>Let’s extend our discussion on the chick weights to multiple comparisons. Since we were able to conclude that at least one feed has a weight that differs, we want to find out where the difference(s) lie!</p>
<p>We will test all possible pairwise comparisons. This will require <span class="math inline">\(K = \frac{6(6-1)}{2} = 15\)</span> tests. The pooled standard deviation is <span class="math inline">\(s_{pooled} = \sqrt{3009} \approx 54.85\)</span>. Let’s walk through the test of casein <span class="math inline">\((\bar{x}_1 = 323.58, n=12)\)</span> vs horsebean <span class="math inline">\((\bar{x}_2 = 160.20, n=10)\)</span>:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span></li>
<li><span class="math inline">\(H_A: \mu_1 \ne \mu_2\)</span></li>
</ul>
<p>The estimated difference and standard error are <span class="math display">\[\bar{x}_1 - \bar{x}_2 = 323.58 - 160.20 = 163.38 \quad\quad SE = \sqrt{\frac{54.85^2}{11}+\frac{54.85^2}{9}} = 25.65\]</span> which results in a test statistic of <span class="math inline">\(t=6.37\)</span> and a p-value of <span class="math inline">\(1.11\times10^{-8}\)</span>. We then compare this to <span class="math inline">\(\alpha^* = 0.05/15 = 0.0033\)</span>. Since the p-value of <span class="math inline">\(1.11\times10^{-8} &lt; \alpha^* = 0.0033\)</span>, we reject the null hypothesis and conclude there is a significant difference in mean chick weight between the casein and horsebean feeds.</p>
<p>In order to complete the pairwise comparisons, we would then run the remaining 14 tests. I will leave this as an optional exercise for the particularly motivated student.</p>
</blockquote>
<p>Note: occasionally, we may reject <span class="math inline">\(H_0\)</span> in the ANOVA but may fail to find any statistically significant differences when performing multiple comparisons with the Bonferroni correction. This is ok! It just means we were unable to identify which specific groups differ.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chi-square-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendices.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
