<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 2 Descriptive Measures | Introduction to Statistics</title>
  <meta name="description" content="Module 2 Descriptive Measures | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 2 Descriptive Measures | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 2 Descriptive Measures | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 2 Descriptive Measures | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 2 Descriptive Measures | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-data.html"/>
<link rel="next" href="regression-and-correlation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-measures" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Module 2</span> Descriptive Measures<a href="descriptive-measures.html#descriptive-measures" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous module, we thought about descriptive statistics using tables and graphs. Next, we summarize data by computing numbers. Some of these numbers you may already be familiar with, such as averages and percentiles. Numbers used to describe data are called <em>descriptive measures</em>.</p>
<p><strong>Module Learning Objectives/Outcomes</strong></p>
<p>After completing Module 2, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Calculate and interpret measures of center.</li>
<li>Calculate and interpret measures of variation.</li>
<li>Find and interpret measures of position.</li>
<li>Summarize data using box plots.</li>
</ol>
<p><strong>R objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Generate measures of center.</li>
<li>Generate measures of variability.</li>
<li>Generate measures of position.</li>
<li>Create box plots.</li>
</ol>
<p>This module’s outcomes correspond to course outcomes (1) organize, summarize, and interpret data in tabular, graphical, and pictorial formats, (2) organize and interpret bivariate data and learn simple linear regression and correlation, and (6) apply statistical inference techniques of parameter estimation such as point estimation and confidence interval estimation.</p>
<div id="measures-of-central-tendency" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Measures of Central Tendency<a href="descriptive-measures.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One research question we might ask is: what values are most common or most likely?</p>
<p><strong>Mode</strong>: the most commonly occurring value. We can use this for numeric variables, but typically we use the mode when talking about categorical data.</p>
<p><strong>Mean</strong>: this is what we usually think of as the “average”. Denoted <span class="math inline">\(\bar{x}\)</span>. Add up all of the values and divide by the number of observations (<span class="math inline">\(n\)</span>):
<span class="math display">\[
  \bar{x} = \frac{x_1 + x_2 + \dots + x_n}{n} = \sum_{i=1}^n \frac{x_i}{n}
\]</span>
where <span class="math inline">\(x_i\)</span> denotes the <span class="math inline">\(i\)</span>th observation and <span class="math inline">\(\sum_{i=1}^n\)</span> is the sum of all observations from 1 through <span class="math inline">\(n\)</span>. This is called <em>summation notation</em>.</p>
<p><strong>Median</strong>: the middle number when the data are ordered from smallest to largest.</p>
<ul>
<li>If there are an odd number of observations, this will be the number in the middle:
<center>
{1, 3, <strong>7</strong>, 9, 9} has median 7
</center></li>
<li>If there are an even number of observations, there will be two numbers in the middle. The median will be their average.
<center>
{1, 2, <strong>4, 7</strong>, 9, 9} has median <span class="math inline">\(\frac{4+7}{2}=5.5\)</span>
</center></li>
</ul>
<p>The mean is sensitive to extreme values and skew. The median is not!</p>
<table border="1">
<tbody>
<tr>
<td style="width: 9%; text-align: center;">
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(x\)</span>: 1, 3, 7, 9, 9
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(y\)</span>: 1, 3, 7, 9, 45
</td>
</tr>
<tr>
<td style="width: 9%; text-align: center;">
<strong>Median</strong>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\text{median} = 7\)</span>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\text{median} = 7\)</span>
</td>
</tr>
<tr>
<td style="width: 9%; text-align: center;">
<strong>Mean</strong>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\bar{x} = \frac{29}{5} = 5.8\)</span>
</td>
<td style="width: 40%; text-align: center;">
<span class="math inline">\(\bar{y} = \frac{65}{5} = 13\)</span>
</td>
</tr>
</tbody>
</table>
<p>Notice how changing that 9 out for a 45 changes the <em>mean</em> a lot! But the <em>median</em> is 7 for both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p>If the mean and median are roughly equal, it is reasonable to assume the distribution is roughly symmetric. Since calculating the mean involves adding all the values, the mean will get pulled toward any extremes (and away from the median).</p>
<p>Because the median is not affected by extreme observations or skew, we say it is a <strong>resistant measure</strong> or that it is <strong>robust</strong>.</p>
<center>
<font size='4'><b>Which measure should we use?</b></font>
</center>
<ul>
<li>Mean: symmetric, numeric data</li>
<li>Median: skewed, numeric data</li>
<li>Mode: categorical data</li>
</ul>
<div id="weighted-means" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Weighted Means<a href="descriptive-measures.html#weighted-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes we have reason to calculate a <em>weighted mean</em>. For example, course grades are often calculated using a grading scheme that weights each category.</p>
<p><span class="math display">\[\bar{x}_w = w_1x_1 + w_2x_2 + \dots w_nx_n\]</span></p>
<p>In this case, each <span class="math inline">\(p\)</span> represents the proportion attributed to that category. In general, we require that all of the <span class="math inline">\(w\)</span> values sum to <span class="math inline">\(1\)</span>.</p>
<blockquote>
<p>Example Consider the following grade distribution:</p>
<ul>
<li>Assignments: 15%</li>
<li>Quizzes: 20%</li>
<li>Exam 1: 15%</li>
<li>Exam 2: 15%</li>
<li>Project: 15%</li>
<li>Final Exam: 20%</li>
</ul>
<p>We can use this to calculate an overall grade. Suppose some student has the following score in each category</p>
<ul>
<li>Assignments: 92%</li>
<li>Quizzes: 76%</li>
<li>Exam 1: 56%</li>
<li>Exam 2: 69%</li>
<li>Project: 89%</li>
<li>Final Exam: 70%</li>
</ul>
<p>We can calculate their overall grade in the class using the weighted average formula.</p>
<p><span class="math display">\[\begin{aligned}\text{grade} &amp;= 92(0.15) + 76(0.20) + 56(0.15) + 69(0.15) + 89(0.15) + 70(0.20) \\
&amp;= 13.8 + 15.2 + 8.4 + 10.35 + 13.35 + 14 \\ &amp;= 75.1\end{aligned}\]</span>
So this student would get a 75.5% in the class. (Notice that we changed the grade distribution values from percents to proportions!)</p>
</blockquote>
<p>This is how learning management systems like Canvas automatically calculate grades.</p>
<blockquote>
<p>Example: Now suppose a student has the following scores</p>
<ul>
<li>Assignments: 83%</li>
<li>Quizzes: 71%</li>
<li>Exam 1: 61%</li>
<li>Exam 2: 68%</li>
<li>Project: 91%</li>
</ul>
<p>and has not taken the final exam yet. He really wants to pass the class with at least a C-, but is not sure what kind of final exam grade would allow him to do that.</p>
<p>If he wants to pass, he needs a minimum overall grade of 70%. So he needs his weighted average to be 70% or higher. We know everything except his final exam score, so we’ll make that <span class="math inline">\(F\)</span> in our formula:</p>
<p><span class="math display">\[70 = 83(0.15) + 71(0.20) + 61(0.15) + 68(0.15) + 91(0.15) + F(0.20)\]</span>
To figure out what he needs to get on the final, we need to solve for F.</p>
<p><span class="math display">\[\begin{aligned}
70 &amp;= 83(0.15) + 71(0.20) + 61(0.15) + 68(0.15) + 91(0.15) + F(0.20)\\
70 &amp;= 12.45+14.2+9.15+10.2+13.65+0.2 \\
70  &amp;= 59.65 + 0.2F \\
10.35 &amp;= 0.2F \\
F &amp;= 51.75
\end{aligned}\]</span></p>
<p>So he needs to get at least a 51.75% on the final exam in order to pass the class.</p>
</blockquote>
</div>
<div id="section-exercises-4" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="descriptive-measures.html#section-exercises-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
For exercises 1-5, calculate the mean and median. Then, determine which measure of center should be used to describe the data. Explain your thought process.
<ol>
<li>
<span class="math inline">\(9,2,7,3,5\)</span>
</li>
<li>
<span class="math inline">\(56,87,21,95,236\)</span>
</li>
<li>
<span class="math inline">\(1.3, 2.4, 1.5, 2.1, 3.9, 3.2, 0.9\)</span>
</li>
<li>
<span class="math inline">\(4, 6, 2, 4, 5, 5, 7, 2, 5\)</span>
</li>
<li>
<span class="math inline">\(345, 654, 234, 123, 432, 152\)</span>
</li>
</ol>
<ol start="6">
<li>
<p>Consider the following frequency distribution for students in a class.</p>
<table>
<thead>
<tr>
<th align="center">Class</th>
<th align="center">Frequency</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">freshman</td>
<td align="center">8</td>
</tr>
<tr>
<td align="center">sophomore</td>
<td align="center">17</td>
</tr>
<tr>
<td align="center">junior</td>
<td align="center">21</td>
</tr>
<tr>
<td align="center">senior</td>
<td align="center">3</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha;">
<li>
How many students are in this class?
</li>
<li>
What is the mode of these data?
</li>
</ol>
<li>
A class of intro stats students were asked where they were from. A bar chart of their responses is shown below.
</li>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<ol style="list-style-type: lower-alpha;">
<li>
How many students are in this class?
</li>
<li>
What is the mode of these data?
</li>
</ol>
<li>
Twenty-five Stat 1 students were asked how many siblings they have. The following data shows their responses: <span class="math display">\[ 5, 1, 7, 3, 2, 0, 1, 4, 3, 2, 0, 2, 2, 0, 0, 5, 1, 1, 1, 5, 2, 3, 2, 4, 6\]</span>
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Calculate the mean number of siblings.
</li>
<li>
Determine the median number of siblings.
</li>
<li>
What do the mean and median tell you about the skew/symmetry of this distribution? Based on this assessment, which measure of center would be the best choice for describing these data?
</li>
</ol>
<li>
A professor is teaching four sections of the same class and wants to know the overall average course grade of her students.
</li>
<table>
<thead>
<tr>
<th align="left"></th>
<th align="center">Class 1</th>
<th align="center">Class 2</th>
<th align="center">Class 3</th>
<th align="center">Class 4</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">Mean grade</td>
<td align="center">78</td>
<td align="center">81</td>
<td align="center">76</td>
<td align="center">80</td>
</tr>
<tr>
<td align="left">Number of students</td>
<td align="center">27</td>
<td align="center">31</td>
<td align="center">33</td>
<td align="center">30</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha;">
<li>
We can weight these grades using the number of students in the class. Convert the number of students to proportions by dividing each number by the total number of students.
</li>
<li>
Using your proportions from (a) as the weights, calculate the weighted mean grade for the professor’s four classes.
</li>
</ol>
</ol>
</div>
</div>
<div id="measures-of-variability" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Measures of Variability<a href="descriptive-measures.html#measures-of-variability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How much do the data vary?</p>
<p>Should we care? Yes! The more variable the data, the harder it is to be confident in our measures of center!</p>
<p>If you live in a place with extremely variable weather, it is going to be much harder to be confident in how to dress for tomorrow’s weather… but if you live in a place where the weather is always the same, it’s much easier to be confident in what you plan to wear.</p>
<p>We want to think about how far observations are from the measure of center.</p>
<p>One easy way to think about variability is the <strong>range</strong> of the data: <span class="math display">\[\text{range} = \text{maximum} - \text{minimum}\]</span> This is quick and convenient, but it is <em>extremely</em> sensitive to outliers! It also takes into account only two of the observations - we would prefer a measure of variability that takes into account <em>all</em> the observations.</p>
<div id="standard-deviation" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Standard Deviation<a href="descriptive-measures.html#standard-deviation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Deviation</strong> is the distance of an observation from the mean: <span class="math inline">\(x - \bar{x}\)</span>. If we want to think about how far - on average - a typical observation is from the center, our intuition might be to take the average deviance… but it turns out that summing up the deviances will <em>always</em> result in 0! Conceptually, this is because the stuff below the mean (negative numbers) and the stuff above the mean (positive numbers) end up canceling each other out until we end up at 0. (If you are interested, <em>Appendix A: Average Deviance</em> has a mathematical proof of this using some relatively straightforward algebra.)</p>
<p>One way to deal with this is to make all of the numbers positive, which we accomplish by squaring the deviance.</p>
<table>
<thead>
<tr>
<th align="center"></th>
<th align="center">Deviance</th>
<th align="center">Squared Deviance</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center"><span class="math inline">\(x\)</span></td>
<td align="center"><span class="math inline">\(x - \bar{x}\)</span></td>
<td align="center"><span class="math inline">\((x - \bar{x})^2\)</span></td>
</tr>
<tr>
<td align="center">2</td>
<td align="center">-1.2</td>
<td align="center">1.44</td>
</tr>
<tr>
<td align="center">5</td>
<td align="center">1.8</td>
<td align="center">3.24</td>
</tr>
<tr>
<td align="center">3</td>
<td align="center">-0.2</td>
<td align="center">0.04</td>
</tr>
<tr>
<td align="center">4</td>
<td align="center">0.8</td>
<td align="center">0.64</td>
</tr>
<tr>
<td align="center">2</td>
<td align="center">-1.2</td>
<td align="center">1.44</td>
</tr>
<tr>
<td align="center"><span class="math inline">\(\bar{x}=3.2\)</span></td>
<td align="center">Total = 0</td>
<td align="center">Total = 6.8</td>
</tr>
</tbody>
</table>
<p><strong>Variance</strong> (denoted <span class="math inline">\(s^2\)</span>) is the average squared distance from the mean:
<span class="math display">\[
  s^2 = \frac{(x_1-\bar{x})^2 + (x_2-\bar{x})^2 + \dots + (x_n-\bar{x})^2}{n-1} = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2
\]</span>
where <span class="math inline">\(n\)</span> is the sample size. Notice that we divide by <span class="math inline">\(n-1\)</span> and NOT by <span class="math inline">\(n\)</span>. There are some mathematical reasons why we do this, but the short version is that it’ll be a better estimate when we talk about inference.</p>
<p>Finally, we come to <strong>standard deviation</strong> (denoted <span class="math inline">\(s\)</span>). <span class="math display">\[s = \sqrt{s^2}\]</span> The standard deviation is the square root of the variance. We say that a “typical” observation is within about one standard deviation of the mean (between <span class="math inline">\(\bar{x}-s\)</span> and <span class="math inline">\(\bar{x}+s\)</span>).</p>
<p>In practice (including in this class), we will use a computer to calculate the variance and standard deviation.</p>
</div>
<div id="the-interquartile-range" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> The Interquartile Range<a href="descriptive-measures.html#the-interquartile-range" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>interquartile range</strong> (<strong>IQR</strong>) represents the middle 50% of the data.</p>
<p>Recall that the <em>median</em> cut the data in half: 50% of the data is below and 50% is above the median. This is also called the <strong>50th percentile</strong>. The <strong><span class="math inline">\(p\)</span>th percentile</strong> is the value for which <span class="math inline">\(p\)</span>% of the data is below it.</p>
<p>To get the middle 50%, we will split the data into four parts:</p>
<table>
<thead>
<tr>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">25%</td>
<td align="center">25%</td>
<td align="center">25%</td>
<td align="center">25%</td>
</tr>
</tbody>
</table>
<p>The 25th and 75th percentiles, along with the median, divide the data into four parts. We call these three measurements the <strong>quartiles</strong>:</p>
<ul>
<li><strong>Q1</strong>, the first quartile, is the median of the lower 50% of the data.</li>
<li><strong>Q2</strong>, the second quartile, is the median.</li>
<li><strong>Q3</strong>, the third quartile, is the median of the upper 50% of the data.</li>
</ul>
<blockquote>
<p><strong>Example</strong>: Consider {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}</p>
<ul>
<li>Cutting the data in half: {1, 2, 3, 4, 5 | 6, 7, 8, 9, 10}, the median (Q2) is <span class="math inline">\(\frac{5+6}{2}=5.5\)</span>.</li>
<li>Q1 is the median of {1, 2, 3, 4, 5}, or 3</li>
<li>Q3 is the median of {6, 7, 8, 9, 10}, or 8</li>
</ul>
</blockquote>
<p><strong>Note:</strong> this is a “quick and dirty” way of finding quartiles. A computer will give a more exact result.</p>
<p>Then the interquartile range is
<span class="math display">\[
  \text{IQR} = \text{Q3}-\text{Q1}
\]</span></p>
<p>This is another measure of variability and is resistant to extreme values.</p>
<p>Which measure should we use?</p>
<ul>
<li>Mean and standard deviation: symmetric, numeric data</li>
<li>Median and IQR: skewed, numeric data</li>
</ul>
<p>Notice that we do not have a measure of variability for categorical data. Instead, if we want to think about variability for categorical data, we can use a frequency table or bar plot to visualize this variability.</p>
</div>
<div id="box-plots" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Box Plots<a href="descriptive-measures.html#box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our quartiles are the foundation for constructing what we call a box plot, which summarizes the data with five five statistics plus extreme observations. These statistics are sometimes referred to collectively as the “five number summary”: the minimum, Q1, the median (Q2), Q3, and the maximum.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Drawing a box plot:</p>
<ol style="list-style-type: decimal">
<li>Draw the vertical axis to include all possible values in the data.</li>
<li>Draw a horizontal line at the median, at <span class="math inline">\(\text{Q1}\)</span>, and at <span class="math inline">\(\text{Q3}\)</span>. Use these to form a box.</li>
<li>Draw the <strong>whiskers</strong>. The whiskers’ upper limit is <span class="math inline">\(\text{Q3}+1.5\times\text{IQR}\)</span> and the lower limit is <span class="math inline">\(\text{Q1}-1.5\times\text{IQR}\)</span>. The actual whiskers are then drawn <em>at the next closest data points within the limits</em>.</li>
<li>Any points outside the whisker limits are included as individual points. These are <strong>potential outliers</strong>.</li>
</ol>
<p>(Potential) outliers can help us…</p>
<ul>
<li>examine skew (outliers in the negative direction suggest left skew; outliers in the positive direction suggest right skew).</li>
<li>identify issues with data collection or entry, especially if the value of an outlier doesn’t make sense.</li>
</ul>
<p>As with most things in this text, we won’t draw a lot of boxplots by hand. However, understanding how they are drawn will help us understand how to interpret them!</p>
</div>
<div id="section-exercises-5" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="descriptive-measures.html#section-exercises-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol>
<li>
Twenty-five Stat 1 students were asked how many siblings they have. The following data shows their responses: <span class="math display">\[ 5, 1, 7, 3, 2, 0, 1, 4, 3, 2, 0, 2, 2, 0, 0, 5, 1, 1, 1, 5, 2, 3, 2, 4, 6\]</span>
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Use a computer to calculate the variance of the number of siblings.
</li>
<li>
Calculate the standard deviation of number of siblings.
</li>
<li>
What do the mean and standard deviation tell you about how many siblings a “typical” Stat 1 student has?
</li>
</ol>
<li>
Twenty-five Stat 1 students were asked how many siblings they have. The following data shows their responses: <span class="math display">\[ 5, 1, 7, 3, 2, 0, 1, 4, 3, 2, 0, 2, 2, 0, 0, 5, 1, 1, 1, 5, 2, 3, 2, 4, 6\]</span>
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Give the five number summary for these data.
</li>
<li>
What is the IQR?
</li>
<li>
Refer to the histogram of these data in <a href="https://bookdown.org/lgpperry/introstats/introduction-to-data.html#section-exercises-3">Section 1.4, Exercise 1</a>. Is the IQR or the standard deviation a better measure of spread for these data? Explain your reasoning.
</li>
</ol>
<li>
Draw or print out the following boxplot.
</li>
<img src="IntroStats_files/figure-html/unnamed-chunk-38-1.png" width="672" />
<ol style="list-style-type: lower-alpha;">
<li>
Label the median, Q1, and Q3 on the boxplot.
</li>
<li>
Label the whiskers and, if there are any, potential outliers.
</li>
<li>
Use the boxplot to find the (approximate) interquartile range for eruption duration.
</li>
</ol>
<li>
Use the boxplots below to answer questions a-b. Note that these are called side-by-side boxplots and can be used to compare different categories. In this case, we are comparing weights of chickens who have been given various types of feed.
</li>
</ol>
<img src="IntroStats_files/figure-html/unnamed-chunk-39-1.png" width="672" />
<ol>
<ol style="list-style-type: lower-alpha;">
<li>
What is the approximate median weight for chickens given meatmeal?
</li>
<li>
What is the approximate IQR for chickens fed horsebean?
</li>
<li>
Based on IQR, which feed has the greatest variability?
</li>
<li>
Are there any potential outliers? How do you know?
</li>
</ol>
</ol>
</div>
</div>
<div id="descriptive-measures-for-populations" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Descriptive Measures for Populations<a href="descriptive-measures.html#descriptive-measures-for-populations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far, we’ve thought about calculating various descriptive statistics from a sample, but our long-term goal is to estimate descriptive information about a population. At the population level, these values are called <strong>parameters</strong>.</p>
<p>When we find a measure of center, spread, or position, we use a sample to calculate a single value. These single values are called <strong>point estimates</strong> and they are used to <em>estimate</em> the corresponding population parameter. For example, we use <span class="math inline">\(\bar{x}\)</span> to estimate the population mean, denoted <span class="math inline">\(\mu\)</span> (Greek letter “mu”) and <span class="math inline">\(s\)</span> to estimate the population standard deviation, denoted <span class="math inline">\(\sigma\)</span> (Greek letter “sigma”).</p>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr>
<th>Point Estimate</th>
<th>Parameter</th>
</tr>
</thead>
<tbody>
<tr>
<td>sample mean: <span class="math inline">\(\bar{x}\)</span></td>
<td>population mean: <span class="math inline">\(\mu\)</span></td>
</tr>
<tr>
<td>sample standard deviation: <span class="math inline">\(s\)</span></td>
<td>population standard deviation: <span class="math inline">\(\sigma\)</span></td>
</tr>
</tbody>
</table>
<p>…and so on and so forth. For each quantity we calculate from a sample (point estimate), there is some corresponding unknown population level value (parameter) that we wish to estimate.</p>
<p>We will discuss this in more detail when we discuss Random Variables and Statistical Inference.</p>
</div>
<div id="r-lab-descriptive-statistics-and-boxplots" class="section level2 unnumbered hasAnchor">
<h2>R Lab: Descriptive Statistics and Boxplots<a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="finding-measures-of-center" class="section level3 unnumbered hasAnchor">
<h3>Finding Measures of Center<a href="descriptive-measures.html#finding-measures-of-center" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a mean in R, we use the command <code>mean</code>. Let’s use the <code>Loblolly</code> pine data again and find the <code>mean</code> tree height.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="descriptive-measures.html#cb17-1" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span>
<span id="cb17-2"><a href="descriptive-measures.html#cb17-2" tabindex="-1"></a><span class="fu">mean</span>(height)</span></code></pre></div>
<pre><code>## [1] 32.3644</code></pre>
<p>From R, we can see that the sample mean height of the Loblolly pines is 32.36 feet. (Note that R will often print things out with ## and a number in square brackets. This is just to help us keep track of things if we write a lot of lines of code. You can ignore that number in the brackets!)</p>
<p>Is a mean the appropriate measure of center? We can quickly check the skew with a histogram:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="descriptive-measures.html#cb19-1" tabindex="-1"></a><span class="fu">hist</span>(height)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>It might be a little bit hard to tell with this histogram, but it does not look particularly skewed. Let’s use our other trick: if the mean and median are approximatly equal, we can say the distribution is approximately symmetric (and therefore the mean is an appropriate measure of center). To calculate the median, we use the command <code>median</code>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="descriptive-measures.html#cb20-1" tabindex="-1"></a><span class="fu">median</span>(height)</span></code></pre></div>
<pre><code>## [1] 34</code></pre>
<p>The sample median of the Loblolly pine heights is 34 feet. Since the mean and median are approximately equal, it would be reasonable to use the mean in this case.</p>
<p>To find a mode, we will use the <code>table</code> command. (Recall that this will generate a frequency distribution, from which you can take the mode.)</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="descriptive-measures.html#cb22-1" tabindex="-1"></a>gender <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Other&quot;</span>, <span class="st">&quot;Female&quot;</span>)</span>
<span id="cb22-2"><a href="descriptive-measures.html#cb22-2" tabindex="-1"></a><span class="fu">table</span>(gender)</span></code></pre></div>
<pre><code>## gender
## Female   Male  Other 
##      2      1      1</code></pre>
<div id="your-turn-6" class="section level4 unnumbered hasAnchor">
<h4>Your Turn<a href="descriptive-measures.html#your-turn-6" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Find the following summary statistics for the <code>age</code> variable in the <code>Loblolly</code> pine tree data. Include your R code and the output in your answer.
<ol style="list-style-type: lower-alpha">
<li>mean</li>
<li>median</li>
</ol></li>
<li>For the <code>age</code> variable in the <code>Loblolly</code> pine tree data, which measure of center is most appropriate? Explain.</li>
</ol>
</div>
</div>
<div id="finding-measures-of-variability" class="section level3 unnumbered hasAnchor">
<h3>Finding Measures of Variability<a href="descriptive-measures.html#finding-measures-of-variability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a range in R, we get started using the command <code>range</code>. Let’s keep using the <code>Loblolly</code> pine data and find the <code>mean</code> tree height.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="descriptive-measures.html#cb24-1" tabindex="-1"></a><span class="fu">range</span>(height)</span></code></pre></div>
<pre><code>## [1]  3.46 64.10</code></pre>
<p>This command gives us the minimum and maximum values. Then to calculate the range, we would find <span class="math inline">\(64.10 - 3.46\)</span>. We can also do this in R, because R doubles as a calculator!</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="descriptive-measures.html#cb26-1" tabindex="-1"></a><span class="fl">64.1</span> <span class="sc">-</span> <span class="fl">3.46</span></span></code></pre></div>
<pre><code>## [1] 60.64</code></pre>
<p>The sample range of the Loblolly pine heights is 60.64 feet.</p>
<p>To find the variance and standard deviation, we use the commands <code>var</code> and <code>sd</code>, respectively:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="descriptive-measures.html#cb28-1" tabindex="-1"></a><span class="fu">var</span>(height)</span></code></pre></div>
<pre><code>## [1] 427.3979</code></pre>
<p>The sample variance of the Loblolly pine heights is 427.4.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="descriptive-measures.html#cb30-1" tabindex="-1"></a><span class="fu">sd</span>(height)</span></code></pre></div>
<pre><code>## [1] 20.6736</code></pre>
<p>The sample standard deviation of the Loblolly pine heights is 20.67 feet.</p>
<div id="your-turn-7" class="section level4 unnumbered hasAnchor">
<h4>Your Turn<a href="descriptive-measures.html#your-turn-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol start="3" style="list-style-type: decimal">
<li>Find the standard deviation of the <code>age</code> variable in the <code>Loblolly</code> pine tree data. Include your R code and the output in your answer.</li>
</ol>
</div>
</div>
<div id="measures-of-position" class="section level3 unnumbered hasAnchor">
<h3>Measures of Position<a href="descriptive-measures.html#measures-of-position" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can get the quartiles quickly using the <code>summary</code> command. This will also give us the minimum, mean, and maximum. That’s fine!</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="descriptive-measures.html#cb32-1" tabindex="-1"></a><span class="fu">summary</span>(height)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    3.46   10.47   34.00   32.36   51.36   64.10</code></pre>
<p>So <span class="math inline">\(Q1 = 10.46\)</span>, <span class="math inline">\(Q2 = \text{Median} = 34\)</span>, and <span class="math inline">\(Q3 = 51.35\)</span>. We can also quickly get the interquartile range using the <code>IQR</code> command.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="descriptive-measures.html#cb34-1" tabindex="-1"></a><span class="fu">IQR</span>(height)</span></code></pre></div>
<pre><code>## [1] 40.895</code></pre>
<div id="your-turn-8" class="section level4 unnumbered hasAnchor">
<h4>Your Turn<a href="descriptive-measures.html#your-turn-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol start="4" style="list-style-type: decimal">
<li>Find the interquartile range for the <code>age</code> variable in the <code>Loblolly</code> pine tree data. Include your R code and the output in your answer.</li>
<li>For the <code>age</code> variable in the <code>Loblolly</code> pine tree data, which measure of spread (variability) is most appropriate? Explain.</li>
</ol>
</div>
</div>
<div id="box-plots-1" class="section level3 unnumbered hasAnchor">
<h3>Box Plots<a href="descriptive-measures.html#box-plots-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To create a boxplot in R, we use the command <code>boxplot</code>. We can use some of the same arguments we used with the <code>hist</code> command to give it titles and color:</p>
<ul>
<li><code>main</code> is where I can give the plot a new title. (Make sure to put the title in quotes!)</li>
<li><code>ylab</code> is the y-axis (vertical axis) title.</li>
<li><code>col</code> allows us to give R a specific color for the bars. Notice that I also have to put the color in quotes.</li>
</ul>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="descriptive-measures.html#cb36-1" tabindex="-1"></a><span class="fu">boxplot</span>(height,</span>
<span id="cb36-2"><a href="descriptive-measures.html#cb36-2" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot of Loblolly Pine Heights&quot;</span>, </span>
<span id="cb36-3"><a href="descriptive-measures.html#cb36-3" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Height (feet)&quot;</span>,</span>
<span id="cb36-4"><a href="descriptive-measures.html#cb36-4" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>R will automatically create the entire box plot, including showing any outliers. (Which we should note that there aren’t any in the <code>height</code> variable!)</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="descriptive-measures.html#cb37-1" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>
<div id="your-turn-9" class="section level4 unnumbered hasAnchor">
<h4>Your Turn<a href="descriptive-measures.html#your-turn-9" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol start="6" style="list-style-type: decimal">
<li>Create a boxplot of the <code>age</code> variable in the <code>Loblolly</code> pine tree data. Give your plot an appropriate vertical axis title.</li>
</ol>
</div>
</div>
<div id="course-survey-data" class="section level3 unnumbered hasAnchor">
<h3>Course Survey Data<a href="descriptive-measures.html#course-survey-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To access the course survey data, enter the following command, replacing the <code>TYY</code> with the appropriate semester, where <code>T</code> is the term (<code>f</code> for fall; <code>s</code> for spring) and <code>YY</code> is the year.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="descriptive-measures.html#cb38-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;https://lgpperry.github.io/teaching/stat1/data/data_TYY.R&quot;</span>)</span></code></pre></div>
<p>For example, for spring semester 2024, this command would look like:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="descriptive-measures.html#cb39-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;https://lgpperry.github.io/teaching/stat1/data/data_s24.R&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Use the command `str(survey)` to view the variables in the data.&quot;
## [1] &quot;The command `attach(survey)` will allow you to access the variables directly.&quot;</code></pre>
<p>This command references some R code I have on my website that both reads in the data and cleans it up a little bit so that it’s ready for you to use. The data saved in R will be called <code>survey</code>.</p>
<p>Note: if you happen to try this out before I get this semester’s data uploaded, you’ll get an error along the lines of “cannot open the connection”. In the meantime, you may use the example code above to get an idea for what the data might look like in R.</p>
<p>To figure out exactly what we’re working with, we will use the <code>str</code> command:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="descriptive-measures.html#cb41-1" tabindex="-1"></a><span class="fu">str</span>(survey)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    21 obs. of  14 variables:
##  $ haircolor   : Factor w/ 3 levels &quot;Black&quot;,&quot;Blonde&quot;,..: 1 1 1 1 3 2 3 1 1 3 ...
##  $ numpets     : int  0 0 0 12 2 1 1 0 0 2 ...
##  $ wherefrom   : Factor w/ 4 levels &quot;Bay Area&quot;,&quot;Other California&quot;,..: 4 1 4 1 1 4 4 1 4 1 ...
##  $ height      : num  5.75 5.9 5.58 5 5 ...
##  $ sleep       : int  6 7 6 6 8 7 8 7 6 9 ...
##  $ pets        : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 1 1 2 2 2 2 1 1 2 ...
##  $ schooldays  : int  5 5 4 5 5 3 5 3 4 3 ...
##  $ schoolperiod: Factor w/ 4 levels &quot;College&quot;,&quot;Elementary School&quot;,..: 1 3 3 4 3 3 2 1 3 2 ...
##  $ siblings    : int  5 1 7 3 2 1 4 3 2 2 ...
##  $ siborder    : Factor w/ 4 levels &quot;Middle child&quot;,..: 2 4 1 2 1 2 4 1 1 4 ...
##  $ job         : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 2 2 2 1 1 2 2 1 1 2 ...
##  $ exercise    : int  0 5 0 3 0 4 1 0 0 3 ...
##  $ units       : int  8 15 12 12 16 15 12 15 16 12 ...
##  $ major       : Factor w/ 8 levels &quot;Biology&quot;,&quot;Business&quot;,..: 1 2 2 6 6 2 2 5 6 2 ...</code></pre>
<p>The stuff shown in the column on the left are all of the variable names. I try to name these to match the survey questions in an intuitive way, but if you’re not sure which variable matches which survey question, there will be additional information available on Canvas.</p>
<p>The stuff shown on the right gives some information about the variable <em>type</em>. If it says <code>int</code> or <code>num</code>, those are numeric variables. Variables that say <code>Factor</code>, are categorical and the “levels” are the different categories in the data.</p>
<p>Finally, to use these variables directly, use the command <code>attach(survey)</code>.</p>
<div id="your-turn-10" class="section level4 unnumbered hasAnchor">
<h4>Your Turn<a href="descriptive-measures.html#your-turn-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol start="7" style="list-style-type: decimal">
<li>Select a numeric variable from this semester’s course survey data. Find the following summary statistics for that variable:
<ol style="list-style-type: lower-alpha">
<li>mean</li>
<li>median</li>
<li>standard deviation</li>
<li>interquartile range</li>
</ol></li>
<li>Create a histogram of the numeric variable you chose in (7). Make sure to give it an appropriate title and axis labels.</li>
<li>Select a categorical variable from this semester’s course survey data. Find the following:
<ol style="list-style-type: lower-alpha">
<li>frequency distribution</li>
<li>mode</li>
</ol></li>
<li>Create a bar plot of the categorical variable you chose in (9). Make sure to give it an appropriate title and axis labels.</li>
</ol>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression-and-correlation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
