<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 6 Introduction to Confidence Intervals | Introduction to Statistics</title>
  <meta name="description" content="Module 6 Introduction to Confidence Intervals | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 6 Introduction to Confidence Intervals | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 6 Introduction to Confidence Intervals | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 6 Introduction to Confidence Intervals | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 6 Introduction to Confidence Intervals | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="random-variables.html"/>
<link rel="next" href="introduction-to-hypothesis-testing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-confidence-intervals" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Module 6</span> Introduction to Confidence Intervals<a href="introduction-to-confidence-intervals.html#introduction-to-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This module will bridge the gap between our discussion on the normal distribution and our first forays into statistical inference. As it turns out, much of the statistical inference we will use relies on the normal distribution and the t-distribution, which we will introduce in this module. We begin our study of statistical inference by learning about confidence intervals.</p>
<p><strong>Module Learning Objectives/Outcomes</strong></p>
<ol style="list-style-type: decimal">
<li>Find the distribution of a sample mean.</li>
<li>Estimate probabilities for a sample mean.</li>
<li>Use the standard normal and t-distributions to find critical values.</li>
<li>Calculate and interpret confidence intervals for a population mean.</li>
</ol>
<p><strong>R Objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Find z and t critical values.</li>
<li>Generate complete confidence intervals for a population mean.</li>
</ol>
<p>This module’s outcomes correspond to course outcome (6) apply statistical inference techniques of parameter estimation such as point estimation and confidence interval estimation and (7) apply techniques of testing various statistical hypotheses concerning population parameters.</p>
<div id="sampling-distributions" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Sampling Distributions<a href="introduction-to-confidence-intervals.html#sampling-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="sampling-error" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Sampling Error<a href="introduction-to-confidence-intervals.html#sampling-error" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We want to use a sample to learn something about a population, but no sample is perfect! <strong>Sampling error</strong> is the error resulting from using a sample to estimate a population characteristic.</p>
<p>If we use a sample mean <span class="math inline">\(\bar{x}\)</span> to estimate <span class="math inline">\(\mu\)</span>, chances are that <span class="math inline">\(\bar{x}\ne\mu\)</span> (they might be close but… they might not be!). We will consider</p>
<ul>
<li>How close <em>is</em> <span class="math inline">\(\bar{x}\)</span> to <span class="math inline">\(\mu\)</span>?</li>
<li>What if we took many samples and calculated <span class="math inline">\(\bar{x}\)</span> many times?
<ul>
<li>How would that relate to <span class="math inline">\(\mu\)</span>?</li>
<li>What would be the distribution of these values?</li>
</ul></li>
</ul>
<p>The distribution of a statistic (across all possible samples of size <span class="math inline">\(n\)</span>) is called the <strong>sampling distribution</strong>. We will focus primarily on the distribution of the sample mean.</p>
<p>For a variable <span class="math inline">\(x\)</span> and given a sample size <span class="math inline">\(n\)</span>, the distribution of <span class="math inline">\(\bar{x}\)</span> is called the <strong>sampling distribution of the sample mean</strong> or the <strong>distribution of <span class="math inline">\(\boldsymbol{\bar{x}}\)</span></strong>.</p>
<blockquote>
<p><strong>Example</strong>: Suppose our population is the five starting players on the Sacramento Kings during their game on April 2, 2024. We are interested in their heights (measures in inches). The full population data is</p>
<table>
<colgroup>
<col width="11%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Player</th>
<th align="center">De’Aaron Fox</th>
<th align="center">Keon Ellis</th>
<th align="center">Harrison Barnes</th>
<th align="center">Keegan Murray</th>
<th align="center">Domantas Sabonis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Height</td>
<td align="center">73</td>
<td align="center">73</td>
<td align="center">78</td>
<td align="center">78</td>
<td align="center">80</td>
</tr>
</tbody>
</table>
<p>The population mean is <span class="math inline">\(\mu=76.4\)</span>. Consider all possible samples of size <span class="math inline">\(n=2\)</span>:</p>
<table>
<thead>
<tr class="header">
<th align="left">Sample</th>
<th align="left"><span class="math inline">\(\bar{x}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fox, Ellis</td>
<td align="left">73</td>
</tr>
<tr class="even">
<td align="left">Fox, Barnes</td>
<td align="left">75.5</td>
</tr>
<tr class="odd">
<td align="left">Fox, Murray</td>
<td align="left">75.5</td>
</tr>
<tr class="even">
<td align="left">Fox, Sabonis</td>
<td align="left">76.5</td>
</tr>
<tr class="odd">
<td align="left">Ellis, Barnes</td>
<td align="left">75.5</td>
</tr>
<tr class="even">
<td align="left">Ellis, Murray</td>
<td align="left">75.5</td>
</tr>
<tr class="odd">
<td align="left">Ellis, Sabonis</td>
<td align="left">76.5</td>
</tr>
<tr class="even">
<td align="left">Barnes, Murray</td>
<td align="left">78</td>
</tr>
<tr class="odd">
<td align="left">Barnes, Sabonis</td>
<td align="left">79</td>
</tr>
<tr class="even">
<td align="left">Murray, Sabonis</td>
<td align="left">79</td>
</tr>
</tbody>
</table>
<p>There are 10 possible samples of size 2. Of these samples, <em>none</em> have means exactly equal to <span class="math inline">\(\mu\)</span>.</p>
</blockquote>
<p>In general, the larger the sample size, the smaller the sampling error tends to be in estimating <span class="math inline">\(\mu\)</span> using <span class="math inline">\(\bar{x}\)</span>.</p>
<p>In practice, we have one sample and <span class="math inline">\(\mu\)</span> is unknown. We also have limited resources to collect data, so it may not be feasible to collect a very large sample.</p>
<p>The mean of the distribution of <span class="math inline">\(\bar{x}\)</span> is <span class="math inline">\(\mu_{\bar{X}}=\mu\)</span> and the standard deviation is <span class="math inline">\(\sigma_{\bar{X}}=\sigma/\sqrt{n}\)</span>. We refer to the standard deviation of a sampling distribution as <strong>standard error</strong>. (Note that this standard error formula is built for very large populations, so it will not work well for our basketball players. This is okay! We usually work with populations so large that we treat them as “infinite”.)</p>
<blockquote>
<p><strong>Example</strong>: The mean house size in the United States is 2164 ft<span class="math inline">\(^2\)</span> with a standard deviation of 568 square feet. For samples of 25 homes, determine the mean and standard error of <span class="math inline">\(\bar{x}\)</span>.</p>
<p>Using our formulae: <span class="math display">\[\mu_{\bar{X}} = \mu = 2164\]</span> and <span class="math display">\[\sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}} = \frac{568}{\sqrt{25}} = 113.6.\]</span></p>
</blockquote>
</div>
<div id="the-central-limit-theorem" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> The Central Limit Theorem<a href="introduction-to-confidence-intervals.html#the-central-limit-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider the setting where <span class="math inline">\(X\)</span> is Normal(<span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>). The plots below show (A) a random sample of 1000 from a Normal(100, 25) distribution and (B) the approximate sampling distribution of <span class="math inline">\(\bar{X}\)</span> when X is Normal(100, 25).</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-93-1.png" alt="" width="672" /></p>
<p>Notice how the x-axis changes from one plot to the next.</p>
<p>In fact, if <span class="math inline">\(X\)</span> is Normal(<span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>), then <span class="math inline">\(\bar{X}\)</span> is Normal(<span class="math inline">\(\mu_{\bar{X}}=\mu\)</span>, <span class="math inline">\(\sigma_{\bar{X}}=\sigma/\sqrt{n}\)</span>).</p>
<p>Surprisingly, we see a similar result for <span class="math inline">\(\bar{X}\)</span> even when <span class="math inline">\(X\)</span> is not normally distributed!</p>
<center>
<font size='4'><b>Central Limit Theorem</b></font>
</center>
<p>For relatively large sample sizes, the random variable <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed <em>regardless of the distribution of</em> <span class="math inline">\(X\)</span>: <span class="math display">\[\bar{X}\text{ is Normal}(\mu_{\bar{X}}=\mu, \sigma_{\bar{X}}=\sigma/\sqrt{n}).\]</span></p>
<p>Notes</p>
<ul>
<li>This approximation improves with increasing sample size.</li>
<li>In general, “relatively large” means sample sizes <span class="math inline">\(n \ge 30\)</span>.</li>
</ul>
</div>
<div id="section-exercises-16" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-confidence-intervals.html#section-exercises-16" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The mean house size in Hong Kong is 484 ft<span class="math inline">\(^2\)</span> with a standard deviation of 163 ft<span class="math inline">\(^2\)</span> (this mean is accurate as of 2024, but the standard deviation is a guesstimate for the sake of the problem).
<ol style="list-style-type: lower-alpha">
<li>Determine <span class="math inline">\(\mu_{\bar{X}}\)</span> and <span class="math inline">\(\sigma_{\bar{X}}\)</span> for samples of size 22.</li>
<li>Determine <span class="math inline">\(\mu_{\bar{X}}\)</span> and <span class="math inline">\(\sigma_{\bar{X}}\)</span> for samples of size 100.</li>
<li>For which of the above (<span class="math inline">\(n=22\)</span> or <span class="math inline">\(n=100\)</span>) can we assume the sampling distribution is normal, <em>without knowing anything else about the data</em>?</li>
<li>For a random sample of 100 houses, what is the probability the mean size is less than 400 ft<span class="math inline">\(^2\)</span>?</li>
</ol></li>
<li>Suppose we have some population with <span class="math inline">\(\sigma=5\)</span>. Determine the proportion of all samples of size 50 that will have means within 0.25 of the population mean.
<ol style="list-style-type: lower-alpha">
<li>Draw and label a normal curve with <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\mu\pm\sigma\)</span>, <span class="math inline">\(\mu\pm 2\sigma\)</span>, and <span class="math inline">\(\mu\pm 3\sigma\)</span>.</li>
<li>What is the sample size?</li>
<li>Determine <span class="math inline">\(\mu_{\bar{X}}\)</span> and <span class="math inline">\(\sigma_{\bar{X}}\)</span>.</li>
<li>Write an expression to represent the values 0.125 above and below the mean, <span class="math inline">\(\mu_{\bar{X}}\)</span>. (Since we don’t know the value of <span class="math inline">\(\mu_{\bar{X}}\)</span>, you should use <span class="math inline">\(\mu_{\bar{X}}\)</span> directly in your expression.)</li>
<li>Determine the z-score for each of the values you found in part (d).</li>
<li>Use your result from part (e) to determine the proportion of all samples of size 50 that will have means within 0.25 of the population mean.</li>
</ol></li>
</ol>
</div>
</div>
<div id="developing-confidence-intervals" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Developing Confidence Intervals<a href="introduction-to-confidence-intervals.html#developing-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall: A <strong>point estimate</strong> is a single-value estimate of a population parameter. We say that a statistic is an <strong>unbiased estimator</strong> if the mean of its distribution is equal to the population parameter. Otherwise, it is a <strong>biased estimator</strong>.</p>
<p><em>Comment</em>: Remember how our formula for sample variance, the “mean squared deviance” divides by <span class="math inline">\(n-1\)</span> instead of <span class="math inline">\(n\)</span>? We do this so that <span class="math inline">\(s\)</span> is an <em>unbiased</em> estimate of <span class="math inline">\(\sigma\)</span>.</p>
<p>Ideally, we want estimates that are unbiased with small standard error. For example, a sample mean (unbiased) with a large sample size (results in smaller standard error).</p>
<p>Point estimates are useful, but they only give us so much information. The variability of an estimate is also important!</p>
<blockquote>
<p><strong>Example</strong> Think about estimating what tomorrow’s weather will be like. If it’s May in Sacramento, the average high temperature is 82 degrees Fahrenheit, but it’s not uncommon to have highs anywhere from 75 to 90! Since the highs are so <em>variable</em>, it’s hard to be confident using 82 to predict tomorrow’s weather.</p>
<p>On the flip side, think about July in Phoenix. The average high is 106 degrees Fahrenheit. In Phoenix, it’s uncommon to have a July day with a high below 100. Since the highs are <em>not variable</em>, you could feel pretty confident using 106 to predict tomorrow’s weather.</p>
</blockquote>
<p>Take a look at these two boxplots:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-94-1.png" alt="" width="672" /></p>
<p>Both samples are size <span class="math inline">\(n=100\)</span> and have <span class="math inline">\(\bar{x}=0\)</span>, which would be our point estimate for <span class="math inline">\(\mu\)</span>… but Variable 1 has a standard deviation of <span class="math inline">\(\sigma=0.5\)</span> and Variable 2 has standard deviation <span class="math inline">\(\sigma=5\)</span>. As a result, we can be more confident in our estimate of the population mean for Variable 1 than for Variable 2.</p>
<p>We want to formalize this idea of confidence in our estimates. A <strong>confidence interval</strong> is an interval of numbers based on the point estimate of the parameter. Say we want to be 95% confident about a statement. In Statistics, this means that we have arrived at our statement using a method that will give us a correct statement 95% of the time.</p>
<p>Our best point estimate for <span class="math inline">\(\mu\)</span> (based on a random sample) is <span class="math inline">\(\bar{x}\)</span>, so that value will make up the center (or midpoint) of the interval. To create an interval around <span class="math inline">\(\bar{x}\)</span>, we will construct what is called the <strong>margin of error</strong>. We will use the variability of the data along with some normal distribution properties. This will look like <span class="math display">\[z\times\frac{\sigma}{\sqrt{n}}\]</span> The value <span class="math inline">\(z\)</span> will come from the normal distribution and will be based on how confident we want to be, e.g., 95% confident.</p>
<p>Putting everything together, the 95% confidence interval is <span class="math display">\[\left(\bar{x} - z_*\frac{\sigma}{\sqrt{n}}, \bar{x} + z_*\frac{\sigma}{\sqrt{n}}\right)\]</span> where <span class="math inline">\(z_* = 1.96\)</span>. The value <span class="math inline">\(1.96\)</span> is chosen because <span class="math inline">\(P(-1.96 &lt; Z &lt; 1.96) = 0.95\)</span> (this is what makes it a 95% confidence interval!).</p>
<p><em>Note</em>: A more detailed mathematical explanation of how we get this interval is available in Appendix C.</p>
<div id="interpreting-a-confidence-interval" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Interpreting a Confidence Interval<a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To interpret a confidence interval, we need to think back to our definition of probability as “the proportion of times an event would occur if the experiment were run infinitely many times”. In the confidence interval case, if an experiment is run infinitely many times, the true value of <span class="math inline">\(\mu\)</span> will be contained in 95% of the intervals.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-95-1.png" alt="" width="672" /></p>
<p>The graphic above shows 95% confidence intervals for 100 samples of size <span class="math inline">\(n=60\)</span> drawn from a population with mean <span class="math inline">\(\mu=80\)</span> and standard deviation <span class="math inline">\(\sigma=25\)</span>. Each sample’s confidence interval is represented by a horizontal line. The dot in the middle of each is the sample mean. When a confidence interval does <em>not</em> capture the population mean <span class="math inline">\(\mu\)</span>, the line is printed in red. Based on this concept of repeated sampling, we would expect about 95% of these intervals to capture <span class="math inline">\(\mu\)</span>. In fact, 96 of the 100 intervals capture <span class="math inline">\(\mu\)</span>.</p>
<p>Finally, when you interpret a confidence interval, it is important to do so in the context of the problem.</p>
<blockquote>
<p><strong>Example</strong> Suppose I took a random sample of 50 Sac State students and asked about their SAT scores and found a mean score of 1112. Prior experience with SAT scores in the CSU system suggests that SAT scores are well-approximated by a normal distribution with standard deviation known to be 50.</p>
<ol style="list-style-type: decimal">
<li>Find and interpret a 95% confidence interval for Sac State SAT scores.</li>
<li>What is the width of your interval? If you want a narrower interval, what could you do?</li>
</ol>
<p><em>Solution</em> Here, <span class="math inline">\(\bar{x} = 1112\)</span>, <span class="math inline">\(\sigma=50\)</span>, and <span class="math inline">\(n=50\)</span>.</p>
<p>The interval is <span class="math display">\[
\bar{x} \pm z_{*\alpha/2*}\frac{\sigma}{\sqrt{n}} = 1112 \pm 1.96\times\frac{50}{\sqrt{50}} = 1112 \pm 13.86 = (1098.1, 1125.9).
\]</span>
Interpretation: We can be 95% confident that the true mean SAT score for Sac State students is between 1098.1 and 1125.9.</p>
</blockquote>
<p>Notice that I kept the interpretation simple! “We can be [x]% confident that the true mean [fill in from problem statement] is between [lower value] and [upper value].” As appropriate, we should also be sure to include any units. A simple interpretation is fine - just be sure you are <em>also</em> able to explain what it means to be 95% confident (using the concept of repeated sampling).</p>
<p>Common mistakes:</p>
<ul>
<li>It is NOT accurate to say that “the probability that <span class="math inline">\(\mu\)</span> is in the confidence interval is 0.95”. The parameter <span class="math inline">\(\mu\)</span> is some fixed quantity and it’s either in the interval or it isn’t.</li>
<li>We are NOT “95% confident that <span class="math inline">\(\bar{x}\)</span> is in the interval”. The value <span class="math inline">\(\bar{x}\)</span> is some known quantity and it’s always in the interval.</li>
</ul>
</div>
<div id="section-exercises-17" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-confidence-intervals.html#section-exercises-17" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Interpret each confidence interval in the context of the setting.
<ol style="list-style-type: lower-alpha">
<li>A 95% confidence interval for the mean ACT score of Sac State students was (21.2, 25.1).</li>
<li>A 90% confidence interval for the mean number of burritos eaten by Californian adults each week was (0.5, 2.1).</li>
<li>A 98% confidence interval for the mean height (in inches) of corgis was (10.1, 11.7).</li>
</ol></li>
<li>Describe in your own words what is meant by “95% confident”.</li>
</ol>
</div>
</div>
<div id="other-levels-of-confidence" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Other Levels of Confidence<a href="introduction-to-confidence-intervals.html#other-levels-of-confidence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While the 95% confidence interval is common in research, there’s nothing inherently special about it. You could calculate a 90%, a 99%, or - if you’re feeling spicy - something like a 43.8% confidence interval. These numbers are called the <strong>confidence level</strong> and they represent the proportion of times that the parameter will fall in the interval (if we took many samples).</p>
<p>The 100(1-<span class="math inline">\(\alpha\)</span>)% confidence interval for <span class="math inline">\(\mu\)</span> is given by <span class="math display">\[\bar{x}\pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\]</span> where <span class="math inline">\(z_{\alpha/2}\)</span> is the z-score associated with the <span class="math inline">\([1-(\alpha/2)]\)</span>th percentile of the standard normal distribution. The value <span class="math inline">\(z_{\alpha/2}\)</span> is called the <strong>critical value</strong> (“c.v.” on the plot, below).</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-96-1.png" alt="" width="672" /></p>
<p>Using the those normal distribution properties, we can also say that <span class="math inline">\(P(Z &gt; z_{\alpha/2}) = \alpha/2\)</span>. Depending on how you’ve been using software to find normal distribution probabilities, you may find you prefer this approach to the percentile approach.</p>
<center>
<font size='4'><b>Common Critical Values</b></font>
</center>
<table>
<thead>
<tr class="header">
<th align="center">Confidence Level</th>
<th align="center"><span class="math inline">\(\alpha\)</span></th>
<th align="center">Critical Value, <span class="math inline">\(z_{\alpha/2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">90%</td>
<td align="center">0.10</td>
<td align="center">1.645</td>
</tr>
<tr class="even">
<td align="center">95%</td>
<td align="center">0.05</td>
<td align="center">1.96</td>
</tr>
<tr class="odd">
<td align="center">98%</td>
<td align="center">0.02</td>
<td align="center">2.326</td>
</tr>
<tr class="even">
<td align="center">99%</td>
<td align="center">0.01</td>
<td align="center">2.575</td>
</tr>
</tbody>
</table>
<p>A good exercise: make sure you are comfortable using software to find critical values by finding the common critical values given in the table above.</p>
<blockquote>
<p><strong>Example</strong> In the previous section, we worked with a random sample of 50 Sac State students with mean SAT score 1112. Prior experience with SAT scores in the CSU system suggests that SAT scores are well-approximated by a normal distribution with standard deviation known to be 50.</p>
<ol style="list-style-type: lower-alpha">
<li>Find and interpret a 98% confidence interval.</li>
<li>Find and interpret a 90% confidence interval.</li>
<li>Comment on how the intervals change as you change the confidence level.</li>
</ol>
<p><em>Solution</em> Again, <span class="math inline">\(\bar{x} = 1112\)</span>, <span class="math inline">\(\sigma=50\)</span>, and <span class="math inline">\(n=50\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>For a 98% interval, <span class="math inline">\(\alpha=0.02\)</span> and <span class="math inline">\(z_{0.02/2} = 2.326\)</span>. So the interval is <span class="math display">\[
\bar{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}} = 1112 \pm 2.326\times\frac{50}{\sqrt{50}} = 1112 \pm 16.4 = (1095.6, 1128.4)
\]</span>
We can be 98% confident that the true mean SAT score for Sac State students is between 1095.6 and 1128.4.</li>
<li>For a 90% interval, <span class="math inline">\(\alpha=0.1\)</span> and <span class="math inline">\(z_{0.1/2} = 1.645\)</span>. So the interval is <span class="math display">\[
\bar{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}} = 1112 \pm 1.645\times\frac{50}{\sqrt{50}} = 1112 \pm 11.6 = (1100.4, 1123.6)
\]</span>
We can be 90% confident that the true mean SAT score for Sac State students is between 1100.4 and 1123.6</li>
<li>As the level of confidence <em>increases</em>, the interval width <em>decreases</em>.</li>
</ol>
</blockquote>
<div id="breaking-down-a-confidence-interval" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Breaking Down a Confidence Interval<a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider <span class="math display">\[\left(\bar{x}- z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \quad \bar{x} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)\]</span> The key values are</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span>, the sample mean</li>
<li><span class="math inline">\(\sigma\)</span>, the population standard deviation</li>
<li><span class="math inline">\(n\)</span>, the sample size</li>
<li><span class="math inline">\(z_{\alpha/2}\)</span>, the critical value <span class="math display">\[P(Z &gt; z_{\alpha/2}) = \frac{\alpha}{2}\]</span></li>
</ul>
<p>The value of interest is <span class="math inline">\(\mu\)</span>, the (unknown) population mean; the confidence interval gives us a reasonable range of values for <span class="math inline">\(\mu\)</span>.</p>
<p>In addition, the formula includes</p>
<ul>
<li>The standard error, <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span></li>
<li>The margin of error, <span class="math inline">\(z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\)</span></li>
</ul>
</div>
<div id="section-exercises-18" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-confidence-intervals.html#section-exercises-18" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Find <span class="math inline">\(\alpha\)</span>, then use a computer to find the corresponding critical value <span class="math inline">\(z_{\alpha/2}\)</span> for
<ol style="list-style-type: lower-alpha">
<li>A 92% level of confidence.</li>
<li>A 37% level of confidence.</li>
<li>An 85% level of confidence.</li>
</ol></li>
<li>We saw in the last example that the level of confidence impacts the width of the confidence interval. When we think about collecting data and calculating a confidence interval, what else can we do to change the width of the interval?</li>
</ol>
</div>
</div>
<div id="confidence-level-precision-and-sample-size" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Confidence Level, Precision, and Sample Size<a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we can be 99% confident (or even higher), why do we tend to “settle” for 95%?? Take a look at the common critical values (above) and the confidence interval formula <span class="math display">\[\bar{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}.\]</span> What will higher levels of confidence do to this interval? Think back to the intuitive interval width explanation with the weather. Mathematically, the same thing will happen: the interval will get wider! And remember, a narrow interval is a more informative interval. There is a trade off here between interval width and confidence. In general, the scientific community has settled on 95% as a compromise between the two, but different fields may use different levels of confidence.</p>
<p>There is one other thing we can control in the confidence interval: the sample size <span class="math inline">\(n\)</span>. One strategy is to specify the confidence level and the maximum acceptable interval width and use these to determine sample size. We know that <span class="math display">\[\text{interval width} = 2z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\]</span> When determining sample size, <span class="math inline">\(2z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\)</span> is the <em>maximum</em> acceptable interval width, so we will consider <span class="math display">\[\text{interval width} \ge 2z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\]</span> since we would still be happy if this value turned out to be smaller! Letting interval width equal <span class="math inline">\(w\)</span>, we then solve for <span class="math inline">\(n\)</span>:
<span class="math display">\[\begin{aligned}
  w &amp;\ge 2z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \\
  w\sqrt{n} &amp;\ge 2z_{\alpha/2}\sigma \\
  \sqrt{n} &amp;\ge 2z_{\alpha/2}\frac{\sigma}{w} \\
  n &amp;\ge \left(2z_{\alpha/2}\frac{\sigma}{w}\right)^2
\end{aligned}\]</span>
Alternately, we may specify a maximum margin of error <span class="math inline">\(m\)</span> instead:
<span class="math display">\[
  \begin{aligned}
  m &amp;\ge z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \\
  m\sqrt{n} &amp;\ge z_{\alpha/2}\sigma \\
  \sqrt{n} &amp;\ge z_{\alpha/2}\frac{\sigma}{m} \\
  n &amp;\ge \left(z_{\alpha/2}\frac{\sigma}{m}\right)^2
\end{aligned}
\]</span>
Once we’ve done this calculation, we need a whole number for <span class="math inline">\(n\)</span>. Since <span class="math inline">\(n \ge\)</span> something, we will <em>always round up</em>.</p>
<blockquote>
<p><strong>Example</strong> Suppose we want a 95% confidence interval for the mean of a normally distributed population with standard deviation <span class="math inline">\(\sigma=10\)</span>. It is important for our margin of error to be no more than 2. What sample size do we need?</p>
<p>Using the formula for sample size with a desired margin of error, I can plug in <span class="math inline">\(z_{0.05/2}=1.96\)</span>, <span class="math inline">\(m=2\)</span> and <span class="math inline">\(\sigma=10\)</span>: <span class="math display">\[n = \left(1.96\times\frac{10}{2}\right)^2 = 96.04\]</span> So (rounding up!) I need a sample size of <em>at least 97</em>.</p>
</blockquote>
<p>A few comments:</p>
<ul>
<li>As desired width/margin of error decreases, <span class="math inline">\(n\)</span> will increase.</li>
<li>As <span class="math inline">\(\sigma\)</span> increases, <span class="math inline">\(n\)</span> will also increase. (More population variability will necessitate a larger sample size.)</li>
<li>As confidence level increases, <span class="math inline">\(n\)</span> will also increase.</li>
</ul>
<div id="section-exercises-19" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-confidence-intervals.html#section-exercises-19" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Find the sample size necessary in each of the following settings.
<ol style="list-style-type: lower-alpha">
<li>Suppose <span class="math inline">\(\sigma = 4\)</span>. We wish to construct a 90% confidence interval with a maximum width of 10.</li>
<li>Suppose <span class="math inline">\(\sigma = 12\)</span>. We wish to construct a 98% confidence interval with a maximum width of 15.</li>
<li>Suppose <span class="math inline">\(\sigma = 2\)</span>. We wish to construct a 92% confidence interval with a maximum margin of error of 5.</li>
<li>Suppose <span class="math inline">\(\sigma = 10\)</span>. We wish to construct a 99% confidence interval with a maximum margin of error of 3.</li>
</ol></li>
<li>Prior experience with SAT scores in the CSU system suggests that SAT scores are well-approximated by a normal distribution with standard deviation known to be 50. Find the sample size required for a 98% confidence interval with maximum margin of error 10.</li>
<li>In practice, we want contradictory things: small margin of error, high level of confidence, and small sample size (often due to time/monetary constraints).
<ol style="list-style-type: lower-alpha">
<li>Come up with a scenario where it will be especially important to have a small margin of error and a high level of confidence, and therefore worth spending a lot of resources on gathering a large sample size.</li>
<li>Come up with a second research scenario where it may be impractical to gather a large sample size. In your scenario, is it more important to prioritize interval width or confidence level? Explain your thought process.</li>
</ol></li>
</ol>
</div>
</div>
<div id="confidence-intervals-for-a-mean" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Confidence Intervals for a Mean<a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In practice, the value of <span class="math inline">\(\sigma\)</span> is almost never known… but we know that we can estimate <span class="math inline">\(\sigma\)</span> using <span class="math inline">\(s\)</span>. Can we plug in <span class="math inline">\(s\)</span> for <span class="math inline">\(\sigma\)</span>? Sometimes!</p>
<p>Remember the Central Limit Theorem from earlier in this this module? For samples of size <span class="math inline">\(n \ge 30\)</span>, <span class="math inline">\(\bar{X}\)</span> will be approximately normal even if <span class="math inline">\(X\)</span> isn’t. In this case, we can plug in <span class="math inline">\(s\)</span> for <span class="math inline">\(\sigma\)</span>: <span class="math display">\[\bar{x} \pm z_{\alpha/2}\frac{s}{\sqrt{n}}.\]</span></p>
<p>That setting is pretty straightforward! Now we need to consider the setting where <span class="math inline">\(n &lt; 30\)</span>, which will require a bit of additional work.</p>
<blockquote>
<p><strong>Example</strong>: The General Social Survey (GSS) is a sociological survey used to collect data on demographic characteristics and attitudes of residents of the United States. In 2010, the survey collected responses from 1,154 US residents. The survey is conducted face-to-face with an in-person interview of a randomly selected sample of adults. One of the questions on the survey is “After an average workday, about how many hours do you have to relax or pursue activities that you enjoy?”. The average time spent relaxing was 3.68 hours, with a standard deviation of 2.6 hours.</p>
<p>Find and interpret a 95% confidence interval for the average time spent relaxing after work.</p>
<p><em>Solution</em>: Clearly, <span class="math inline">\(n = 1154 \ge 30\)</span>, so we can use the normal distribution for our critical value. We want a 95% interval, so we will use critical value <span class="math inline">\(z_{0.05/2} = z_{0.025} = 1.96\)</span>.</p>
<p>Further, we can see in the prompt that the sample resulted in sample mean <span class="math inline">\(\bar{x} = 3.68\)</span> and standard deviation <span class="math inline">\(s = 2.6\)</span>. So the 95% interval is
<span class="math display">\[ \bar{x} \pm z_{\alpha/2}\frac{s}{\sqrt{n}} = 3.68 \pm 1.96 \frac{2.6}{\sqrt{1154}} = 3.68 \pm 0.15\]</span>
which results in the interval <span class="math inline">\((3.53, 3.83)\)</span>.</p>
<p>Interpretation: we can be 95% confident that the true mean number of hours spent relaxing after work is between 3.53 and 3.83.</p>
</blockquote>
<div id="the-t-distribution" class="section level3 hasAnchor" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> The T-Distribution<a href="introduction-to-confidence-intervals.html#the-t-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Enter: the t-distribution. If <span class="math display">\[Z = \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\]</span> has a standard normal distribution (for <span class="math inline">\(X\)</span> normal or <span class="math inline">\(n\ge30\)</span>), the slightly modified <span class="math display">\[T = \frac{\bar{X}-\mu}{s/\sqrt{n}}\]</span> has what we call the <strong>t-distribution</strong> with <span class="math inline">\(n-1\)</span> <strong>degrees of freedom</strong> (even when <span class="math inline">\(n &lt; 30\)</span>!). The only thing we need to know about degrees of freedom is that <span class="math inline">\(\text{df}=n-1\)</span> is the t-distribution’s only parameter.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-97-1.png" alt="" width="672" /></p>
<p>The t-distribution is symmetric and always centered at 0. When <span class="math inline">\(n\ge30\)</span>, the t-distribution is approximately equivalent to the standard normal distribution. For smaller sample sizes, the t-distribution has more area in the tails (and therefore less area in the center of the distribution). Therefore, we can always use t confidence intervals (even if <span class="math inline">\(n\)</span> is large) because the critical values are essentially equivalent between the t and standard normal distributions for large values of <span class="math inline">\(n\)</span>. This is usually what happens in practice.</p>
<p>In practice, we plug in <span class="math inline">\(s\)</span> for <span class="math inline">\(\sigma\)</span> and almost always use a t critical value (instead of a z critical value): <span class="math inline">\(t_{\text{df}, \, \alpha/2}\)</span>. The t critical value is the <span class="math inline">\([1- \alpha/2]\)</span>th percentile of the t-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. The resulting 95% confidence interval is <span class="math display">\[\bar{x} \pm t_{\text{df}, \, \alpha/2}\frac{s}{\sqrt{n}}.\]</span></p>
<p>You may use the applet, <a href="http://www.rossmanchance.com/applets/2021/tcalc/tCalc.htm" target="blank">Rossman and Chance t Probability Calculator</a> to find t critical values. For this applet, enter the degrees of freedom <span class="math inline">\(n-1\)</span> next to “df”. Then check the top box under “t-value probability” and make sure the inequality is clicked to “&gt;” . Enter the value of <span class="math inline">\(\alpha/2\)</span> for the probability. Click anywhere else on the page and the applet will automatically fill in the box under “t-value”. This is your t critical value.</p>
<blockquote>
<p><strong>Example</strong>: The following table gives a few t critical values. You should make sure you can use the degrees of freedom and <span class="math inline">\(\alpha\)</span> to replicate those t critical values using a computer.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(n\)</span></th>
<th align="center"><span class="math inline">\(\alpha\)</span></th>
<th align="center"><span class="math inline">\(t_{\text{df}, \, \alpha/2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">14</td>
<td align="center">0.05</td>
<td align="center">2.160</td>
</tr>
<tr class="even">
<td align="center">17</td>
<td align="center">0.1</td>
<td align="center">1.746</td>
</tr>
<tr class="odd">
<td align="center">24</td>
<td align="center">0.02</td>
<td align="center">2.500</td>
</tr>
</tbody>
</table>
</blockquote>
<blockquote>
<p><strong>Example</strong>: The weights of 6 randomly selected NFL linebackers were <span class="math inline">\(243, 238, 229, 253, 248, 225\)</span>. Find a 90% confidence interval for the average weight of NFL linebackers.</p>
<p><em>Solution</em>: Right away, we can see that <span class="math inline">\(n=6&lt;30\)</span> and so we will need to use a confidence interval with a t critical value. Next, we calculate the mean and standard deviation from the data: <span class="math inline">\(\bar{x} = 239.3\)</span> and <span class="math inline">\(s = 10.9\)</span>.</p>
<p>The t-critical value for a 90% interval has <span class="math inline">\(\alpha=0.1\)</span> and <span class="math inline">\(\text{df}=6-1=5\)</span>. Using a computer, <span class="math inline">\(t_{\text{df}, \, \alpha/2} = t_{5, \, 0.05} = 2.015\)</span>. Then
<span class="math display">\[ \bar{x} \pm t_{\text{df}, \, \alpha/2}\frac{s}{\sqrt{n}} = 239.3 \pm 2.015 \times \frac{10.9}{\sqrt{6}} = 239.3 \pm 8.97\]</span>
which yields the interval <span class="math inline">\((230.3, 248.3)\)</span>.</p>
<p>Interpretation: we can be 90% confident that the average weight of NFL linebackers is between 230.3 and 248.3 pounds.</p>
</blockquote>
</div>
<div id="section-exercises-20" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-confidence-intervals.html#section-exercises-20" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Find the t critical values for each combination of sample size and confidence level.
<ol style="list-style-type: lower-alpha">
<li>95%, <span class="math inline">\(n=19\)</span></li>
<li>90%, <span class="math inline">\(n=27\)</span></li>
<li>80%, <span class="math inline">\(n=7\)</span></li>
</ol></li>
<li>In 1-2 sentences, explain the difference between the Z (standard normal) and the t-distribution. What properties do these distributions have in common? How do they differ?</li>
<li>Refer to the example above on NFL linebackers. Find and interpret
<ol style="list-style-type: lower-alpha">
<li>A 95% confidence interval for mean weight of NFL linebackers.</li>
<li>A 98% confidence interval for mean weight of NFL linebackers.</li>
<li>A 99% confidence interval for mean weight of NFL linebackers.</li>
</ol></li>
<li>Researchers took a random sample of 20 green sea turtle nests and counted the number of eggs in each. They found a mean of 107.3 eggs with standard deviation 13.7.
<ol style="list-style-type: lower-alpha">
<li>Should we use a z or a t critical value in this setting? Explain.</li>
<li>Find and interpret a 95% confidence interval for the mean number of eggs in a green sea turtle nest.</li>
<li>Find and interpret a 98% confidence interval for the mean number of eggs in a green sea turtle nest.</li>
<li>Suppose <span class="math inline">\(\mu = 105\)</span>. Did the confidence intervals do a good job of estimating <span class="math inline">\(\mu\)</span>? Explain.</li>
</ol></li>
<li>Some Sac State students wanted to know how: long is an average commute to campus? A random sample of 32 students resulted in a mean of 31 minutes with standard deviation 18 minutes.
<ol style="list-style-type: lower-alpha">
<li>Should we use a z or a t critical value in this setting? Explain.</li>
<li>Find and interpret a 95% confidence interval for mean commute time.</li>
<li>Find and interpret a 90% confidence interval for mean commute time.</li>
</ol></li>
<li>A city council member suspects that people speed through a certain intersection. They want to know the average speed at which drivers enter the intersection. They set up a speed camera and randomly sample 250 vehicles at different times of day, which results in a mean speed of 52 mph with standard deviation 8 mph.
<ol style="list-style-type: lower-alpha">
<li>Find and interpret a 95% confidence interval for the mean speed at which drivers take the intersection.</li>
<li>Suppose the posted speed limit is 45mph. Does the interval suggest that people speed? Explain your thought process.</li>
</ol></li>
</ol>
</div>
</div>
<div id="r-lab-confidence-intervals" class="section level2 unnumbered hasAnchor">
<h2>R Lab: Confidence Intervals<a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="finding-z-critical-values" class="section level3 unnumbered hasAnchor">
<h3>Finding Z Critical Values<a href="introduction-to-confidence-intervals.html#finding-z-critical-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can find critical values in R using the same command we used to find percentiles: <code>qnorm</code>. Recall that <span class="math inline">\(z_{\alpha/2}\)</span> is the z-score associated with the <span class="math inline">\([1-(\alpha/2)]\)</span>th percentile of the standard normal distribution. So for a <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval, we need to find the value of <span class="math inline">\(1-\alpha/2\)</span> to input into the <code>qnorm</code> command.</p>
<p>For example, to find <span class="math inline">\(z_{\alpha/2}\)</span> for a 93% confidence interval, we would use <span class="math display">\[(1-\alpha)100\% = 93\%\]</span> to solve for <span class="math inline">\(\alpha\)</span> and get <span class="math inline">\(\alpha = 0.07\)</span>. Then we need the <span class="math inline">\([1-(\alpha/2)]\)</span>th percentile: <span class="math display">\[1-\frac{\alpha}{2} = 1 - \frac{0.07}{2} = 0.965\]</span> Finally, we enter this value into the <code>qnorm</code> command:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="introduction-to-confidence-intervals.html#cb75-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.965</span>)</span></code></pre></div>
<pre><code>## [1] 1.811911</code></pre>
<p>and the critical value for a 93% confidence interval is <span class="math inline">\(z_{\alpha/2}=1.812\)</span>.</p>
</div>
<div id="finding-t-critical-values" class="section level3 unnumbered hasAnchor">
<h3>Finding T Critical Values<a href="introduction-to-confidence-intervals.html#finding-t-critical-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a t critical value, we will again use R, now with the command <code>qt</code>. (Notice that this is similar to the command for the standard normal distribution, but instead of “norm” for normal it has “t” for the t-distribution.) The <code>qt</code> command takes in the following:</p>
<ul>
<li><code>p</code>, the probability</li>
<li><code>df</code>, the degrees of freedom</li>
</ul>
<p>For example, for a 98% interval with a sample size of 15, <span class="math display">\[100(1-\alpha) = 98 \implies \alpha=0.02\]</span> Then <span class="math inline">\(1-\alpha/2 = 0.99\)</span> and <span class="math inline">\(\text{df}=15-1=14\)</span>.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="introduction-to-confidence-intervals.html#cb77-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.99</span>, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div>
<pre><code>## [1] 2.624494</code></pre>
<p>which gives the t critical value <span class="math inline">\(t_{14,\alpha/2} = 2.625\)</span>.</p>
</div>
<div id="confidence-intevals-for-a-mean" class="section level3 unnumbered hasAnchor">
<h3>Confidence Intevals for a Mean<a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To generate complete confidence intervals for a mean in R, we will use our confidence interval formula, <span class="math display">\[\bar{x} \pm (\text{critical value})\times\frac{s}{\sqrt{n}}\]</span> where the critical value is either <span class="math inline">\(z_{\alpha/2}\)</span> or <span class="math inline">\(t_{\text{df}, \alpha/2}\)</span>.</p>
<p>We will continue to use the <code>Loblolly</code> pine tree data.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="introduction-to-confidence-intervals.html#cb79-1" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span></code></pre></div>
<p>In this case, the variable of interest is <code>x = height</code> and the desired confidence level is <code>conf.level = 0.95</code>. We can check how many observations we have (the sample size) by using the command <code>length()</code> and putting the variable name in the parentheses:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="introduction-to-confidence-intervals.html#cb80-1" tabindex="-1"></a><span class="fu">length</span>(height)</span></code></pre></div>
<pre><code>## [1] 84</code></pre>
<p>Then we can find the sample mean and sample standard deviation of the <code>height</code> variable:</p>
<pre><code>## [1] 32.3644</code></pre>
<pre><code>## [1] 20.6736</code></pre>
<p>Since <span class="math inline">\(n = 84 &gt; 30\)</span>, we will use the standard normal distribution. Let’s find the critical value for a 95% confidence interval. Here, <span class="math display">\[1-\frac{\alpha}{2} = 1 - \frac{0.05}{2} = 0.975\]</span> so the R command will be</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="introduction-to-confidence-intervals.html#cb84-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<p>Finally, we can put this all together. As when you use your calculator, pay close attention to order of operations in R. If in doubt, use parentheses!</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="introduction-to-confidence-intervals.html#cb86-1" tabindex="-1"></a><span class="fl">32.36</span> <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>(<span class="fl">20.67</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">84</span>))</span></code></pre></div>
<pre><code>## [1] 27.93965</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="introduction-to-confidence-intervals.html#cb88-1" tabindex="-1"></a><span class="fl">32.36</span> <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>(<span class="fl">20.67</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">84</span>))</span></code></pre></div>
<pre><code>## [1] 36.78035</code></pre>
<p>So a 95% confidence interval for <code>height</code> is <span class="math inline">\((27.94, 36.78)\)</span>. We can say that we are 95% confident that the true mean height of the loblolly pines is between 27.94 and 36.78 feet (assuming the researchers took a random sample of trees).</p>
<p>Alternately, if you’re starting to feel comfortable with R, we can put all of this together into one:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="introduction-to-confidence-intervals.html#cb90-1" tabindex="-1"></a><span class="fu">mean</span>(height) <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>(<span class="fu">sd</span>(height)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(height)))</span></code></pre></div>
<pre><code>## [1] 27.94336</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="introduction-to-confidence-intervals.html#cb92-1" tabindex="-1"></a><span class="fu">mean</span>(height) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>(<span class="fu">sd</span>(height)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(height)))</span></code></pre></div>
<pre><code>## [1] 36.78545</code></pre>
<p>The numbers are slightly different only because R does not round until the very end.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introduction-to-confidence-intervals.html#cb94-1" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="random-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-hypothesis-testing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
