<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 7 Introduction to Hypothesis Testing | Introduction to Statistics</title>
  <meta name="description" content="Module 7 Introduction to Hypothesis Testing | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 7 Introduction to Hypothesis Testing | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 7 Introduction to Hypothesis Testing | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 7 Introduction to Hypothesis Testing | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 7 Introduction to Hypothesis Testing | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-confidence-intervals.html"/>
<link rel="next" href="inference-for-a-proportion.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-hypothesis-testing" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Module 7</span> Introduction to Hypothesis Testing<a href="introduction-to-hypothesis-testing.html#introduction-to-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this module, we will continue our discussion on statistical inference with a discussion on hypothesis testing. In hypothesis testing, we take a more active approach to our data by asking questions about population parameters and developing a framework to answer those questions. We will root this discussion in confidence intervals before learning about several other approaches to hypothesis testing.</p>
<p><strong>Module Learning Outcomes/Objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Test one sample means using
<ol style="list-style-type: lower-alpha">
<li>confidence intervals.</li>
<li>the critical value approach.</li>
<li>the p-value approach.</li>
</ol></li>
</ol>
<p><strong>R Objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Generate hypothesis tests for a mean.</li>
<li>Interpret R output for tests of a mean.</li>
</ol>
<p>This module’s outcomes correspond to course outcomes (6) apply statistical inference techniques of parameter estimation such as point estimation and confidence interval estimation and (7) apply techniques of testing various statistical hypotheses concerning population parameters.</p>
<div id="logic-of-hypothesis-testing" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Logic of Hypothesis Testing<a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section is framed in terms of questions about a population mean <span class="math inline">\(\mu\)</span>, but the same logic applies to <span class="math inline">\(p\)</span> (and other population parameters).</p>
<p>One of our goals with statistical inference is to make decisions or judgements about the value of a parameter. A confidence interval is a good starting point, but we might also want to ask questions like</p>
<ul>
<li>Do cans of soda actually contain 12 oz?</li>
<li>Is Medicine A better than Medicine B?</li>
</ul>
<p>A <strong>hypothesis</strong> is a statement that something is true. A hypothesis test involves two (competing) hypotheses:</p>
<ol style="list-style-type: decimal">
<li>The <strong>null hypothesis</strong>, denoted <span class="math inline">\(H_0\)</span>, is the hypothesis to be tested. This is the “default” assumption.</li>
<li>The <strong>alternative hypothesis</strong>, denoted <span class="math inline">\(H_A\)</span> is the alternative to the null.</li>
</ol>
<p>Note that the subscript 0 is “nought” (pronounced “not”). A <strong>hypothesis test</strong> helps us decide whether the null hypothesis should be rejected in favor of the alternative.</p>
<blockquote>
<p><strong>Example</strong>: Cans of soda are labeled with “12 FL OZ”. Is this accurate?</p>
<p>The default, or uninteresting, assumption is that cans of soda contain 12 oz.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: the mean volume of soda in a can is 12 oz.</li>
<li><span class="math inline">\(H_A\)</span>: the mean volume of soda in a can is NOT 12 oz.</li>
</ul>
</blockquote>
<p>We can write these hypotheses in words (as above) or in statistical notation. The null specifies a single value of <span class="math inline">\(\mu\)</span></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu=\mu_0\)</span></li>
</ul>
<p>We call <span class="math inline">\(\mu_0\)</span> the <strong>null value</strong>. When we run a hypothesis test, <span class="math inline">\(\mu_0\)</span> will be replaced by some number. For the soda can example, the null value is 12. We would write <span class="math inline">\(H_0: \mu = 12\)</span>.</p>
<p>The alternative specifies a <em>range</em> of possible values for <span class="math inline">\(\mu\)</span>:</p>
<ul>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu\ne\mu_0\)</span>. “The true mean is different from the null value.”</li>
</ul>
<center>
<font size='4'><strong>The Logic of Hypothesis Testing</strong>
</center>
<p></font></p>
<p>Take a random sample from the population. If the data area consistent with the null hypothesis, do not reject the null hypothesis. If the data are inconsistent with the null hypothesis <em>and</em> supportive of the alternative hypothesis, reject the null in favor of the alternative.</p>
<blockquote>
<p><strong>Example</strong>: One way to think about the logic of hypothesis testing is by comparing it to the U.S. court system. In a jury trial, jurors are told to assume the defendant is “innocent until proven guilty”. Innocence is the default assumption, so</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: the defendant is innocent.</li>
<li><span class="math inline">\(H_A\)</span>: the defendant is guilty.</li>
</ul>
<p>Like in hypothesis testing, it is not the jury’s job to decide if the defendant is innocent. That should be their default assumption. They are only there to decide if the defendant is guilty or if there is not enough evidence to override that default assumption. The <em>burden of proof</em> lies on the alternative hypothesis.</p>
</blockquote>
<p>Notice the careful language in the logic of hypothesis testing: we either reject, or fail to reject, the null hypothesis. We never “accept” a null hypothesis.</p>
<div id="decision-errors" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Decision Errors<a href="introduction-to-hypothesis-testing.html#decision-errors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>A <strong>Type I Error</strong> is rejecting the null when it is true. (Null is true, but we conclude null is false.)</li>
<li>A <strong>Type II Error</strong> is not rejecting the null when it is false. (Null is false, but we do not conclude it is false.)</li>
</ul>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-s7xz{border-color:#ffffff;text-align:left;vertical-align:middle}
.tg .tg-vhtn{background-color:#ffffff;border-color:#000000;text-align:center;vertical-align:middle}
</style>
<table class="tg">
<thead>
<tr>
<th class="tg-s7xz">
</th>
<th class="tg-s7xz">
</th>
<th class="tg-vhtn" colspan="2">
<span class="math inline">\(H_0\)</span> is
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-s7xz">
</td>
<td class="tg-s7xz">
</td>
<td class="tg-vhtn">
True
</td>
<td class="tg-vhtn">
False
</td>
</tr>
<tr>
<td class="tg-vhtn" rowspan="2">
Decision
</td>
<td class="tg-vhtn">
Do not reject <span class="math inline">\(H_0\)</span>
</td>
<td class="tg-vhtn">
Correct decision
</td>
<td class="tg-vhtn">
Type II Error
</td>
</tr>
<tr>
<td class="tg-vhtn">
Reject <span class="math inline">\(H_0\)</span>
</td>
<td class="tg-vhtn">
Type I Error
</td>
<td class="tg-vhtn">
Correct decision
</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Example</strong>: In our jury trial,</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: the defendant is innocent.</li>
<li><span class="math inline">\(H_A\)</span>: the defendant is guilty.</li>
</ul>
<p>A Type I error is concluding guilt when the defendant is innocent. A Type II error is failing to convict when the person is guilty.</p>
</blockquote>
<p>How likely are we to make errors? Well, <span class="math inline">\(P(\)</span>Type I Error<span class="math inline">\()=\alpha\)</span>, the <strong>significance level</strong>. (Yes, this is the same <span class="math inline">\(\alpha\)</span> we saw in confidence intervals!) For Type II error, <span class="math inline">\(P(\)</span>Type II Error<span class="math inline">\()=\beta\)</span>. This is related to the sample size calculation from the previous module, but is otherwise something we don’t have time to cover.</p>
<p>We would like both <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> to be small but, like many other things in statistics, there’s a trade off! For a fixed sample size,</p>
<ul>
<li>If we decrease <span class="math inline">\(\alpha\)</span>, then <span class="math inline">\(\beta\)</span> will increase.</li>
<li>If we increase <span class="math inline">\(\alpha\)</span>, then <span class="math inline">\(\beta\)</span> will decrease.</li>
</ul>
<p>In practice, we set <span class="math inline">\(\alpha\)</span> (as we did in confidence intervals). We can improve <span class="math inline">\(\beta\)</span> by increasing sample size. Since resources are finite (we can’t get enormous sample sizes all the time), we will need to consider the consequences of each type of error.</p>
<blockquote>
<p><strong>Example</strong> We could think about assessing consequences through the jury trial example. Consider two possible charges:</p>
<ol style="list-style-type: decimal">
<li>Defendant is accused of stealing a loaf of bread. If found guilty, they may face some jail time and will have a criminal record.</li>
<li>Defendant is accused of murder. If found guilty, they will have a felony and may spend decades in prison.</li>
</ol>
<p>Since these are moral questions, I will let you consider the consequences of each type of error. However, keep in mind that we do make scientific decisions that have lasting impacts on people’s lives.</p>
</blockquote>
<center>
<font size='4'><strong>Hypothesis Test Conclusions</strong>
</center>
<p></font></p>
<ul>
<li>If the null hypothesis is rejected, we say the result is <strong>statistically significant</strong>. We can interpret this result with:
<ul>
<li>At the <span class="math inline">\(\alpha\)</span> level of significance, the data provide sufficient evidence to support the alternative hypothesis.</li>
</ul></li>
<li>If the null hypothesis is <em>not</em> rejected, we say the result is <strong>not statistically significant</strong>. We can interpret this result with:
<ul>
<li>At the <span class="math inline">\(\alpha\)</span> level of significance, the data do <em>not</em> provide sufficient evidence to support the alternative hypothesis.</li>
</ul></li>
</ul>
<p>Notice that these conclusions are framed in terms of the alternative hypothesis, which is either supported or not supported. We will <em>never</em> conclude the null hypothesis. Finally, when we write these types of conclusions, we will write them in the context of the problem.</p>
</div>
<div id="section-exercises-21" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-hypothesis-testing.html#section-exercises-21" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>For each of the following scenarios, describe what it means to make a Type I and a Type II error.
<ol style="list-style-type: lower-alpha">
<li>Researchers want to test if a new surgical procedure helps prevent recurring heart attacks. (Null hypothesis: the procedure does not prevent recurring heart attacks.)</li>
<li>Cans of soda are labeled with “12 FL OZ”. A company will test if this claim is accurate.</li>
<li>For each of the scenarios above, comment on the consequences of making each error type.</li>
</ol></li>
</ol>
</div>
</div>
<div id="confidence-interval-approach-to-hypothesis-testing" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Confidence Interval Approach to Hypothesis Testing<a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can use a confidence interval to help us weigh the evidence against the null hypothesis. A confidence interval gives us a range of <em>plausible</em> values for <span class="math inline">\(\mu\)</span>. If the null value is in the interval, then <span class="math inline">\(\mu_0\)</span> is a plausible value for <span class="math inline">\(\mu\)</span>. If the null value is <em>not</em> in the interval, then <span class="math inline">\(\mu_0\)</span> is <em>not</em> a plausible value for <span class="math inline">\(\mu\)</span>.</p>
<ol style="list-style-type: decimal">
<li>State null and alternative hypotheses.</li>
<li>Decide on significance level <span class="math inline">\(\alpha\)</span>. Check assumptions (decide which confidence interval setting to use).</li>
<li>Find the critical value.</li>
<li>Compute confidence interval.</li>
<li>If the null value is <em>not</em> in the confidence interval, reject the null hypothesis. Otherwise, do not reject.</li>
<li>Interpret results in the context of the problem.</li>
</ol>
<blockquote>
<p><strong>Example</strong>: Is the average mercury level in dolphin muslces different from <span class="math inline">\(2.5\mu g/g\)</span>? Test at the 0.05 level of significance. A random sample of <span class="math inline">\(19\)</span> dolphins resulted in a mean of <span class="math inline">\(4.4 \mu g/g\)</span> and a standard deviation of <span class="math inline">\(2.3 \mu g/g\)</span>.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu = 2.5\)</span> and <span class="math inline">\(H_A: \mu \ne 2.5\)</span>.</li>
<li>Significance level is <span class="math inline">\(\alpha=0.05\)</span>. The value of <span class="math inline">\(\sigma\)</span> is unknown and <span class="math inline">\(n = 19 &lt; 30\)</span>, so we are in setting 3.</li>
<li>For setting 3, the critical value is <span class="math inline">\(t_{df, \alpha/2}\)</span>. Here, <span class="math inline">\(df=n-1=18\)</span> and <span class="math inline">\(\alpha/2 = 0.025\)</span>:</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="introduction-to-hypothesis-testing.html#cb92-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="dv">18</span>)</span></code></pre></div>
<pre><code>## [1] -2.100922</code></pre>
<blockquote>
<ol start="4" style="list-style-type: decimal">
<li>The confidence interval is <span class="math display">\[\begin{align} \bar{x} &amp;\pm t_{df, \alpha/2}\frac{s}{\sqrt{n}} \\ 4.4 &amp;\pm 2.101 \frac{2.3}{\sqrt{19}} \\ 4.4 &amp;\pm 1.109 \end{align}\]</span> or <span class="math inline">\((3.29, 5.51)\)</span>.</li>
<li>Since the null value, <span class="math inline">\(2.5\)</span>, is not in the interval, it is <em>not</em> a plausible value for <span class="math inline">\(\mu\)</span> (at the 95% level of confidence). Therefore we reject the null hypothesis.</li>
<li>At the 0.05 level of significance, the data provide sufficient evidence to conclude that the true mean mercury level in dolphin muscles is <em>greater than</em> <span class="math inline">\(2.5\mu g/g\)</span>.</li>
</ol>
<p>Note: The alternative hypothesis is “not equal to”, but we conclude “greater than” because all of the plausible values in the confidence interval are greater than the null value.</p>
</blockquote>
<div id="section-exercises-22" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-hypothesis-testing.html#section-exercises-22" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The weights of 6 randomly selected NFL linebackers were <span class="math inline">\(243, 238, 229, 253, 248, 225\)</span>. Suppose we want to test if the mean weight of NFL linebackers differs from 230 pounds. We will test at the 0.05 level of significance. (Note that <span class="math inline">\(\bar{x} = 239.3\)</span> and <span class="math inline">\(s = 10.9\)</span>.)
<ol style="list-style-type: lower-alpha">
<li>Write out the null and alternative hypotheses.</li>
<li>Using the confidence interval approach, what decision should you make about rejecting or not rejecting the null hypotheses?</li>
<li>Interpret your results in the context of the problem.</li>
</ol></li>
<li>Researchers took a random sample of 20 green sea turtle nests and counted the number of eggs in each. They found a mean of 107.3 eggs with standard deviation 13.7. Use the confidence interval approach to test at the 0.1 level of confidence if the true mean number of eggs is 110.</li>
<li>Some Sac State students claim the average commute to campus is 45 minutes. A random sample of 32 students resulted in a mean of 31 minutes with standard deviation 18 minutes. Use the confidence interval approach to test their claim at the 0.05 level of confidence.</li>
<li>A city council member suspects that people speed through a certain intersection. They want to know the average speed at which drivers enter the intersection. They set up a speed camera and randomly sample 250 vehicles at different times of day, which results in a mean speed of 52 mph with standard deviation 8 mph. Suppose the posted speed limit is 45mph. Use the confidence interval approach at the 0.05 level of confidence to test the claim that drivers do not follow the speed limit.</li>
</ol>
</div>
</div>
<div id="critical-value-approach-to-hypothesis-testing" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Critical Value Approach to Hypothesis Testing<a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We learned about critical values when we discussed confidence intervals. Now, we want to use these values directly in a hypothesis test. We will compare these values to a value based on the data, called a <strong>test statistic</strong>.</p>
<p>Idea: the null is our “default assumption”. If the null is true, how likely are we to observe a sample that looks like the one we have? If our sample is very inconsistent with the null hypothesis, we want to reject the null hypothesis.</p>
<div id="test-statistics" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Test statistics<a href="introduction-to-hypothesis-testing.html#test-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Test statistics are similar to z- and t-scores: <span class="math display">\[\text{test statistic} = \frac{\text{point estimate}-\text{null value}}{\text{standard error}}.\]</span> In fact, they serve a similar function in converting a variable <span class="math inline">\(\bar{X}\)</span> into a distribution we can work with easily.</p>
<ul>
<li><strong>Large Sample Setting</strong>: <span class="math inline">\(\mu\)</span> is target parameter, <span class="math inline">\(n \ge 30\)</span></li>
</ul>
<p><span class="math display">\[z = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}\]</span></p>
<ul>
<li><strong>Small Sample Setting</strong>: <span class="math inline">\(\mu\)</span> is target parameter, <span class="math inline">\(n &lt; 30\)</span></li>
</ul>
<p><span class="math display">\[t = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}\]</span></p>
<p>The set of values for the test statistic that cause us to reject <span class="math inline">\(H_0\)</span> is the <strong>rejection region</strong>. The remaining values are the <strong>nonrejection region</strong>. The value that separates these is the critical value!</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-108-1.png" alt="" width="672" /></p>
<p>Steps:</p>
<ol style="list-style-type: decimal">
<li>State the null and alternative hypotheses.</li>
<li>Determine the significance level <span class="math inline">\(\alpha\)</span>. Check assumptions (decide which setting to use).</li>
<li>Compute the value of the test statistic.</li>
<li>Determine the critical values.</li>
<li>If the test statistic is in the rejection region, reject the null hypothesis. Otherwise, do not reject.</li>
<li>Interpret results.</li>
</ol>
<blockquote>
<p><strong>Example</strong>: Researchers took a random sample of 20 green sea turtle nests and counted the number of eggs in each. They found a mean of 107.3 eggs with standard deviation 13.7. Using the critical value approach at the 0.1 level of significance, test if the mean number of eggs in green sea turtle clutches is 110.</p>
<p><em>Solution</em>: From the problem statement, <span class="math inline">\(n=20\)</span>, <span class="math inline">\(\bar{x}=107.3\)</span>, and <span class="math inline">\(s=13.7\)</span>.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu = 110\)</span> and <span class="math inline">\(H_A: \mu \ne 110\)</span>.</li>
<li>Significance level is <span class="math inline">\(\alpha=0.1\)</span>. The value of <span class="math inline">\(\sigma\)</span> is unknown and <span class="math inline">\(n = 20 &lt; 30\)</span>, so we are in setting 3.</li>
<li>The test statistic is <span class="math display">\[\begin{align} t &amp;= \frac{\bar{x}-\mu_0}{s/\sqrt{n}} \\ &amp;= \frac{107.3-110}{13.7/\sqrt{20}} \\ &amp;= -0.881 \end{align}\]</span></li>
<li>The critical value is <span class="math inline">\(t_{df, \alpha/2}\)</span>. Here, <span class="math inline">\(df=n-1=19\)</span> and <span class="math inline">\(\alpha/2 = 0.05\)</span>:</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introduction-to-hypothesis-testing.html#cb94-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.05</span>, <span class="dv">19</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.729133</code></pre>
<blockquote>
<p>So the critical value is <span class="math inline">\(t_{19, 0.05}=1.729\)</span>.
5. The test statistic is <em>not</em> in the rejection region, so we will fail to reject the null hypothesis:</p>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-110-1.png" alt="" width="672" /></p>
<blockquote>
<ol start="6" style="list-style-type: decimal">
<li>At the 0.05 level of significance, the data provide insufficient evidence to conclude that the true mean number of eggs in a green sea turtle next differs from <span class="math inline">\(110\)</span>.</li>
</ol>
</blockquote>
</div>
<div id="section-exercises-23" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-hypothesis-testing.html#section-exercises-23" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The weights of 6 randomly selected NFL linebackers were <span class="math inline">\(243, 238, 229, 253, 248, 225\)</span>. Suppose we want to test if the mean weight of NFL linebackers differs from 230 pounds. We will test at the 0.05 level of significance. (Note that <span class="math inline">\(\bar{x} = 239.3\)</span> and <span class="math inline">\(s = 10.9\)</span>.)
<ol style="list-style-type: lower-alpha">
<li>Write out the null and alternative hypotheses.</li>
<li>Find the test statistic.</li>
<li>Using the critical value approach, what decision should you make about rejecting or not rejecting the null hypotheses?</li>
<li>Interpret your results in the context of the problem.</li>
</ol></li>
<li>Researchers took a random sample of 20 green sea turtle nests and counted the number of eggs in each. They found a mean of 107.3 eggs with standard deviation 13.7. Use the critical value approach to test at the 0.1 level of confidence if the true mean number of eggs is 110.</li>
<li>Some Sac State students claim the average commute to campus is 45 minutes. A random sample of 32 students resulted in a mean of 31 minutes with standard deviation 18 minutes. Use the critical value approach to test their claim at the 0.05 level of confidence.</li>
<li>A city council member suspects that people speed through a certain intersection. They want to know the average speed at which drivers enter the intersection. They set up a speed camera and randomly sample 250 vehicles at different times of day, which results in a mean speed of 52 mph with standard deviation 8 mph. Suppose the posted speed limit is 45mph. Use the critical value approach at the 0.05 level of confidence to test the claim that drivers do not follow the speed limit.</li>
</ol>
</div>
</div>
<div id="p-value-approach-to-hypothesis-testing" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> P-Value Approach to Hypothesis Testing<a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If the null hypothesis is true, what is the probability of getting a random sample that is as inconsistent with the null hypothesis as the random sample we got? This probability is called the <strong>p-value</strong>.</p>
<blockquote>
<p><strong>Example</strong>: Is the average mercury level in dolphin muscles different from <span class="math inline">\(2.5\mu g/g\)</span>? Test at the 0.05 level of significance. A random sample of <span class="math inline">\(19\)</span> dolphins resulted in a mean of <span class="math inline">\(4.4 \mu g/g\)</span> and a standard deviation of <span class="math inline">\(2.3 \mu g/g\)</span>.</p>
<p>Probability of a sample <em>as inconsistent</em> as our sample is <span class="math inline">\(P(t_{df} \text{ is as extreme as the test statistic})\)</span>. Consider <span class="math display">\[P(t_{18} &gt; 3.6) = 0.001\]</span> but we want to think about the probability of being “as extreme” in <em>either direction</em> (either tail), so <span class="math display">\[\text{p-value} = 2P(t_{18}&gt;3.6) = 0.002\]</span></p>
</blockquote>
<p>If <span class="math inline">\(\text{p-value} &lt; \alpha\)</span>, reject the null hypothesis. Otherwise, do not reject.</p>
<div id="p-values" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> P-Values<a href="introduction-to-hypothesis-testing.html#p-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Large Sample Setting</strong>: <span class="math inline">\(\mu\)</span> is target parameter, <span class="math inline">\(n \ge 30\)</span>, <span class="math display">\[2P(Z &gt; |z|)\]</span> where <span class="math inline">\(z\)</span> is the test statistic.</p></li>
<li><p><strong>Small Sample Setting</strong>: <span class="math inline">\(\mu\)</span> is target parameter, <span class="math inline">\(n &lt; 30\)</span>, <span class="math display">\[2P(t_{df} &gt; |t|)\]</span> where <span class="math inline">\(t\)</span> is the test statistic.</p></li>
</ul>
<p>Note: <span class="math inline">\(|a|\)</span> is the “absolute value” of <span class="math inline">\(a\)</span>. The absolute value takes a number and throws away the sign, so <span class="math inline">\(|2|=2\)</span> and <span class="math inline">\(|-3|=3\)</span>.</p>
<p>Steps:</p>
<ol style="list-style-type: decimal">
<li>State the null and alternative hypotheses.</li>
<li>Determine the significance level <span class="math inline">\(\alpha\)</span>. Check assumptions (decide which setting to use).</li>
<li>Compute the value of the test statistic.</li>
<li>Determine the p-value.</li>
<li>If <span class="math inline">\(\text{p-value} &lt; \alpha\)</span>, reject the null hypothesis. Otherwise, do not reject.</li>
<li>Interpret results.</li>
</ol>
<p>We often use p-values instead of the critical value approach because they are meaningful on their own (they have a direct interpretation).</p>
<blockquote>
<p><strong>Example</strong>: Is the average meerkat height different from 25cm? A random sample of 31 meerkats yielded a mean of 26.5cm and a standard deviation of 4.07cm. Use the p-value approach to test at the 0.05 level of significance.</p>
<p><em>Solution</em>: From the problem statement, <span class="math inline">\(n=31\)</span>, <span class="math inline">\(\bar{x}=26.5\)</span> and <span class="math inline">\(s=4.07\)</span>. Then,</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \mu = 25\)</span> and <span class="math inline">\(H_A: \mu \ne 25\)</span>.</li>
<li>Significance level is <span class="math inline">\(\alpha=0.05\)</span>. The value of <span class="math inline">\(\sigma\)</span> is unknown and <span class="math inline">\(n = 31 \ge 30\)</span>, so we are in setting 2 (standard normal).</li>
<li>The test statistic is <span class="math display">\[\begin{align} z &amp;= \frac{\bar{x}-\mu_0}{s/\sqrt{n}} \\ &amp;= \frac{26.5-25}{4.07/\sqrt{31}} \\ &amp;= 2.052 \end{align}\]</span></li>
<li>The p-value is <span class="math display">\[2P(z &gt; |z|) - 2P(z &gt; 2.052) = 0.040\]</span></li>
<li>Since <span class="math inline">\(\text{p-value}=0.04 &lt; \alpha=0.05\)</span>, reject the null hypothesis.</li>
<li>At the 0.05 level of significance, the data provide sufficient evidence to conclude that the true mean height of meerkats is greater than 25cm.</li>
</ol>
</blockquote>
<p>As before, this is the same conclusion we came to when we used the confidence interval and critical value approaches. All of these approaches are exactly equivalent.</p>
</div>
<div id="section-exercises-24" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="introduction-to-hypothesis-testing.html#section-exercises-24" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The weights of 6 randomly selected NFL linebackers were <span class="math inline">\(243, 238, 229, 253, 248, 225\)</span>. Suppose we want to test if the mean weight of NFL linebackers differs from 230 pounds. We will test at the 0.05 level of significance. (Note that <span class="math inline">\(\bar{x} = 239.3\)</span> and <span class="math inline">\(s = 10.9\)</span>.)
<ol style="list-style-type: lower-alpha">
<li>Write out the null and alternative hypotheses.</li>
<li>Find and interpret the p-value.</li>
<li>Using the p-value approach, what decision should you make about rejecting or not rejecting the null hypotheses?</li>
<li>Interpret your results in the context of the problem.</li>
</ol></li>
<li>Researchers took a random sample of 20 green sea turtle nests and counted the number of eggs in each. They found a mean of 107.3 eggs with standard deviation 13.7. Use the p-value approach to test at the 0.1 level of confidence if the true mean number of eggs is 110.</li>
<li>Some Sac State students claim the average commute to campus is 45 minutes. A random sample of 32 students resulted in a mean of 31 minutes with standard deviation 18 minutes. Use the p-value approach to test their claim at the 0.05 level of confidence.</li>
<li>A city council member suspects that people speed through a certain intersection. They want to know the average speed at which drivers enter the intersection. They set up a speed camera and randomly sample 250 vehicles at different times of day, which results in a mean speed of 52 mph with standard deviation 8 mph. Suppose the posted speed limit is 45mph. Use the p-value approach at the 0.05 level of confidence to test the claim that drivers do not follow the speed limit.</li>
</ol>
</div>
</div>
<div id="r-lab-hypothesis-tests-for-a-mean" class="section level2 unnumbered hasAnchor">
<h2>R Lab: Hypothesis Tests for a Mean<a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To conduct hypothesis tests for a mean in R, we will use the <code>t.test</code> command. The arguments we will use for hypothesis testing are</p>
<ul>
<li><code>x</code>: the variable that contains the data we want to use to construct a confidence interval.</li>
<li><code>mu</code>: the null value, <span class="math inline">\(\mu_0\)</span>.</li>
<li><code>conf.level</code>: the desired confidence level (<span class="math inline">\(1-\alpha\)</span>).</li>
</ul>
<p>We will again to use the <code>Loblolly</code> pine tree data.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="introduction-to-hypothesis-testing.html#cb96-1" tabindex="-1"></a><span class="fu">attach</span>(Loblolly)</span></code></pre></div>
<p>Let’s test if the average height of Loblolly pines differs from <span class="math inline">\(40\)</span> feet. We will test at a 0.01 level of significance (<span class="math inline">\(\alpha = 0.01\)</span>). So <span class="math inline">\(H_0: \mu = 40\)</span> and <span class="math inline">\(H_A: \mu \ne 40\)</span> and the R command will look like</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="introduction-to-hypothesis-testing.html#cb97-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> height, <span class="at">mu =</span> <span class="dv">40</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  height
## t = -3.3851, df = 83, p-value = 0.001089
## alternative hypothesis: true mean is not equal to 40
## 99 percent confidence interval:
##  26.41761 38.31120
## sample estimates:
## mean of x 
##   32.3644</code></pre>
<p>The output from this test shows the following (top to bottom):</p>
<ul>
<li>the variable used in the hypothesis test.</li>
<li>the value of the test statistic (<span class="math inline">\(t = -3.3851\)</span>), the degrees of freedom (<span class="math inline">\(83\)</span>), and the p-value (<span class="math inline">\(0.001\)</span>).</li>
<li>the alternative hypothesis (<span class="math inline">\(H_0: \mu\ne 40\)</span>).</li>
<li>the confidence interval (<span class="math inline">\(29.42, 38.31\)</span>).</li>
<li>the sample mean (<span class="math inline">\(\bar{x} = 32.36\)</span>).</li>
</ul>
<p>Based on this output, we have everything we need to conduct a hypothesis test using (A) the confidence interval approach, (B) the critical value approach, or (C) the p-value approach! In practice, we might include results from multiple approaches: At the 0.01 level of significance, there is sufficient evidence to reject the null hypothesis and conclude that the true mean height of Loblolly pines is less than 40 feet (<span class="math inline">\(t = -3.385\)</span>, p-value<span class="math inline">\(=0.001\)</span>).</p>
<p><strong>Comment</strong>: Notice are we using <code>t.test</code> and not a test using the normal distribution? Remember that when <span class="math inline">\(n \ge 30\)</span>, the t and standard normal distributions are basically the same! Therefore, when using a computer, we often use the t-distribution regardless of sample size.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="introduction-to-hypothesis-testing.html#cb99-1" tabindex="-1"></a><span class="fu">detach</span>(Loblolly)</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-confidence-intervals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inference-for-a-proportion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
