<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 3 Regression and Correlation | Introduction to Statistics</title>
  <meta name="description" content="Module 3 Regression and Correlation | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 3 Regression and Correlation | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 3 Regression and Correlation | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 3 Regression and Correlation | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 3 Regression and Correlation | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descriptive-measures.html"/>
<link rel="next" href="probability-concepts.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-and-correlation" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Module 3</span> Regression and Correlation<a href="regression-and-correlation.html#regression-and-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this module, we will extend our conversation on descriptive measures
for quantitative variables to include the relationship between two
variables.</p>
<p><strong>Module Learning Outcomes/Objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Interpret a correlation coefficient.</li>
<li>Calculate and interpret a regression line.</li>
<li>Interpret a coefficient of determination.</li>
<li>Understand the relationship between a correlation coefficient and a
coefficient of determination.</li>
<li>Use a regression line to make predictions.</li>
</ol>
<div id="linear-equations" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Linear Equations<a href="regression-and-correlation.html#linear-equations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>From your previous math classes, you should have a passing familiarity
with linear equations like <span class="math inline">\(y=mx+b\)</span>. In statistics, we write these as
<span class="math display">\[y=b_0 + b_1x\]</span> where <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are constants, <span class="math inline">\(x\)</span> is the
independent variable, and <span class="math inline">\(y\)</span> is the dependent variable. The graph of a
linear function is always a (straight) line.</p>
<p>The <strong>y-intercept</strong> is <span class="math inline">\(b_0\)</span>, the value the dependent variable takes
when the independent variable <span class="math inline">\(x=0\)</span>. The <strong>slope</strong> is <span class="math inline">\(b_1\)</span>, the change
in <span class="math inline">\(y\)</span> for a one-unit increase in <span class="math inline">\(x\)</span>.</p>
<div id="scatter-plots" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Scatter Plots<a href="regression-and-correlation.html#scatter-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>scatter plot</strong> shows the relationship between two (numeric)
variables.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>This is just a bunch of points of the form <span class="math inline">\((x,y)\)</span> plotted in the
<span class="math inline">\(xy\)</span>-plane, where instead of showing the full x- and y-axes, we crop the
plot to show only the part where we have data.</p>
<p>At a glance, we can see that (in general) heavier cars have lower MPG.
We call this type of data <strong>bivariate data</strong> (“bi” as in “two” and
“variate” as in “variable”).</p>
<p>Now consider a person who spends $15 each month buying a bag of coffee
for their home coffee machine. Each coffee they purchase costs $4.25.
If we know the numbers of coffees they bought last month, we know
<em>exactly</em> how much money they spent!</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>This relationship can be modeled perfectly with a straight line:
<span class="math inline">\(y = 15 + 4.25x\)</span>. The y-intercept tells us that, in a month when this person buys zero coffees (<span class="math inline">\(x=0\)</span>), they spend <span class="math inline">\(\$15\)</span>. The slope tells us that, for each additional coffee purchased, the amount of money spent in that month goes up by <span class="math inline">\(\$4.25\)</span></p>
<p>When we can do this – model a relationship perfectly
– we know the exact value of <span class="math inline">\(y\)</span> whenever we know the value of <span class="math inline">\(x\)</span>.
This is nice (we would love to be able to do this all the time!) but
typically real-world data is much more complex than this.</p>
</div>
<div id="linear-regression" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Linear Regression<a href="regression-and-correlation.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Linear regression takes the idea of fitting a line to points and allows
the relationship to be imperfect. What if that bag of coffee didn’t
always cost $15? Or the coffee drinks didn’t always cost $4.25? In
this case, you might get a plot that looks something like this:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>Without doing any math, you can think about where you might draw a line
through these points. Later on, we will formalize how to do that
mathematically.</p>
<p>Bear with me for a bit while we go over some mathematical notation. The
notation for the linear regression line is
<span class="math display">\[y = \beta_0 + \beta_1x + \epsilon\]</span></p>
<ul>
<li><span class="math inline">\(\beta\)</span> is the Greek letter “beta”.</li>
<li><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, the slope and intercept, are constants.</li>
<li><span class="math inline">\(\epsilon\)</span> is the Greek letter “epsilon”.</li>
<li><span class="math inline">\(\epsilon\)</span> represents the <em>error</em>, the fact that the points don’t
all line up perfectly.</li>
</ul>
<p>If you think back to Section 2.3 (Descriptive Measures for Populations),
this is the true, unknown (population) version of the line. We estimate
<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> using data and denote the estimated line by
<span class="math display">\[\hat{y} = b_0 + b_1x \]</span></p>
<ul>
<li><span class="math inline">\(\hat{y}\)</span>, “y-hat”, is the estimated value of <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(b_0\)</span> is the estimate for <span class="math inline">\(\beta_0\)</span>.</li>
<li><span class="math inline">\(b_1\)</span> is the estimate for <span class="math inline">\(\beta_1\)</span>.</li>
</ul>
<p>That is, <span class="math inline">\(b_0\)</span> is the point estimate for the population parameter
<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(b_1\)</span> is the point estimate for the population parameter
<span class="math inline">\(\beta_1\)</span>.</p>
<p>We drop the error term <span class="math inline">\(\epsilon\)</span> when we estimate the constants for a
regression line; we assume that the mean error is 0, so <em>on average</em> we
can ignore this error.</p>
<p>We use a regression line to make predictions about <span class="math inline">\(y\)</span> using values of
<span class="math inline">\(x\)</span>.</p>
<ul>
<li><span class="math inline">\(x\)</span> is the <strong>predictor variable</strong>
<ul>
<li>We use <span class="math inline">\(x\)</span> to <em>predict</em> <span class="math inline">\(y\)</span>.</li>
</ul></li>
<li><span class="math inline">\(y\)</span> is the <strong>response variable</strong>
<ul>
<li>The value of <span class="math inline">\(y\)</span> <em>responds</em> to whatever we plug in for <span class="math inline">\(x\)</span>.</li>
</ul></li>
</ul>
<blockquote>
<p><strong>Example</strong>: Researchers took a variety of measurements on 344 adult
penguins (species chinstrap, gentoo, and adelie) near Palmer Station
in Antarctica.</p>
<div class="float">
<img src="penguins.png" alt="Artwork by @allison_horst" />
<div class="figcaption">Artwork by @allison_horst</div>
</div>
<p>We will consider two measurements for each penguin: their body mass
(weight in grams) and flipper length (in millimeters).</p>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<blockquote>
<p>Clearly, the relationship isn’t perfectly linear, but there does
appear to be some kind of linear relationship (as flipper length
increases, body mass also increases). We want to try to use flipper
length (<span class="math inline">\(x\)</span>) to predict body mass (<span class="math inline">\(y\)</span>).</p>
<p>The regression model for these data is <span class="math display">\[\hat{y}=-5780.83 + 49.69x\]</span></p>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<blockquote>
<p>We can interpret the slope and intercept by using the definitions
given previously and tweaking them to match the context of the data:</p>
<ul>
<li>Slope: For a one-mm increase in flipper length, body mass is
predicted to increase by 49.69g.</li>
<li>Intercept: When flipper length is equal to 0mm, body mass is
predicted to be -5780.83g.</li>
</ul>
<p>What happened with our intercept? Sometimes interpretations of
intercepts do not make sense and that’s ok! It doesn’t make sense to
have a flipper length of 0, so we shouldn’t be concerned that plugging
in 0 gives us a nonsense value for body length. That intercept value
is still important in the regression line because it helps situate the
regression line in the xy plane.</p>
<p>To predict the body mass for a penguin with a flipper length of 180cm,
we just need to plug in 180 for flipper length (<span class="math inline">\(x\)</span>):
<span class="math display">\[\hat{y}=-5780.83 + 49.69\times 180 = 3163.37\text{g}.\]</span> Note:
because the regression line is built using the data’s original units
(mm for flipper length, g for body mass), the regression line will
preserve those units. That means that when we plugged in a value in
mm, the equation spit out a predicted value in g.</p>
</blockquote>
</div>
<div id="section-exercises-6" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="regression-and-correlation.html#section-exercises-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
For exercises 1-5, determine which variable should be the predictor (<span class="math inline">\(x\)</span>) and which should be the response (<span class="math inline">\(y\)</span>).
<ol>
<li>
We want to use annual days of sunshine to predict depression rates in US cities.
</li>
<li>
We want to know if we can use annual paid vacation days to predict employee satisfation.
</li>
<li>
A researcher will use mouse hormone levels to predict changes in weight.
</li>
<li>
A company wants to know if they can determine revenue based on amount of money spent on ads.
</li>
<li>
I want to know if the amount my dog barks is predictive of how quickly solicitors leave the front door.
</li>
</ol>
<ol start="6">
<li>
Suppose we have a regression line to predict miles per gallon (<span class="math inline">\(y\)</span>)
using car weight in pounds (<span class="math inline">\(x\)</span>): <span class="math display">\[\hat{y} = 37.285 - 0.005x\]</span>
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Interpret the intercept in the context of the problem.
</li>
<li>
Interpret the slope in the context of the problem.
</li>
<li>
Predict the miles per gallon for a car that weighs 3,500
lbs.
</li>
</ol>
<li>
Suppose we have a regression line to predict penguin bill length (in
millimeters) using bill depth (in millimeters). The regression line
is <span class="math inline">\(y = 55.07 - 0.650x\)</span>.
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Which variable is <span class="math inline">\(x\)</span> and which is <span class="math inline">\(y\)</span>?.
</li>
<li>
Interpret the intercept in the context of the problem.
</li>
<li>
Interpret the slope in the context of the problem.
</li>
<li>
Predict the bill length for a penguin with a bill depth of 17.3
mm.
</li>
</ol>
</ol>
</div>
</div>
<div id="correlation" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Correlation<a href="regression-and-correlation.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ve talked about the strength of linear relationships, but it would be
nice to formalize this concept. The <strong>correlation</strong> between two
variables describes the strength of their linear relationship. It always
takes values between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>. We denote the correlation (or
correlation coefficient) by <span class="math inline">\(R\)</span>:
<span class="math display">\[R = \frac{1}{n-1}\sum_{i=1}^n\left(\frac{x_i - \bar{x}}{s_x}\times\frac{y_i - \bar{y}}{s_y}\right)\]</span>
where <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> are the respective standard deviations for <span class="math inline">\(x\)</span> and
<span class="math inline">\(y\)</span>. The sample size <span class="math inline">\(n\)</span> is the total number of <span class="math inline">\((x,y)\)</span> pairs.</p>
<blockquote>
<p><strong>Example</strong>: Suppose <span class="math inline">\(x: 2, 4, 3, 5, 2\)</span> and <span class="math inline">\(y: 1,8,6,10,4\)</span>. Find the correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p><strong>Solution</strong>: First, <span class="math inline">\(n=5\)</span> and we should calculate the means and standard deviations for <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. Using a computer, the means are <span class="math inline">\(\bar{x} = 3.2\)</span> and <span class="math inline">\(\bar{y} = 5.8\)</span> and the standard deviations are <span class="math inline">\(s_x=1.30\)</span> and <span class="math inline">\(s_y=3.49\)</span>.</p>
<p>Like we did for variance, we’ll use a table to help organize our math.</p>
<table style="width:100%;">
<colgroup>
<col width="25%" />
<col width="16%" />
<col width="25%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="left"><span class="math inline">\(\frac{x-\bar{x}}{s_x}\)</span></th>
<th align="center"><span class="math inline">\(y\)</span></th>
<th align="left"><span class="math inline">\(\frac{y-\bar{y}}{s_y}\)</span></th>
<th align="right"><span class="math inline">\(\frac{x - \bar{x}}{s_x}\times\frac{y - \bar{y}}{s_y}\)</span></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">2</td>
<td align="left"><span class="math inline">\(\frac{2-3.2}{1.30} = -0.92\)</span></td>
<td align="center">1</td>
<td align="left"><span class="math inline">\(\frac{1-5.8}{3.49} = -1.37\)</span></td>
<td align="right"><span class="math inline">\((-0.92)(-1.37) = 1.26\)</span></td>
</tr>
<tr>
<td align="center">4</td>
<td align="left"><span class="math inline">\(\frac{4-3.2}{1.30} = 0.61\)</span></td>
<td align="center">8</td>
<td align="left"><span class="math inline">\(\frac{8-5.8}{3.49} = 0.63\)</span></td>
<td align="right"><span class="math inline">\((0.61)(0.63) = 0.39\)</span></td>
</tr>
<tr>
<td align="center">3</td>
<td align="left"><span class="math inline">\(\frac{3-3.2}{1.30} =-0.15\)</span></td>
<td align="center">6</td>
<td align="left"><span class="math inline">\(\frac{6-5.8}{3.49} = 0.06\)</span></td>
<td align="right"><span class="math inline">\((-0.15)(0.06) = -0.01\)</span></td>
</tr>
<tr>
<td align="center">5</td>
<td align="left"><span class="math inline">\(\frac{5-3.2}{1.30} = 1.38\)</span></td>
<td align="center">10</td>
<td align="left"><span class="math inline">\(\frac{10-5.8}{3.49} = 1.20\)</span></td>
<td align="right"><span class="math inline">\((1.38)(1.20) = 1.66\)</span></td>
</tr>
<tr>
<td align="center">2</td>
<td align="left"><span class="math inline">\(\frac{2-3.2}{1.30} =-0.92\)</span></td>
<td align="center">4</td>
<td align="left"><span class="math inline">\(\frac{4-5.8}{3.49} = -0.52\)</span></td>
<td align="right"><span class="math inline">\((-0.92)(-0.52) = 0.47\)</span></td>
</tr>
<tr>
<td align="center"></td>
<td align="left"></td>
<td align="center"></td>
<td align="left"></td>
<td align="right"><span class="math inline">\(\sum_{i=1}^n\left(\frac{x_i - \bar{x}}{s_x}\times\frac{y_i - \bar{y}}{s_y}\right) = 3.78\)</span></td>
</tr>
</tbody>
</table>
<p>Then <span class="math inline">\(R = \frac{3.78}{5-1} = 0.94\)</span>.</p>
</blockquote>
<p>This is a pretty involved formula! In general, we’ll let a computer handle this one.</p>
<p>Correlations</p>
<ul>
<li>close to <span class="math inline">\(-1\)</span> suggest strong, negative linear relationships.</li>
<li>close to <span class="math inline">\(+1\)</span> suggest strong, positive linear relationships.</li>
<li>close to <span class="math inline">\(0\)</span> have little-to-no linear relationship.</li>
</ul>
<p>Note: the sign of the correlation will match the sign of the slope!</p>
<ul>
<li>If <span class="math inline">\(R &lt; 0\)</span>, there is a downward trend and <span class="math inline">\(b_1 &lt; 0\)</span>.</li>
<li>If <span class="math inline">\(R &gt; 0\)</span>, there is an upward trend and <span class="math inline">\(b_1 &gt; 0\)</span>.</li>
<li>If <span class="math inline">\(R \approx 0\)</span>, there is no relationship and <span class="math inline">\(b_1 \approx 0\)</span>.</li>
</ul>
<p>When two variables are highly correlated (<span class="math inline">\(R\)</span> close to <span class="math inline">\(-1\)</span> or <span class="math inline">\(1\)</span>), we
know there is a strong linear <em>relationship</em> between them, but we do not know
what <em>causes</em> that relationship. For example, when we looked at the
Palmer penguins, we noticed that an increase in flipper length related
to an increase in body weight… but we have no way of knowing if
flipper length <em>causes</em> a higher body weight (or vice versa). That is,
<em>correlation does not imply causation</em>.</p>
<blockquote>
<p>Example Correlations:
<img src="IntroStats_files/figure-html/unnamed-chunk-56-1.png" width="672" /><img src="IntroStats_files/figure-html/unnamed-chunk-56-2.png" width="672" /><img src="IntroStats_files/figure-html/unnamed-chunk-56-3.png" width="672" /></p>
</blockquote>
<p>A final note: correlations only represent <em>linear</em> relationships. Consider the
following scatter plot:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>Obviously there’s a strong relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. In fact,
there’s a perfect relationship here: <span class="math inline">\(y = x^2\)</span>. But the <em>correlation</em>
between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is 0! This is one reason why it’s important to
examine the data both through visual and numeric measures.</p>
<div id="section-exercises-7" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="regression-and-correlation.html#section-exercises-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The <code>penguins</code> data set (from the <code>palmerpenguins</code> package in R) has
data on various penguin body measurements. We want to consider the
relationship between a penguin’s <code>body mass</code> from its
<code>flipper length</code>. The scatter plot below shows the relationship
between these two variables.</li>
</ol>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<ol>
<ol style="list-style-type: lower-alpha;">
<li>
Based only on the scatter plot, what can you say about the
correlation <span class="math inline">\(R\)</span>? Explain.
</li>
<li>
The actual correlation between these two variables is <span class="math inline">\(R=0.871\)</span>.
What does this tell you about the relationship between penguin body mass
and flipper length?
</li>
</ol>
</ol>
</div>
</div>
<div id="finding-a-regression-line" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Finding a Regression Line<a href="regression-and-correlation.html#finding-a-regression-line" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Residuals</strong> are the leftover <em>stuff</em> (variation) in the data after
accounting for model fit:
<span class="math display">\[\text{data} = \text{prediction} + \text{residual}\]</span> Each observation
has its own residual. The residual for an observation <span class="math inline">\((x,y)\)</span> is the
difference between observed (<span class="math inline">\(y\)</span>) and predicted (<span class="math inline">\(\hat{y}\)</span>):
<span class="math display">\[e = y - \hat{y}\]</span> We denote the residuals by <span class="math inline">\(e\)</span> and find <span class="math inline">\(\hat{y}\)</span> by
plugging <span class="math inline">\(x\)</span> into the regression equation. If an observation lands above
the regression line, <span class="math inline">\(e &gt; 0\)</span>. If below, <span class="math inline">\(e &lt; 0\)</span>.</p>
<p>When we estimate the parameters for the regression, our goal is to get
each residual as close to 0 as possible. We might think to try
minimizing <span class="math display">\[\sum_{i=1}^n e_i = \sum_{i=1}^n (y_i - \hat{y}_i)\]</span> but
that would just give us very large negative residuals. (Remember that
this symbol <span class="math inline">\(\sum\)</span> just means I’m adding up all the values of whatever
is next to it, so <span class="math inline">\(\sum_{i=1}^n e_i\)</span> means we add all of the the
residuals.)</p>
<p>As with the variance, we will use squares to shift the focus to
magnitude: <span class="math display">\[\begin{align}
\sum_{i=1}^n e_i^2 &amp;= \sum_{i=1}^n (y_i - \hat{y}_i)^2 \\
&amp; = \sum_{i=1}^n [y_i - (b_0 + b_1 x_i)]^2
\end{align}\]</span> This will allow us to shrink the residuals toward 0: the
values <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> that minimize this will make up our regression
line. This is a calculus-free course, though, so we’ll skip the proof of
the minimization part.</p>
<p>The slope can be estimated as <span class="math display">\[b_1 = \frac{s_y}{s_x}\times R\]</span> and the
intercept as <span class="math display">\[b_0 = \bar{y} - b_1 \bar{x}\]</span></p>
<blockquote>
<p><strong>Example</strong>: Consider two measurements taken on the Old Faithful
Geyser in Yellowstone National Park: <code>eruptions</code>, the length of each
eruption and <code>waiting</code>, the time between eruptions. Each is measured
in minutes.</p>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<blockquote>
<p>There does appear to be some kind of linear relationship here, so we
will see if we can use the wait time to predict the eruption duration.
The sample statistics for these data are</p>
<table>
<thead>
<tr>
<th align="center"></th>
<th align="center"><code>waiting</code></th>
<th align="center"><code>eruptions</code></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">mean</td>
<td align="center"><span class="math inline">\(\bar{x}=70.90\)</span></td>
<td align="center"><span class="math inline">\(\bar{y}=3.49\)</span></td>
</tr>
<tr>
<td align="center">sd</td>
<td align="center"><span class="math inline">\(s_x=13.60\)</span></td>
<td align="center"><span class="math inline">\(s_y=1.14\)</span></td>
</tr>
<tr>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(R = 0.90\)</span></td>
</tr>
</tbody>
</table>
<p>Since we want to use wait time to predict eruption duration, wait time
is <span class="math inline">\(x\)</span> and eruption duration is <span class="math inline">\(y.\)</span> Then
<span class="math display">\[b_1 = \frac{1.14}{13.60}\times 0.90 \approx 0.076 \]</span> and
<span class="math display">\[b_0 = 3.49 - 0.076\times 70.90 \approx -1.87\]</span> so the estimated
regression line is <span class="math display">\[\hat{y} = -1.87 + 0.076x\]</span></p>
<p>To interpret <span class="math inline">\(b_1\)</span>, the slope, we would say that for a one-minute
increase in waiting time, we would predict a 0.076 minute increase in
eruption duration. The intercept is a little bit trickier. Plugging in
0 for <span class="math inline">\(x\)</span>, we get a predicted eruption duration of <span class="math inline">\(-1.87\)</span> minutes.
There are two issues with this. First, a negative eruption duration
doesn’t make sense… but it also doesn’t make sense to have a waiting
time of 0 minutes.</p>
</blockquote>
<div id="the-coefficient-of-determination" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> The Coefficient of Determination<a href="regression-and-correlation.html#the-coefficient-of-determination" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With the correlation and regression line in hand, we will add one last
piece for considering the fit of a regression line. The <strong>coefficient of
determination</strong>, <span class="math inline">\(R^2\)</span>, is the square of the correlation coefficient.
This value tells us how much of the variability around the regression
line is accounted for by the regression. An easy way to interpret this
value is to assign it a letter grade. For example, if <span class="math inline">\(R^2 = 0.84\)</span>, the
predictive capabilities of the regression line get a B.</p>
</div>
<div id="when-prediction-goes-wrong" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> When Prediction Goes Wrong<a href="regression-and-correlation.html#when-prediction-goes-wrong" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It’s important to stop and think about our predictions. Sometimes, the
numbers don’t make sense and it’s easy to see that there’s something
wrong with the prediction. Other times, these issues are more insidious.
Usually, all of these issues result from what we call <em>extrapolation</em>,
applying a model estimate for values outside of the data’s range for
<span class="math inline">\(x\)</span>. Our linear model is only an approximation, and we don’t know
anything about how the relationship outside of the scope of our data!</p>
<p>Consider the following data with the best fit line drawn on the scatter
plot.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>The best fit line is <span class="math display">\[\hat{y} = 2.69 + 0.179x\]</span> and the correlation is
<span class="math inline">\(R=0.877\)</span>. Then the coefficient of determination is <span class="math inline">\(R^2 = 0.767\)</span>
(think: a C grade), so the model has decent predictive capabilities.
More precisely, the model accounts for 76.7% of the variability about
the regression line. Now suppose we wanted to predict the value of <span class="math inline">\(y\)</span>
when <span class="math inline">\(x=0.1\)</span>: <span class="math display">\[\hat{y} = 2.66 + 0.181\times0.1 = 2.67\]</span> This seems like
a perfectly reasonable number… But what if I told you that I generated
the data using the model <span class="math inline">\(y = 2\ln(x) + \text{random error}\)</span>? (If you’re
not familiar with the natural log, <span class="math inline">\(\ln\)</span>, don’t worry about it! You
won’t need to use it.) The true (population) best-fit model would look
like this:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>The vertical lines at <span class="math inline">\(x=5\)</span> and <span class="math inline">\(x=20\)</span> show the bounds of our data. The
blue dot at <span class="math inline">\(x=0.1\)</span> is the predicted value <span class="math inline">\(\hat{y}\)</span> based on the linear
model. The dashed horizontal line helps demonstrate just how far this
estimate is from the true population value! This does <em>not</em> mean there’s
anything inherently wrong with our model. If it works well from <span class="math inline">\(x=5\)</span> to
<span class="math inline">\(x=20\)</span>, great, it’s doing its job!</p>
</div>
<div id="section-exercises-8" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="regression-and-correlation.html#section-exercises-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>The Loblolly pine tree dataset contains information about <code>height</code>
(in feet) and <code>age</code> (in years) of Loblolly pine trees. We want to
use <code>height</code> to predict <code>age</code>. The sample statistics for these data
are</li>
</ol>
<table>
<thead>
<tr>
<th align="center"></th>
<th align="center">Height</th>
<th align="center">Age</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">mean</td>
<td align="center"><span class="math inline">\(32.36\)</span></td>
<td align="center"><span class="math inline">\(13.00\)</span></td>
</tr>
<tr>
<td align="center">sd</td>
<td align="center"><span class="math inline">\(20.67\)</span></td>
<td align="center"><span class="math inline">\(7.90\)</span></td>
</tr>
<tr>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(R = 0.90\)</span></td>
</tr>
</tbody>
</table>
<ol>
<ol style="list-style-type: lower-alpha;">
<li>
Which variable should be the predictor (<span class="math inline">\(x\)</span>) and which should be the
outcome (<span class="math inline">\(y\)</span>)? How do you know?
</li>
<li>
Calculate the slope.
</li>
<li>
Calculate the intercept.
</li>
<li>
Write out your regression line.
</li>
<li>
<p>Interpret your slope and intercept values in the context of the problem.</p>
</ol>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>The <code>penguins</code> dataset (from the <code>PalmerPenguins</code> package in R) has
data on various penguin body measurements. We want to build a model
for predicting a penguin’s <code>body mass</code> from its <code>flipper length</code>.
The table below contains some summary information about these data.
The correlation is <span class="math inline">\(R = 0.871\)</span>.</li>
</ol>
<table>
<thead>
<tr>
<th></th>
<th>Body Mass (g)</th>
<th>Flipper Length (mm)</th>
</tr>
</thead>
<tbody>
<tr>
<td>Minimum</td>
<td>2700.0</td>
<td>172.0</td>
</tr>
<tr>
<td>Maximum</td>
<td>6300.0</td>
<td>231.0</td>
</tr>
<tr>
<td>Mean</td>
<td>4201.75</td>
<td>200.92</td>
</tr>
<tr>
<td>Standard Deviation</td>
<td>801.95</td>
<td>14.06</td>
</tr>
</tbody>
</table>
<ol>
<ol style="list-style-type: lower-alpha;">
<li>
Based on the prompt, which variable should be your outcome (<span class="math inline">\(y\)</span>) and
which your predictor (<span class="math inline">\(x\)</span>)?
</li>
<li>
Calculate the slope. Interpret your value in the context of the
problem.
</li>
<li>
Calculate the intercept. Interpret your value in the context of the
problem. Does this interpretation make sense?
</li>
<li>
Write out the linear regression line using your slope and intercept
from parts (b) and (c).
</li>
<li>
Find and interpret the coefficient of determination, <span class="math inline">\(R^2\)</span>, for this
model.
</li>
<li>
Predict the body mass for a penguin with a flipper length of 200mm.
Do you have any concerns with this prediction?
</li>
<li>
Predict the body mass for a penguin with a flipper length of 150mm.
Do you have any concerns with this prediction?
</li>
</ol>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>The <code>mtcars</code> dataset has measurements (from 1974) on various aspects
of automobile design for 32 automobiles. Suppose we want to use
<code>horsepower</code> to predict <code>quarter mile time</code>. The sample statistics
for these data are</li>
</ol>
<table>
<thead>
<tr>
<th align="center"></th>
<th align="center">Horsepower</th>
<th align="center">Quarter Mile Time (sec)</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">mean</td>
<td align="center"><span class="math inline">\(146.69\)</span></td>
<td align="center"><span class="math inline">\(17.85\)</span></td>
</tr>
<tr>
<td align="center">sd</td>
<td align="center"><span class="math inline">\(68.56\)</span></td>
<td align="center"><span class="math inline">\(1.79\)</span></td>
</tr>
<tr>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(R = -0.708\)</span></td>
</tr>
</tbody>
</table>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<ol>
<ol style="list-style-type: lower-alpha;">
<li>
Based on the prompt, which variable should be your outcome and which
your predictor?
</li>
<li>
Calculate the slope. Interpret your value in the context of the
problem.
</li>
<li>
Calculate the intercept. Interpret your value in the context of the
problem. Does this interpretation make sense?
</li>
<li>
Write out the linear regression line using your slope and intercept
from parts (b) and (c).
</li>
<li>
What does the correlation tell us about the relationship between
horsepower and quarter mile time?
</li>
<li>
Find and interpret the coefficient of determination, <span class="math inline">\(R^2\)</span>, for this
model.
</li>
<li>
Predict the quarter mile time for a car with horsepower equal to
175. Do you have any concerns with this prediction?
</li>
<li>
Predict the quarter mile time for a car with horsepower equal to
500. Do you have any concerns with this prediction?
</li>
</ol>
</ol>
</div>
</div>
<div id="r-lab-scatterplots-and-regression" class="section level2 unnumbered hasAnchor">
<h2>R Lab: Scatterplots and Regression<a href="regression-and-correlation.html#r-lab-scatterplots-and-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="scatterplots" class="section level3 unnumbered hasAnchor">
<h3>Scatterplots<a href="regression-and-correlation.html#scatterplots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s create a scatterplot from the <code>faithful</code> dataset in R, which
contains measurements on waiting time and eruption duration for Old
Faithful geyser in Yellowstone National Park. We can use some of the
same arguments we used with the <code>hist</code> and <code>boxplot</code> commands to give it
titles:</p>
<ul>
<li><code>x</code> is the variable I want represented on the x-axis (horizontal
axis).</li>
<li><code>y</code> is the variable I want represented on the y-axis (vertical
axis).</li>
<li><code>main</code> is where I can give the plot a new title. (Make sure to put
the title in quotes!)</li>
<li><code>xlab</code> is the x-axis title.</li>
<li><code>ylab</code> is the y-axis title.</li>
</ul>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="regression-and-correlation.html#cb44-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;faithful&quot;</span>)</span>
<span id="cb44-2"><a href="regression-and-correlation.html#cb44-2" tabindex="-1"></a><span class="fu">attach</span>(faithful)</span>
<span id="cb44-3"><a href="regression-and-correlation.html#cb44-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions,</span>
<span id="cb44-4"><a href="regression-and-correlation.html#cb44-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Scatterplot of Old Faithful Geyser Data&quot;</span>,</span>
<span id="cb44-5"><a href="regression-and-correlation.html#cb44-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Waiting Time (minutes)&quot;</span>,</span>
<span id="cb44-6"><a href="regression-and-correlation.html#cb44-6" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Eruption Duration (minutes)&quot;</span>)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
</div>
<div id="correlation-1" class="section level3 unnumbered hasAnchor">
<h3>Correlation<a href="regression-and-correlation.html#correlation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find the correlation between two variables <code>x</code> and <code>y</code>, we use the
command <code>cor(x,y)</code>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="regression-and-correlation.html#cb45-1" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions)</span></code></pre></div>
<pre><code>## [1] 0.9008112</code></pre>
<p>The correlation between waiting time and eruption duration for Old
Faithful Geyser is <span class="math inline">\(-0.645\)</span>.</p>
</div>
<div id="finding-a-regression-line-1" class="section level3 unnumbered hasAnchor">
<h3>Finding a Regression Line<a href="regression-and-correlation.html#finding-a-regression-line-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find a regression line using R, we use the command <code>lm</code>, which stands
for “linear model”. The necessary argument is the <code>formula</code>, which takes
the form <code>y ~ x</code>. For example, to find the regression line for the Old
Faithful geyser data with waiting time predicting eruption duration,
<span class="math display">\[\text{eruptions} = b_0 + b_1\times\text{waiting}\]</span> we would use
<code>formula = eruptions ~ waiting</code>:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="regression-and-correlation.html#cb47-1" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> eruptions <span class="sc">~</span> waiting)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eruptions ~ waiting)
## 
## Coefficients:
## (Intercept)      waiting  
##    -1.87402      0.07563</code></pre>
<p>The <code>lm</code> command prints out the intercept, <span class="math inline">\(b_0\)</span> and the slope
(waiting), <span class="math inline">\(b_1\)</span>. So the model is
<span class="math display">\[\text{eruptions} = -1.87 + 0.08\times\text{waiting}\]</span></p>
<p>To get the coefficient of determination, we can simply find and square
the correlation coefficient. I will do this by putting the <code>cor()</code>
command in parentheses and squaring it by adding <code>^2</code> at the end:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="regression-and-correlation.html#cb49-1" tabindex="-1"></a>(<span class="fu">cor</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions))<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.8114608</code></pre>
<p>We might also be interested in adding a regression line to a
scatterplot. Now that we know how to find both separately, we can put
them together. I can add a line to a plot in R by using the command
<code>abline</code>. This command takes two primary arguments, along with some
optional arguments for adjusting line color and thickness:</p>
<ul>
<li><code>a</code>: the intercept (<span class="math inline">\(b_0\)</span>)</li>
<li><code>b</code>: the slope (<span class="math inline">\(b_1\)</span>)</li>
<li><code>col</code>: the line color</li>
<li><code>lwd</code>: the line width</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="regression-and-correlation.html#cb51-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> waiting, <span class="at">y =</span> eruptions,</span>
<span id="cb51-2"><a href="regression-and-correlation.html#cb51-2" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Scatterplot of Old Faithful Geyser Data&quot;</span>,</span>
<span id="cb51-3"><a href="regression-and-correlation.html#cb51-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Waiting Time (minutes)&quot;</span>,</span>
<span id="cb51-4"><a href="regression-and-correlation.html#cb51-4" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Eruption Duration (minutes)&quot;</span>)</span>
<span id="cb51-5"><a href="regression-and-correlation.html#cb51-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(<span class="at">formula =</span> eruptions <span class="sc">~</span> waiting))<span class="sc">$</span>coef[,<span class="dv">1</span>],</span>
<span id="cb51-6"><a href="regression-and-correlation.html#cb51-6" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descriptive-measures.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability-concepts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
