<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 5 Random Variables | Introduction to Statistics</title>
  <meta name="description" content="Module 5 Random Variables | Introduction to Statistics." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 5 Random Variables | Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Module 5 Random Variables | Introduction to Statistics." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 5 Random Variables | Introduction to Statistics" />
  
  <meta name="twitter:description" content="Module 5 Random Variables | Introduction to Statistics." />
  

<meta name="author" content="Dr. Lauren Perry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability-concepts.html"/>
<link rel="next" href="introduction-to-confidence-intervals.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Statistics!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-student"><i class="fa fa-check"></i>For the Student</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-programming"><i class="fa fa-check"></i>R Programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-the-instructor"><i class="fa fa-check"></i>For the Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i>Course Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistics-terminology"><i class="fa fa-check"></i><b>1.1</b> Statistics Terminology</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#statistical-sampling"><i class="fa fa-check"></i><b>1.2</b> Statistical Sampling</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#sampling-types"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Types</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-1"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design"><i class="fa fa-check"></i><b>1.3</b> Experimental Design</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experiments"><i class="fa fa-check"></i><b>1.3.1</b> Experiments</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.3.2</b> Observational Studies</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#experimental-design-principles"><i class="fa fa-check"></i><b>1.3.3</b> Experimental Design Principles</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-2"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#frequency-distributions"><i class="fa fa-check"></i><b>1.4</b> Frequency Distributions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#qualitative-variables"><i class="fa fa-check"></i><b>1.4.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#quantitative-variables"><i class="fa fa-check"></i><b>1.4.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#section-exercises-3"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-lab-data-basics-and-graphs"><i class="fa fa-check"></i>R Lab: Data Basics and Graphs</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a Calculator</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#random-number-generation"><i class="fa fa-check"></i>Random Number Generation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#entering-data"><i class="fa fa-check"></i>Entering Data</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-measures.html"><a href="descriptive-measures.html"><i class="fa fa-check"></i><b>2</b> Descriptive Measures</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#weighted-means"><i class="fa fa-check"></i><b>2.1.1</b> Weighted Means</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-4"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2</b> Measures of Variability</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descriptive-measures.html"><a href="descriptive-measures.html#standard-deviation"><i class="fa fa-check"></i><b>2.2.1</b> Standard Deviation</a></li>
<li class="chapter" data-level="2.2.2" data-path="descriptive-measures.html"><a href="descriptive-measures.html#the-interquartile-range"><i class="fa fa-check"></i><b>2.2.2</b> The Interquartile Range</a></li>
<li class="chapter" data-level="2.2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots"><i class="fa fa-check"></i><b>2.2.3</b> Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#section-exercises-5"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="descriptive-measures.html"><a href="descriptive-measures.html#descriptive-measures-for-populations"><i class="fa fa-check"></i><b>2.3</b> Descriptive Measures for Populations</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#r-lab-descriptive-statistics-and-boxplots"><i class="fa fa-check"></i>R Lab: Descriptive Statistics and Boxplots</a>
<ul>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-center"><i class="fa fa-check"></i>Finding Measures of Center</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#finding-measures-of-variability"><i class="fa fa-check"></i>Finding Measures of Variability</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#measures-of-position"><i class="fa fa-check"></i>Measures of Position</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#box-plots-1"><i class="fa fa-check"></i>Box Plots</a></li>
<li class="chapter" data-level="" data-path="descriptive-measures.html"><a href="descriptive-measures.html#course-survey-data"><i class="fa fa-check"></i>Course Survey Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>3</b> Regression and Correlation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-equations"><i class="fa fa-check"></i><b>3.1</b> Linear Equations</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatter-plots"><i class="fa fa-check"></i><b>3.1.1</b> Scatter Plots</a></li>
<li class="chapter" data-level="3.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-regression"><i class="fa fa-check"></i><b>3.1.2</b> Linear Regression</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-6"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>3.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-7"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line"><i class="fa fa-check"></i><b>3.3</b> Finding a Regression Line</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#the-coefficient-of-determination"><i class="fa fa-check"></i><b>3.3.1</b> The Coefficient of Determination</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#when-prediction-goes-wrong"><i class="fa fa-check"></i><b>3.3.2</b> When Prediction Goes Wrong</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#section-exercises-8"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#r-lab-scatterplots-and-regression"><i class="fa fa-check"></i>R Lab: Scatterplots and Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-1"><i class="fa fa-check"></i>Correlation</a></li>
<li class="chapter" data-level="" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#finding-a-regression-line-1"><i class="fa fa-check"></i>Finding a Regression Line</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-concepts.html"><a href="probability-concepts.html"><i class="fa fa-check"></i><b>4</b> Probability Concepts</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#experiments-sample-spaces-and-events"><i class="fa fa-check"></i><b>4.1</b> Experiments, Sample Spaces, and Events</a>
<ul>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-9"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-distributions"><i class="fa fa-check"></i><b>4.2</b> Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probability-concepts.html"><a href="probability-concepts.html#venn-diagrams"><i class="fa fa-check"></i><b>4.2.1</b> Venn Diagrams</a></li>
<li class="chapter" data-level="4.2.2" data-path="probability-concepts.html"><a href="probability-concepts.html#probability-axioms"><i class="fa fa-check"></i><b>4.2.2</b> Probability Axioms</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-10"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#rules-of-probability"><i class="fa fa-check"></i><b>4.3</b> Rules of Probability</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="probability-concepts.html"><a href="probability-concepts.html#addition-rules"><i class="fa fa-check"></i><b>4.3.1</b> Addition Rules</a></li>
<li class="chapter" data-level="4.3.2" data-path="probability-concepts.html"><a href="probability-concepts.html#contingency-tables"><i class="fa fa-check"></i><b>4.3.2</b> Contingency Tables</a></li>
<li class="chapter" data-level="4.3.3" data-path="probability-concepts.html"><a href="probability-concepts.html#complements"><i class="fa fa-check"></i><b>4.3.3</b> Complements</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-11"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-concepts.html"><a href="probability-concepts.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probability-concepts.html"><a href="probability-concepts.html#multiplication-rules"><i class="fa fa-check"></i><b>4.4.1</b> Multiplication Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-concepts.html"><a href="probability-concepts.html#law-of-total-probability"><i class="fa fa-check"></i><b>4.4.2</b> Law of Total Probability</a></li>
<li class="chapter" data-level="4.4.3" data-path="probability-concepts.html"><a href="probability-concepts.html#bayes-theorem"><i class="fa fa-check"></i><b>4.4.3</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="" data-path="probability-concepts.html"><a href="probability-concepts.html#section-exercises-12"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>5</b> Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.1</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="random-variables.html"><a href="random-variables.html#the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> The Mean and Standard Deviation</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-13"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> The Binomial Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="random-variables.html"><a href="random-variables.html#expected-value-and-variance"><i class="fa fa-check"></i><b>5.2.1</b> Expected Value and Variance</a></li>
<li class="chapter" data-level="5.2.2" data-path="random-variables.html"><a href="random-variables.html#probabilities-with-inequalities"><i class="fa fa-check"></i><b>5.2.2</b> Probabilities with Inequalities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-14"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="random-variables.html"><a href="random-variables.html#the-normal-distribution"><i class="fa fa-check"></i><b>5.3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="random-variables.html"><a href="random-variables.html#z-scores"><i class="fa fa-check"></i><b>5.3.1</b> Z-Scores</a></li>
<li class="chapter" data-level="5.3.2" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities"><i class="fa fa-check"></i><b>5.3.2</b> Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="5.3.3" data-path="random-variables.html"><a href="random-variables.html#percentiles"><i class="fa fa-check"></i><b>5.3.3</b> Percentiles</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#section-exercises-15"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#r-lab-probabilities-and-percentiles"><i class="fa fa-check"></i>R Lab: Probabilities and Percentiles</a>
<ul>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#binomial-probabilities"><i class="fa fa-check"></i>Binomial Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-probabilities-1"><i class="fa fa-check"></i>Normal Distribution Probabilities</a></li>
<li class="chapter" data-level="" data-path="random-variables.html"><a href="random-variables.html#normal-distribution-percentiles"><i class="fa fa-check"></i>Normal Distribution Percentiles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Introduction to Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#sampling-error"><i class="fa fa-check"></i><b>6.1.1</b> Sampling Error</a></li>
<li class="chapter" data-level="6.1.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>6.1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-16"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#developing-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Developing Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>6.2.1</b> Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-17"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#other-levels-of-confidence"><i class="fa fa-check"></i><b>6.3</b> Other Levels of Confidence</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#breaking-down-a-confidence-interval"><i class="fa fa-check"></i><b>6.3.1</b> Breaking Down a Confidence Interval</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-18"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-level-precision-and-sample-size"><i class="fa fa-check"></i><b>6.4</b> Confidence Level, Precision, and Sample Size</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-19"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intervals-for-a-mean"><i class="fa fa-check"></i><b>6.5</b> Confidence Intervals for a Mean</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#the-t-distribution"><i class="fa fa-check"></i><b>6.5.1</b> The T-Distribution</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#section-exercises-20"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#r-lab-confidence-intervals"><i class="fa fa-check"></i>R Lab: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-z-critical-values"><i class="fa fa-check"></i>Finding Z Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#finding-t-critical-values"><i class="fa fa-check"></i>Finding T Critical Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-confidence-intervals.html"><a href="introduction-to-confidence-intervals.html#confidence-intevals-for-a-mean"><i class="fa fa-check"></i>Confidence Intevals for a Mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Introduction to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Logic of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#decision-errors"><i class="fa fa-check"></i><b>7.1.1</b> Decision Errors</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-21"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#confidence-interval-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Confidence Interval Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-22"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#critical-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Critical Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#test-statistics"><i class="fa fa-check"></i><b>7.3.1</b> Test statistics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-23"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-value-approach-to-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> P-Value Approach to Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#p-values"><i class="fa fa-check"></i><b>7.4.1</b> P-Values</a></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#section-exercises-24"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#r-lab-hypothesis-tests-for-a-mean"><i class="fa fa-check"></i>R Lab: Hypothesis Tests for a Mean</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html"><i class="fa fa-check"></i><b>8</b> Inference for a Proportion</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-intervals-for-a-proportion"><i class="fa fa-check"></i><b>8.1</b> Confidence Intervals for a Proportion</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-25"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i><b>8.2</b> Hypothesis Tests for a Proportion</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#confidence-interval-approach"><i class="fa fa-check"></i><b>8.2.1</b> Confidence Interval Approach</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#critical-value-approach"><i class="fa fa-check"></i><b>8.2.2</b> Critical Value Approach</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#p-value-approach"><i class="fa fa-check"></i><b>8.2.3</b> P-Value Approach</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#section-exercises-26"><i class="fa fa-check"></i>Section Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-proportion.html"><a href="inference-for-a-proportion.html#r-hypothesis-tests-for-a-proportion"><i class="fa fa-check"></i>R: Hypothesis Tests for a Proportion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html"><i class="fa fa-check"></i><b>9</b> Inference: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions"><i class="fa fa-check"></i><b>9.1</b> Hypothesis Tests for Two Proportions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>9.1.1</b> Confidence Intervals for Two Proportions</a></li>
<li class="chapter" data-level="9.1.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#critical-values-test-statistics-and-p-values"><i class="fa fa-check"></i><b>9.1.2</b> Critical Values, Test Statistics, and P-Values</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means"><i class="fa fa-check"></i><b>9.2</b> Hypothesis Tests for Two Means</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#paired-samples"><i class="fa fa-check"></i><b>9.2.1</b> Paired Samples</a></li>
<li class="chapter" data-level="9.2.2" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#independent-samples"><i class="fa fa-check"></i><b>9.2.2</b> Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#r-lab-comparing-parameters"><i class="fa fa-check"></i>R Lab: Comparing Parameters</a>
<ul>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-proportions-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Proportions</a></li>
<li class="chapter" data-level="" data-path="inference-comparing-parameters.html"><a href="inference-comparing-parameters.html#hypothesis-tests-for-two-means-1"><i class="fa fa-check"></i>Hypothesis Tests for Two Means</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-on-regression.html"><a href="more-on-regression.html"><i class="fa fa-check"></i><b>10</b> More on Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-predictor-variable"><i class="fa fa-check"></i><b>10.1</b> A Hypothesis Test for a Predictor Variable</a></li>
<li class="chapter" data-level="10.2" data-path="more-on-regression.html"><a href="more-on-regression.html#a-hypothesis-test-for-a-regression-model"><i class="fa fa-check"></i><b>10.2</b> A Hypothesis Test for a Regression Model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="more-on-regression.html"><a href="more-on-regression.html#the-f-distribution"><i class="fa fa-check"></i><b>10.2.1</b> The F-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="more-on-regression.html"><a href="more-on-regression.html#model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Model Assumptions</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="more-on-regression.html"><a href="more-on-regression.html#normality-of-errors"><i class="fa fa-check"></i><b>10.3.1</b> Normality of Errors</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="more-on-regression.html"><a href="more-on-regression.html#constant-variance"><i class="fa fa-check"></i><b>10.4</b> Constant Variance</a></li>
<li class="chapter" data-level="10.5" data-path="more-on-regression.html"><a href="more-on-regression.html#uncorrelated-errors"><i class="fa fa-check"></i><b>10.5</b> Uncorrelated Errors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-tests.html"><a href="chi-square-tests.html"><i class="fa fa-check"></i><b>11</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#inference-for-a-population-variance"><i class="fa fa-check"></i><b>11.1</b> Inference for a Population Variance</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>11.1.1</b> The Chi-Square Distribution</a></li>
<li class="chapter" data-level="11.1.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#confidence-intervals-for-sigma"><i class="fa fa-check"></i><b>11.1.2</b> Confidence Intervals for <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#hypothesis-tests-for-sigma"><i class="fa fa-check"></i><b>11.1.3</b> Hypothesis Tests for <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chi-square-tests.html"><a href="chi-square-tests.html#the-ratio-of-two-variances"><i class="fa fa-check"></i><b>11.2</b> The Ratio of Two Variances</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-tests.html"><a href="chi-square-tests.html#goodness-of-fit"><i class="fa fa-check"></i><b>11.3</b> Goodness of Fit</a></li>
<li class="chapter" data-level="11.4" data-path="chi-square-tests.html"><a href="chi-square-tests.html#contingency-tables-1"><i class="fa fa-check"></i><b>11.4</b> Contingency Tables</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="anova.html"><a href="anova.html#what-is-the-analysis-of-variance-anova"><i class="fa fa-check"></i><b>12.1</b> What is the Analysis of Variance (ANOVA)</a></li>
<li class="chapter" data-level="12.2" data-path="anova.html"><a href="anova.html#multiple-comparisons-and-type-i-error-rate"><i class="fa fa-check"></i><b>12.2</b> Multiple Comparisons and Type I Error Rate</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-a-important-links-and-additional-resources"><i class="fa fa-check"></i>Appendix A: Important Links and Additional Resources</a>
<ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#applets"><i class="fa fa-check"></i>Applets</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#run-r-online"><i class="fa fa-check"></i>Run R Online</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-b-average-deviance"><i class="fa fa-check"></i>Appendix B: Average Deviance</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#appendix-c-deriving-a-confidence-interval"><i class="fa fa-check"></i>Appendix C: Deriving a Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html"><i class="fa fa-check"></i>Works Cited</a>
<ul>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="works-cited.html"><a href="works-cited.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="random-variables" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Module 5</span> Random Variables<a href="random-variables.html#random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In previous modules, we introduced the idea of variables and examined their distributions. We also began our discussion on probability theory. Now, we extend these concepts into what are called random variables. We will introduce the concept of random variables in general and will discuss a specific type of distribution - the binomial distribution. Then we will discuss a continuous probability distribution, the normal distribution. The normal distribution will provide a foundation for much of the inference we will complete throughout the rest of this course.</p>
<p><strong>Module Learning Objectives/Outcomes</strong></p>
<ol style="list-style-type: decimal">
<li>Discuss discrete random variables using key terminology.</li>
<li>Express cumulative probabilities using probability notation.</li>
<li>Calculate the expected value and standard deviation of a discrete random variable.</li>
<li>Calculate binomial probabilities.</li>
<li>Use z scores to compare observations on different scales.</li>
<li>Calculate probabilities for a normal distribution using area under the curve.</li>
<li>Calculate normal distribution percentiles.</li>
</ol>
<p><strong>R Objectives</strong></p>
<ol style="list-style-type: decimal">
<li>Calculate binomial probabilities.</li>
<li>Find cumulative probabilities for the standard normal distribution.</li>
<li>Find percentiles.</li>
</ol>
<p>This module’s outcomes correspond to course outcomes (4) use the binomial distribution as a model for discrete variables and (5) use the normal distribution as a model for continuous variables.</p>
<div id="discrete-random-variables" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Discrete Random Variables<a href="random-variables.html#discrete-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A <strong>random variable</strong> is a quantitative variable whose values are based on chance. By “chance”, we mean that you can’t <em>know</em> the outcome before it occurs.</p>
<p>A <strong>discrete random variable</strong> is a random variable whose possible values can be listed.</p>
<p>Notation:</p>
<ul>
<li><span class="math inline">\(x\)</span>,<span class="math inline">\(y\)</span>,<span class="math inline">\(z\)</span> (lower case letters) denote variables.</li>
<li><span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, <span class="math inline">\(Z\)</span> (upper case letters) denote <em>random</em> variables.</li>
</ul>
<p>In contrast to events, where we usually used letters toward the start of the alphabet, (random) variables are typically denoted by letters from the end of the alphabet.</p>
<ul>
<li><span class="math inline">\(\{X=x\}\)</span> denotes the event that the random variable <span class="math inline">\(X\)</span> equals <span class="math inline">\(x\)</span>.</li>
<li><span class="math inline">\(P(X=x)\)</span> denotes the probability that the random variable <span class="math inline">\(X\)</span> equals <span class="math inline">\(x\)</span>.</li>
</ul>
<p>Recall: a probability distribution is a list of all possible values and their corresponding probabilities. (See Section 3.3 for a refresher.) A <strong>probability histogram</strong> is a histogram where the heights of the bars correspond to the probability of each value. (This is very similar to a relative frequency histogram!) For discrete random variables, each “bin” is one of the listed values.</p>
<blockquote>
<p><strong>Example</strong>:</p>
<table>
<thead>
<tr>
<th align="left">Number of Siblings, <span class="math inline">\(x\)</span></th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left"><strong>Probability</strong>, <span class="math inline">\(P(X=x)\)</span></td>
<td align="center">0.200</td>
<td align="center">0.425</td>
<td align="center">0.275</td>
<td align="center">0.075</td>
<td align="center">0.025</td>
</tr>
</tbody>
</table>
<p>(Assume for the sake of the example that no one has more than 4 siblings.)</p>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p>Interpretation: in a large number of independent observations of a random variable <span class="math inline">\(X\)</span>, the proportion of times each possible value occurs will approximate the probability distribution of <span class="math inline">\(X\)</span>.</p>
<div id="the-mean-and-standard-deviation" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> The Mean and Standard Deviation<a href="random-variables.html#the-mean-and-standard-deviation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<center>
<font size='4'><b>Mean of a Discrete Random Variable</b></font>
</center>
<p>The mean of a discrete random variable <span class="math inline">\(X\)</span> is denoted <span class="math inline">\(\mu_X\)</span>. If it’s clear which random variable we’re talking about, we can drop the subscript and write <span class="math inline">\(\mu\)</span>.
<span class="math display">\[
  \mu_X = \Sigma xP(X=x)
\]</span>
where <span class="math inline">\(\Sigma\)</span> denotes “the sum over all values of <span class="math inline">\(x\)</span>”: <span class="math display">\[\Sigma xP(X=x) = x_1P(X=x_1) + x_2P(X=x_2) + \dots + x_nP(X=x_n).\]</span></p>
<p>The mean of a random variable is also called the <strong>expected value</strong> or <strong>expectation</strong>. Recall that measures of center are meant to identify the most common or most likely, thus the value we can <em>expect</em> to see (most often).</p>
<blockquote>
<p><strong>Example</strong>: for the Siblings distribution, <span class="math display">\[\mu = 0(0.200)+1(0.425)+2(0.275)+3(0.075)+4(0.025)=1.3\]</span>
Make sure you understand how we used the formula for <span class="math inline">\(\mu\)</span> and the probability distribution to come up with this number.</p>
</blockquote>
<p>The random variable <span class="math inline">\(X\)</span> represents draws from some population, so <span class="math inline">\(\mu\)</span> is just the population mean. In the above example, the mean number of siblings (for people in that population) is 1.3.</p>
<p>The larger the number of observations, the closer their average tends to be to <span class="math inline">\(\mu\)</span>. This is known as the <strong>law of large numbers</strong>.</p>
<blockquote>
<p><strong>Example</strong>: Suppose I took a random sample of 10 people and asked how many siblings they have. <span class="math display">\[2,2,2,2,1,0,3,1,2,0\]</span> In my random sample of 10, <span class="math inline">\(\bar{x}=2\)</span>, which is a reasonable estimate but not that close to the true mean <span class="math inline">\(\mu=1.3\)</span>.</p>
<ul>
<li>A random sample of 30 gave me a mean of <span class="math inline">\(\bar{x}=1.53\)</span>.</li>
<li>A random sample of 100 gave me a mean of <span class="math inline">\(\bar{x}=1.47\)</span>.</li>
<li>A random sample of 1000 gave me a mean of <span class="math inline">\(\bar{x}=1.307\)</span>.</li>
</ul>
</blockquote>
<p>We use concepts related to the law of large numbers as a foundation for statistical inference, but note that - although very large samples are nice to have - it’s not necessary to take enormous samples all the time. Often, we can come to interesting conclusions with fewer than 30 observations!</p>
<center>
<font size='4'><b>Standard Deviation of a Discrete Random Variable</b></font>
</center>
<p>The variance of a discrete random variable <span class="math inline">\(X\)</span> is denoted <span class="math inline">\(\sigma_X^2\)</span> (or <span class="math inline">\(\sigma^2\)</span> if it’s clear which variable we’re talking about).
<span class="math display">\[ \sigma_X^2 = \Sigma[(x-\mu_X)^2P(X=x)]\]</span>
OR
<span class="math display">\[ \sigma_X^2 = \Sigma[x^2P(X=x)]-\mu_X^2\]</span>
These formulas are <em>exactly</em> equivalent and you may use whichever you wish, but note that the second may be a little easier to work with.</p>
<p>As before, the standard deviation is the square root of the variance: <span class="math display">\[\sigma = \sqrt{\sigma^2}\]</span></p>
<blockquote>
<p><strong>Example</strong>: Calculate the standard deviation of the Siblings variable.</p>
<p>In general, a table is the best way to keep track of a variance calculation:</p>
<table>
<thead>
<tr>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(P(X=x)\)</span></th>
<th align="center"><span class="math inline">\(xP(X=x)\)</span></th>
<th align="center"><span class="math inline">\(x^2\)</span></th>
<th align="center"><span class="math inline">\(x^2P(X=x)\)</span></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">0</td>
<td align="center">0.200</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr>
<td align="center">1</td>
<td align="center">0.425</td>
<td align="center">0.425</td>
<td align="center">1</td>
<td align="center">0.425</td>
</tr>
<tr>
<td align="center">2</td>
<td align="center">0.275</td>
<td align="center">0.550</td>
<td align="center">4</td>
<td align="center">1.100</td>
</tr>
<tr>
<td align="center">3</td>
<td align="center">0.075</td>
<td align="center">0.225</td>
<td align="center">9</td>
<td align="center">0.675</td>
</tr>
<tr>
<td align="center">4</td>
<td align="center">0.025</td>
<td align="center">0.100</td>
<td align="center">16</td>
<td align="center">0.400</td>
</tr>
<tr>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\mu\)</span> = 1.3</td>
<td align="center"></td>
<td align="center">Total = 2.6</td>
</tr>
</tbody>
</table>
<p>Then the variance is <span class="math display">\[\sigma^2 = 2.6 - 1.3^2 = 0.9\]</span> and the standard deviation is <span class="math display">\[\sigma = \sqrt{0.9} = 0.9539.\]</span></p>
</blockquote>
</div>
<div id="section-exercises-13" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="random-variables.html#section-exercises-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol>
<li>
Consider the following probability distribution for some discrete random variable.
</li>
<table>
<thead>
<tr>
<th align="center">x</th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">P(x)</td>
<td align="center">0.1</td>
<td align="center">0.2</td>
<td align="center">0.3</td>
<td align="center">0.3</td>
<td align="center">0.1</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha;">
<li>
Use probability notation to write the probability that <span class="math inline">\(X\)</span> is less than 2. Then, use the table to find this probability.
</li>
<li>
Find the expected value of the random variable <span class="math inline">\(X\)</span>.
</li>
<li>
Find the standard deviation of the random variable.
</li>
</ol>
<li>
Consider the probability distribution of the number of dogs owned by people in the US. Assume for the sake of the problem that nobody has more than three dogs.
</li>
<table>
<thead>
<tr>
<th>Number of dogs, <span class="math inline">\(x\)</span></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
</tr>
</thead>
<tbody>
<tr>
<td>Proportion of people, <span class="math inline">\(p(x)\)</span></td>
<td>0.635</td>
<td>0.212</td>
<td>0.131</td>
<td>0.022</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha;">
<li>
Find the mean number of dogs owned by people in the US.
</li>
<li>
For a randomly selected household, what is the probability they have at least 2 dogs?</il>
</ol>
</ol>
</div>
</div>
<div id="the-binomial-distribution" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> The Binomial Distribution<a href="random-variables.html#the-binomial-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The binomial distribution is used to describe the number of successes in some fixed number of trials (or some set sample size).</p>
<blockquote>
<p><strong>Example</strong>: Suppose we will roll three dice: a green (<span class="math inline">\(G\)</span>), a blue (<span class="math inline">\(B\)</span>), and a red (<span class="math inline">\(R\)</span>). What is the probability that exactly one of them will result in a 1?</p>
<p>Let’s start by considering one specific scenario where exactly one die results in a 1:
<span class="math display">\[\begin{aligned}
P(G = 1 \text{ and } B \ne 1 \text{ and } R \ne 1 ) &amp;= P(G = 1)P(B &gt; 1)P(R &gt; 1) \\
&amp;= \frac{1}{6} \times \frac{5}{6} \times \frac{5}{6} \\
&amp;= (0.1667)(0.8333)(0.8333) \\
&amp;= (0.1667)^1(0.8333)^2 \\
&amp;= 0.1157
\end{aligned} \]</span>
Note that “not 1” in this scenario is the same as “greater than 1” and includes the values <span class="math inline">\(2\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(4\)</span>, <span class="math inline">\(5\)</span>, and <span class="math inline">\(6\)</span>, which is how we come up with those individual probabilities. Also notice that our first step was to use the multiplication rule for independent events!</p>
<p>But we also could have considered the scenarios where the Blue or Red die was the single die to roll a 1. In each case, the probability is the same: <span class="math inline">\((0.1667)^1(0.8333)^2\)</span> so we need to multiply this probability by 3: <span class="math display">\[P(\text{exactly one four-sided die rolls a 1}) = 3\times(0.1667)^1(0.8333)^2 = 0.3472\]</span></p>
</blockquote>
<p>Next, think back to replication in an experiment. Each replication is what we call a <strong>trial</strong>. We will consider a setting where each trial has two possible outcomes.</p>
<blockquote>
<p><strong>Example</strong>: Suppose you want to know if a coin is fair (both sides equally likely). You might flip the coin 100 times (thus running 100 trials). Each trial is a flip of the coin with two possible outcomes: heads or tails.</p>
</blockquote>
<p>The product of the first <span class="math inline">\(k\)</span> positive integers <span class="math inline">\((1, 2, 3, \dots)\)</span> is called <strong>k-factorial</strong>, denoted <span class="math inline">\(k!\)</span>: <span class="math display">\[k! = k \times (k-1) \times\dots\times 3 \times 2 \times 1\]</span> We define <span class="math inline">\(0!=1\)</span>.</p>
<blockquote>
<p><strong>Example</strong>: <span class="math inline">\(5! = 5 \times 4 \times 3 \times 2 \times 1 = 120\)</span></p>
</blockquote>
<p>If <span class="math inline">\(n\)</span> is a positive integer <span class="math inline">\((1, 2, 3, \dots)\)</span> and <span class="math inline">\(x\)</span> is a nonnegative integer <span class="math inline">\((0, 1, 2, \dots)\)</span> with <span class="math inline">\(x \le n\)</span>, the <strong>binomial coefficient</strong> is <span class="math display">\[\binom{n}{x} = \frac{n!}{x!(n-x)!}\]</span></p>
<blockquote>
<p><strong>Example</strong>: <span class="math display">\[\binom{5}{2} = \frac{5!}{2!(5-2)!} = \frac{5 \times 4 \times 3 \times 2 \times 1}{(2 \times 1)(3 \times 2 \times 1)}\]</span></p>
</blockquote>
<p>The binomial coefficient represents the number of ways to select <span class="math inline">\(x\)</span> objects from a group of <span class="math inline">\(n\)</span> objects, <em>without replacement</em>. When we say “without replacement”, we mean that we cannot select an object more than once. (Note that this implies a binomial coefficient should <em>always</em> result in a whole number!) This turns out to be a handy thing to be able to calculate when working with probability and random variables.</p>
<blockquote>
<p><strong>Example</strong>: When we worked out the probability of rolling exactly one <span class="math inline">\(1\)</span> when rolling three dice, we found that there were <span class="math inline">\(3\)</span> possible ways to do so. Using the binomial coefficient, <span class="math inline">\(n = 3\)</span> rolls and <span class="math inline">\(x=1\)</span> roll of a 1, so <span class="math display">\[\binom{3}{1} = \frac{3!}{1!(3-2)!} = \frac{3 \times 2 \times 1}{(1) \times (2 \times 1)} = \frac{6}{2} = 3\]</span>
In this case, it was fairly straightforward to list all the ways to roll exactly one <span class="math inline">\(1\)</span>, but sometimes it’s not so simple and the binomial coefficient will save us a lot of headache.</p>
</blockquote>
<p>Sometimes, we may want to simplify a binomial coefficient <em>before</em> taking all of the factorials. Why? Well, <span class="math display">\[20! = 2,432,902,008,176,640,000\]</span> Most calculators will not print this number! Instead, you’ll get an error or a rounded version printed using scientific notation. Neither will help you accurately calculate the binomial coefficient.</p>
<blockquote>
<p><strong>Example</strong>: <span class="math display">\[\binom{20}{17} = \frac{20!}{17!3!} = \frac{20\times 19\times 18\times 17\times 16\times \dots \times 3\times 2\times 1}{(17\times 16\times \dots \times 3\times 2\times 1)(3\times 2\times 1)}\]</span> but notice that I can rewrite <span class="math inline">\(20!\)</span> as <span class="math inline">\(20\times 19\times 18\times 17!\)</span>, so <span class="math display">\[\binom{20}{17} = \frac{20\times 19\times 18\times 17!}{17!(3\times 2\times 1)} = \frac{20\times 19\times 18}{3\times 2\times 1} = \frac{6840}{6} = 1140\]</span></p>
</blockquote>
<p><strong>Bernoulli trials</strong> are repeated trials of an experiment where:</p>
<ol style="list-style-type: decimal">
<li>Each trial has two possible outcomes: success and failure.</li>
<li>Trials are independent.</li>
<li>The probability of success (the <strong>success probability</strong>) <span class="math inline">\(p\)</span> remains the same from one trial to the next: <span class="math display">\[P(X=\text{success})=p\]</span></li>
</ol>
<p>The <strong>binomial distribution</strong> is the probability distribution for the number of successes in a sequence of Bernoulli trials.</p>
<p>Fact: in <span class="math inline">\(n\)</span> Bernoulli trials, the number of outcomes that contain exactly <span class="math inline">\(x\)</span> successes equals the binomial coefficient <span class="math inline">\(\binom{n}{x}\)</span>.</p>
<blockquote>
<p><strong>Example</strong>: Find the probability of rolling exactly one <span class="math inline">\(1\)</span> in three dice rolls.</p>
<p>In this scenario, we are primarily interested in an outcome related to rolling a <span class="math inline">\(1\)</span>, so we will let this be our <em>success</em>. Rolling exactly one <span class="math inline">\(1\)</span> means observing exactly one success. The other possibility (to rolling a <span class="math inline">\(1\)</span>) is <em>not</em> rolling a <span class="math inline">\(1\)</span>, so this must be our failure.
From our previous examples, we know this probability can be written as <span class="math display">\[\binom{3}{1}(0.1667)^1(0.8333)^2\]</span></p>
<ul>
<li><span class="math inline">\(\binom{3}{1}\)</span> is the number of ways to observe <span class="math inline">\(1\)</span> success in <span class="math inline">\(3\)</span> trials, or rolls of the dice.</li>
<li><span class="math inline">\(0.1667\)</span> is the probability of success.</li>
<li>The <span class="math inline">\(1\)</span> in the binomial coefficient and the power is the number of successes.</li>
<li><span class="math inline">\(0.8333\)</span> is the probability of failure.
<ul>
<li>By the complement rule, this value is equal to <span class="math inline">\(1-0.1667\)</span> (one minus the probability of success).</li>
</ul></li>
<li>The <span class="math inline">\(2\)</span> in the power is the number of failures.
<ul>
<li>If each trial is a success or a failure, and we are interested in <span class="math inline">\(1\)</span> success out of <span class="math inline">\(3\)</span> failures, then the other <span class="math inline">\(3-1=2\)</span> trials must be failures.</li>
</ul></li>
</ul>
<p>This is a binomial probability! Let’s see how this becomes the general binomial probability formula.</p>
</blockquote>
<center>
<font size='4'><b>Binomial Probability Formula</b></font>
</center>
<p>Let <span class="math inline">\(x\)</span> denote the total number of successes in <span class="math inline">\(n\)</span> Bernoulli trials with success probability <span class="math inline">\(p\)</span>. The probability distribution of the random variable <span class="math inline">\(X\)</span> is given by <span class="math display">\[P(X=x) = \binom{n}{x}p^x(1-p)^{n-x} \quad\quad x = 0,1,2,\dots,n\]</span> The random variable <span class="math inline">\(X\)</span> is called a <strong>binomial random variable</strong> and is said to have the <strong>binomial distribution</strong>. Because <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> fully define this distribution, they are called the distribution’s <strong>parameters</strong>.</p>
<p>To find a binomial probability formula:</p>
<ol>
<li>
Check assumptions.
</li>
<ol type="a">
<li>
Exactly <span class="math inline">\(n\)</span> trials to be performed.
</li>
<li>
Two possible outcomes for each trial.
</li>
<li>
Trials are independent (each trial does not impact the result of the next)
</li>
<li>
Success probability <span class="math inline">\(p\)</span> remains the same from trial to trial.
</li>
</ol>
<li>
Identify a “success”. Generally, this is whichever of the two possible outcomes we are most interested in.
</li>
<li>
Determine the success probability <span class="math inline">\(p\)</span>.
</li>
<li>
Determine <span class="math inline">\(n\)</span>, the number of trials.
</li>
<li>
Plug <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> into the binomial distribution formula.
</li>
</ol>
<blockquote>
<p><strong>Example</strong>: Approximately 44.5% of US households have dogs. If we are to take a random sample of 10 US households, what is the probability that exactly 4 of them will have dogs?</p>
<p><em>Solution</em>:</p>
<ol style="list-style-type: decimal">
<li>Assumptions: (1) We will take a random sample of 10 households, so there are exactly 10 trials to be performed. (2) The two possible outcomes are “dogs” or “no dogs”. (3) Since this is a random sample, we can assume that trials are independent. (4) The probability of a US household having a dog is (always) 0.445, so the success probability is constant.</li>
<li>We will let <span class="math inline">\(\text{success = household has dog(s)}\)</span> since the probability of interest relates to having dogs. Therefore <span class="math inline">\(\text{failure = household does not have dogs}\)</span>.</li>
<li><span class="math inline">\(P(\text{success}) = 0.445\)</span> from the problem statement.</li>
<li>We will take a random sample of 10, so our number of trials is <span class="math inline">\(n=10\)</span>.</li>
<li>The formula looks like <span class="math display">\[P(X=x) = \binom{n}{x}p^x(1-p)^{n-x} = \binom{10}{x}0.445^x(1-0.445)^{10-x}\]</span> For exactly 4 successes, we set <span class="math inline">\(x=4\)</span>: <span class="math display">\[\begin{aligned}P(X=4) &amp;= \binom{10}{4}0.445^4(1-0.445)^{10-4} \\ &amp;=\binom{10}{4}0.445^4(0.555)^{6}\end{aligned} \]</span>
Now, let’s take a moment to work through that binomial coefficient: <span class="math display">\[\begin{aligned}\binom{10}{4} &amp;= \frac{10!}{4!6!} \\ &amp;= \frac{10\times 9 \times 8 \times 7 \times 6!}{(4 \times 3 \times 2 \times 1)\times 6!} \\ &amp;= \frac{10\times 9 \times 8 \times 7}{4 \times 3 \times 2 \times 1} \\ &amp;= \frac{5040}{24} \\ &amp;= 210
\end{aligned}\]</span>
Plugging that into our binomial probability formula,
<span class="math display">\[\begin{aligned}P(X=4) &amp;=210\times 0.445^4 \times 0.555^{6} \\ &amp;= 210 \times 0.0392 \times 0.0292 \\ &amp;= 0.241 \end{aligned}\]</span>
So the probability that exactly 4 of the 10 US households have dog(s) is 0.241.</li>
</ol>
</blockquote>
<div id="expected-value-and-variance" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Expected Value and Variance<a href="random-variables.html#expected-value-and-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The expected value (mean) of a binomial distribution is <span class="math inline">\(\mu = np\)</span>. The variance is <span class="math inline">\(\sigma^2 = np(1-p)\)</span>.</p>
<p>The shape of a binomial distribution is determined by the success probability:</p>
<ul>
<li>If <span class="math inline">\(p \approx 0.5\)</span>, the distribution is approximately symmetric.</li>
<li>If <span class="math inline">\(p &lt; 0.5\)</span>, the distribution is right-skewed.</li>
<li>If <span class="math inline">\(p &gt; 0.5\)</span>, the distribution is left-skewed.</li>
</ul>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
</div>
<div id="probabilities-with-inequalities" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Probabilities with Inequalities<a href="random-variables.html#probabilities-with-inequalities" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also use the binomial probability formula to calculate probabilities like <span class="math inline">\(P(X\le x)\)</span>. Notice that we can rewrite this using concepts from the previous module <span class="math display">\[P(X \le k) = P(X=k \text{ or } X=k-1 \text{ or } \dots  \text{ or } X=2 \text{ or } X=1  \text{ or } X=0)\]</span> Since <span class="math inline">\(X\)</span> is a discrete random variable, each possible value is <em>disjoint</em>. We can use this! <span class="math display">\[P(X \le k) = P(X=k) + P(X=k-1) + \dots + P(X=2) + P(X=1) + P(X=0)\]</span></p>
<blockquote>
<p><strong>Example</strong>: <span class="math display">\[\begin{aligned}
P(X \le 3) =&amp; P(X = 3 \text{ or } X=2 \text{ or } X=1 \text{ or } X=0) \\
=&amp; P(X=3)+P(X=2)+P(X=1)+P(X=0)
\end{aligned}\]</span></p>
</blockquote>
<p>We can also extend this concept to work with probabilities like <span class="math inline">\(P(a &lt; X \le b)\)</span>.</p>
<blockquote>
<p><strong>Example</strong>: <span class="math inline">\(P(2 &lt; X \le 5)\)</span></p>
<p>First, notice that if <span class="math inline">\(2 &lt; X \le 5\)</span>, then <span class="math inline">\(X\)</span> can be 3, 4, or 5: <span class="math display">\[\begin{aligned} P(2 &lt; X \le 5) &amp;= P(X=3\text{ or }X=4\text{ or }X=5) \\
&amp;= P(X=3)+P(X=4)+P(X=5) \end{aligned}\]</span></p>
<p>Note: if going from <span class="math inline">\(2 &lt; X \le 5\)</span> to “<span class="math inline">\(X\)</span> can be 3, 4, or 5” doesn’t make sense to you, start by writing out the sample space. Suppose <span class="math inline">\(n=10\)</span>. Then the sample space for the binomial distribution is <span class="math display">\[S = \{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10\}\]</span> Then I can check any number in this sample space by plugging it in for <span class="math inline">\(X\)</span>. So for 1, I can check <span class="math inline">\(2 &lt; 1 \le 5\)</span>. Obviously this is not true, so we won’t include 1. Checking the number 2, I get <span class="math inline">\(2 &lt; 2 \le 5\)</span>. Since 2 &lt; 2 is NOT true, we don’t include 2. Etc.</p>
</blockquote>
<p>These concepts apply to any other type of inequality, too! Figure out which values in the sample space satisfy the inequality, apply the addition rule for disjoint outcomes, and add up the individual probabilities.</p>
</div>
<div id="section-exercises-14" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="random-variables.html#section-exercises-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol>
<li>
Suppose you are going to roll a 6-sided die seven times. What is the probability of getting exactly three <span class="math inline">\(6\)</span>s?
</li>
<li>
Over the course of a board game, a player is going to roll a 10-sized die 30 times. Find the expected value and standard deviation for the number of <span class="math inline">\(10\)</span>s rolled.
</li>
<li>
In the 2024 NFL season, Gardner Minshew, quarterback for the Raiders, completed 66.3% of his pass attempts. Suppose we will randomly select 10 passes by Minshew and see if they are completed.
</li>
<ol style="list-style-type: lower-alpha;">
<li>
What distribution could you use to model the probability that all 10 pass attempts are completed? Go through each condition and confirm is it satisfied.
</li>
<li>
Find the mean and standard deviation number of completed passes.
</li>
<li>
Find the probability that exactly 5 of the pass attempts are completed.
</li>
<li>
Find the probability that all 10 of the pass attempts are completed.
</li>
<li>
Find the probability that none of the pass attempts are completed.
</li>
</ol>
<li>
A restaurant has a reservation on the books for a 22 person birthday party. They know that 32% of their customers order dessert. The restaurant works with a local bakery to provide desserts, and they want to think about how many to order.
</li>
<ol style="list-style-type: lower-alpha;">
<li>
What distribution could we use to model the number of birthday party goers who order dessert? Justify your answer by checking any necessary conditions.
</li>
<li>
What are the expected value and standard deviation number of party goes who will order dessert?
</li>
<li>
Find the probability that no more than 3 people order dessert.
</li>
<li>
Find the probability that between 5 and 7 people (inclusive) order dessert.
</li>
</ol>
<li>
If you flip a fair coin 5 times, what is the probability of getting at least one heads? Hint: what is the complement of getting at least one heads?
</li>
<li>
For smokers, the probability of developing a severe lung infection at some point in their lifetime is 0.3.
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Suppose we take a random sample of 20 smokers. What distribution could you use to model the probability of some number of them developing a severe lung infection? Justify your answer by checking any necessary conditions.
</li>
<li>
Find the mean and standard deviation number of smokers (from the sample of 20) who will develop a severe lung infection during their lifetimes.
</li>
<li>
For our 20 smokers, find the probability that none of them develop a severe lung infection during their
lifetimes.
</li>
</ol>
<li>
Consider the probability distribution of the number of dogs owned by people in the US. (For the sake of the problem, assume no one has more than 3 dogs.)
</li>
<table>
<thead>
<tr>
<th>Number of dogs, <span class="math inline">\(x\)</span></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
</tr>
</thead>
<tbody>
<tr>
<td>Proportion of people, <span class="math inline">\(p(x)\)</span></td>
<td>0.635</td>
<td>0.212</td>
<td>0.131</td>
<td>0.022</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha;">
<li>
What proportion of people have at least one dog?
</li>
<li>
Consider two categories: (1) people with no dogs and (2) people with dog(s). A random sample of 10 people were asked about their dog ownership. Let Y be the random variable which counts number of people with (some number of) dogs. What is the distribution of Y? Justify your answer by checking any necessary conditions.
</li>
<li>
What is the probability that fewer than 3 people out of 10 will have dog(s)?
</ol>
</ol>
</div>
</div>
<div id="the-normal-distribution" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> The Normal Distribution<a href="random-variables.html#the-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we can represent a discrete variable with a probability histogram, what can we do with a continuous variable?</p>
<p>We represent the shape of a continuous variable using a <strong>density curve</strong>. This is like a histogram, but with a smooth curve:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>For a variable with a density curve, the proportion of all possible observations that lie within a specified range equals the corresponding area under the density curve.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>Properties of density curves:</p>
<ol style="list-style-type: decimal">
<li>The curve is always above the horizontal axis (because probabilities are always nonnegative).</li>
<li>The total area under the curve equals 1 (because <span class="math inline">\(P(S)=1\)</span>).</li>
</ol>
<p>A <strong>normal curve</strong> is a special type of density curve that has a “bell-shaped” distribution. In fact, all of the density curves I’ve shown in this section have been normal curves! We say that a variable is <strong>normally distributed</strong> or has a <strong>normal distribution</strong> if its distribution has the shape of a normal curve.</p>
<p>Why “normal”? Because it appears so often in practice! Lots of things are more common around the average and less common as you get farther from the average: height, amount of sleep people get each night, standardized test scores, etc. (In practice, these things aren’t <em>exactly</em> normally distributed… instead, they’re <strong>approximately normally distributed</strong> - and that’s ok.)</p>
<p>Normal distributions…</p>
<ul>
<li>have curves that extend indefinitely in both directions along the horizontal axis.</li>
<li>are fully determined by parameters mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>.</li>
<li>are symmetric and centered at <span class="math inline">\(\mu\)</span>.</li>
<li>have spreads that depend on <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<p>Pay close attention to the horizontal axis and how spread out the densities are in each of the following plots:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>Notice that the bottom left plot comes to a sharper peak, while the bottom right has a gentler slope. This is what we mean by “spread”: the density on the bottom right is the most spread out.</p>
<center>
<font size='4'><b>Empirical Rule</b></font>
</center>
<p>For any (approximately) normally distributed variable,</p>
<ol style="list-style-type: decimal">
<li>Approximately 68% of all possible observations lie within one standard deviation of the mean: <span class="math inline">\(\mu \pm \sigma.\)</span></li>
<li>Approximately 95% of all possible observations lie within two standard deviations of the mean: <span class="math inline">\(\mu \pm 2\sigma.\)</span></li>
<li>Approximately 99.7% of all possible observations lie within three standard deviations of the mean: <span class="math inline">\(\mu \pm 3\sigma.\)</span></li>
</ol>
<p>Given some data, you can check if approximately 68% of the data falls within <span class="math inline">\(\bar{x}\pm s\)</span>, 95% within <span class="math inline">\(\bar{x}\pm 2s\)</span>, and 99.7% within <span class="math inline">\(\bar{x}\pm 3s\)</span> to examine whether the data follow the empirical rule.</p>
<p>To check whether a variable is (approximately) normally distributed, we can check the histogram to see if it is symmetric and bell-shaped… or we can check to see if the variable conforms (approximately) to the empirical rule! If we decide it is approximately normal, we can estimate the parameters: <span class="math inline">\(\mu\)</span> using <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\sigma\)</span> using <span class="math inline">\(s\)</span>.</p>
<div id="z-scores" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Z-Scores<a href="random-variables.html#z-scores" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We <strong>standardize</strong> a variable using <span class="math display">\[z = \frac{x-\mu}{\sigma}.\]</span> This is also called a <strong>z-score</strong>. Standardizing using this formula will <em>always</em> result in a variable with mean 0 and standard deviation 1 (even if it’s not normal!).</p>
<p>Because z-scores always result in variables with mean 0 and standard deviation 1, they are also very useful for comparing values which are originally on different scales.</p>
<p>Note that a z-score tells us how many standard deviations an observation is from the mean. A positive z-score <span class="math inline">\(z&gt;0\)</span> is <em>above</em> the mean; a negative z-score <span class="math inline">\(z&lt;0\)</span> is <em>below</em> the mean. For example, if an observation has <span class="math inline">\(z=-0.23\)</span>, that observation is 0.23 standard deviations below the mean.</p>
<blockquote>
<p><strong>Example</strong>: ACT scores have mean 20.8 and standard deviation 5.8. SAT scores have mean 1500 and standard deviation 300. If Jose scored a 27 on his ACT and Navreet scored an 1850 on her SAT, who got a better score (relative to other test takers)?</p>
<p>We cannot compare their scores directly because the ACT and SAT are on different scales. Instead, we will compare their z-scores.</p>
<p>For the SAT, we are given <span class="math inline">\(\mu = 1500\)</span> and <span class="math inline">\(\sigma = 300\)</span>. So Navreet’s z-score is
<span class="math display">\[z_{\text{Navreet}} = \frac{1850-1500}{300} = 1.17\]</span>
standard deviations above the mean.
Then for the ACT, we have that <span class="math inline">\(\mu=20.8\)</span> and <span class="math inline">\(\sigma=5.8\)</span>. So Jose’s z-score is
<span class="math display">\[z_{\text{Jose}} = \frac{27-20.8}{5.8} = 1.07\]</span>
standard deviations above the mean.</p>
<p>Comparing their z-scores, we can see that Navreet’s score is a little farther above the mean than Jose’s and so we can conclude that Navreet got the better score.</p>
</blockquote>
<p>Take a moment to connect z-scores back to the empirical rule. If a z-score is the number of standard deviations an observation is from the mean, we can rewrite the empirical rule as: For any (approximately) normally distributed variable,</p>
<ol style="list-style-type: decimal">
<li>Approximately 68% of all possible observations have z-scores between -1 and 1.</li>
<li>Approximately 95% of all possible observations have z-scores between -2 and 2.</li>
<li>Approximately 99.7% of all possible observations have z-scores between -3 and 3.</li>
</ol>
<p>Note that, since nearly all observations fall within three standard deviations of the mean, this is another way to think about potential outliers: if an observation has a z-score less than -3 or greater than 3, it’s a potential outlier.</p>
</div>
<div id="normal-distribution-probabilities" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Normal Distribution Probabilities<a href="random-variables.html#normal-distribution-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In order to make normal distributions easier to work with, we will standardize them. A <strong>standard normal distribution</strong> is a normal distribution with mean <span class="math inline">\(\mu=0\)</span> and standard deviation <span class="math inline">\(\sigma=1\)</span>. If <span class="math inline">\(X\)</span> is approximately normal, then the standardized variable <span class="math inline">\(Z\)</span> will have a standard normal distribution.</p>
<p>Properties:</p>
<ol style="list-style-type: decimal">
<li>Total area under the curve is 1.</li>
<li>The curve extends infinitely in both directions, never touching the horizontal axis.</li>
<li>Symmetric about 0.</li>
<li>Almost all of the area under the curve is between -3 and 3.</li>
</ol>
<p>Note: when we z-score a variable, we preserve the area under the curve properties! If <span class="math inline">\(X\)</span> is Normal<span class="math inline">\((\mu,\sigma)\)</span>, then <span class="math display">\[P(X &lt; c) = P\left(Z &lt; \frac{c - \mu}{\sigma}\right) = P(Z &lt; z).\]</span></p>
<p>We will think about area under the standard normal curve in terms of <strong>cumulative probabilities</strong> or probabilities of the form <span class="math inline">\(P(Z &lt; z)\)</span>.</p>
<p>We will use the fact that the total area under the curve is 1 to find probabilities like <span class="math inline">\(P(Z &gt; c)\)</span>:</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>Using the graphic to help visualize, we can see that <span class="math display">\[1 = P(Z &lt; c) + P(Z &gt; c)\]</span> which we can then rewrite as
<span class="math display">\[P(Z &gt; c) = 1-P(Z&lt;c).\]</span></p>
<p>We can also use this concept to find <span class="math inline">\(P(a &lt; Z &lt; b)\)</span>.</p>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Notice that <span class="math display">\[1 = P(Z &lt; a) + P(a &lt; Z &lt; b) + P(Z &gt; b),\]</span> which we can rewrite as <span class="math display">\[P(a &lt; Z &lt; b) = 1 - P(Z &gt; b) - P(Z &lt; a)\]</span> and since we just found that <span class="math inline">\(P(Z &gt; b) = 1 - P(Z &lt; b)\)</span>, we can replace <span class="math inline">\(1 - P(Z &gt; b)\)</span> with <span class="math inline">\(P(Z &lt; b)\)</span>, and get <span class="math display">\[P(a &lt; Z &lt; b) = P(Z &lt; b) - P(Z &lt; a).\]</span></p>
<center>
<font size='4'><b>Key Cumulative Probability Concepts</b></font>
</center>
<ul>
<li><span class="math inline">\(P(Z &gt; c) = 1 - P(Z &lt; c)\)</span></li>
<li><span class="math inline">\(P(a &lt; Z &lt; b) = P(Z &lt; b) - P(Z &lt; a)\)</span></li>
</ul>
<p>A final note, because the normal distribution is symmetric, <span class="math inline">\(P(X &lt; \mu) = P(X &gt; \mu) = 0.5\)</span>. Notice this also implies that, when a distribution is symmetric (and unimodal), the mean and median are the same!</p>
<p>Now that we can get all of our probabilities written as <em>cumulative</em> probabilities, we’re ready to use software to find the area under the curve!</p>
<center>
<font size='4'><b>Finding Area Under the Curve: Applets</b></font>
</center>
<p>One option for finding probabilities and z-scores associated with the normal curve is to use an online applet. The <a href="http://www.rossmanchance.com/applets/2021/normcalc/NormCalc.html" target="blank">Rossman and Chance Normal Probability Calculator</a> is my preferred applet. It’s relatively straightforward to use, but would be difficult to demonstrate in these course notes. Instead, we will demonstrate this applet in class. I recommend you bookmark any websites you use to find probabilities.</p>
<p>You can also find the area under a normal distribution using a Normal Distribution Table. These are outdated and not used anywhere but the statistics classroom. As a result, I do not teach them.</p>
<p>Using z-scores and area under the standard normal curve, we can now find probabilities for any normal distribution problem!</p>
<center>
<font size='4'><b>Determining Normal Distribution Probabilities</b></font>
</center>
<ol style="list-style-type: decimal">
<li>Sketch the normal curve for the variable.</li>
<li>Shade the region of interest and mark its delimiting x-value(s).</li>
<li>Find the z-score(s) for the value(s).</li>
<li>Use an applet (or the <code>pnorm</code> command in R) to find the associated area.</li>
</ol>
<blockquote>
<p><strong>Example</strong>: Find the proportion of SAT-takers who score between 1150 and 1300. Assume that SAT scores are approximately normally distributed with mean <span class="math inline">\(\mu=1100\)</span> and standard deviation <span class="math inline">\(\sigma = 200\)</span>.</p>
<p>First, let’s figure out what we want to calculate. Using area under the curve concepts, the proportion of test-takers who score <em>between</em> 1150 and 1300 will be <span class="math inline">\(P(1150 &lt; X &lt; 1300)\)</span>.</p>
<ol style="list-style-type: decimal">
<li>Sketch. On the bottom axis, I am including <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\mu\pm\sigma\)</span>, <span class="math inline">\(\mu\pm2\sigma\)</span>, and <span class="math inline">\(\mu\pm3\sigma\)</span>,as well as the corresponding z-scores (in blue).</li>
</ol>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Shade and label:</li>
</ol>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Calculate z-scores: <span class="math display">\[x = 1150 \rightarrow z = \frac{1150-1100}{200} = 0.25\]</span> and <span class="math display">\[x=1300 \rightarrow z = \frac{1300-1100}{200} = 1.\]</span></li>
<li>Use an applet to find <span class="math inline">\(P(Z &lt; 0.25) = 0.599\)</span> and <span class="math inline">\(P(Z &lt; 1) = 0.841\)</span> <em>or</em> use the <code>pnorm</code> command in R:</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="random-variables.html#cb51-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.25</span>)</span></code></pre></div>
<pre><code>## [1] 0.5987063</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="random-variables.html#cb53-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.8413447</code></pre>
<blockquote>
<p>Note that <span class="math display">\[P(1150 &lt; X &lt; 1300) = P\left(\frac{1150-1100}{200} &lt; Z &lt; \frac{1300-1100}{200}\right) = P(0.25 &lt; Z &lt; 1)\]</span> and, using cumulative probability concepts, <span class="math display">\[P(0.25 &lt; Z &lt; 1) = P(Z &lt; 1) - P(Z &lt; 0.25).\]</span> We found <span class="math inline">\(P(Z &lt; 0.25) \approx 0.5987\)</span> and <span class="math inline">\(P(Z &lt; 1) \approx 0.8413\)</span>, so <span class="math display">\[P(Z &lt; 1) - P(Z &lt; 0.25) \approx 0.8413 - 0.5987 = 0.2426.\]</span> That is, approximately 26.26% of test-takers score between 1150 and 1300 on the SAT.</p>
</blockquote>
</div>
<div id="percentiles" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Percentiles<a href="random-variables.html#percentiles" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also find the <em>observation</em> associated with a percentage/proportion.</p>
<p>The <span class="math inline">\(w\)</span>th <strong>percentile</strong> <span class="math inline">\(p_w\)</span> is the observation that is higher than w% of all observations <span class="math display">\[P(X &lt; p_w) = \frac{w}{100}\]</span></p>
<center>
<font size='4'><b>Finding a Percentile</b></font>
</center>
<ol style="list-style-type: decimal">
<li>Sketch the normal curve for the variable.</li>
<li>Shade the region of interest and label the area.</li>
<li>Use the applet (or R - see below) to determine the z-score for the area.</li>
<li>Find the x-value using <span class="math inline">\(z\)</span>, <span class="math inline">\(\mu\)</span>, and <span class="math inline">\(\sigma\)</span>.</li>
</ol>
<p>Note that if <span class="math inline">\(z = \frac{x-\mu}{\sigma}\)</span>, then <span class="math inline">\(x = \mu + z\sigma\)</span>.</p>
<blockquote>
<p><strong>Example</strong>: Find the 90th percentile for SAT scores.</p>
<p>From the previous example, we know that SAT scores are approximately Normal(<span class="math inline">\(\mu=1100\)</span>, <span class="math inline">\(\sigma=200\)</span>).</p>
<ol style="list-style-type: decimal">
<li>Sketch the normal curve.</li>
</ol>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Shade the region of interest and label the area.</li>
</ol>
</blockquote>
<p><img src="IntroStats_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Use the applet to determine the z-score for the area. This results in <span class="math inline">\(z = 1.28\)</span>.</li>
<li>Find the x-value using <span class="math inline">\(z\approx 1.28\)</span>, <span class="math inline">\(\mu=1100\)</span>, and <span class="math inline">\(\sigma=200\)</span>: <span class="math display">\[x = 1100 + 1.28(200) = 1356\]</span> so 90% of SAT test-takers score below 1356.</li>
</ol>
</blockquote>
</div>
<div id="section-exercises-15" class="section level3 unnumbered hasAnchor">
<h3>Section Exercises<a href="random-variables.html#section-exercises-15" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol>
<li>
Let <span class="math inline">\(X\)</span> be the height of randomly selected adult men. Globally, the approximate mean and standard deviation of men’s heights are <span class="math inline">\(\mu = 68\)</span> and <span class="math inline">\(\sigma = 3\)</span>.
</li>
<ol style="list-style-type: lower-alpha;">
<li>
Use this information, along with the z-score formula, to fill in the table, below
</li>
<table>
<thead>
<tr>
<th>x</th>
<th>62</th>
<th>64</th>
<th>___</th>
<th>66</th>
<th>68</th>
<th>70</th>
<th>___</th>
<th>72</th>
<th>74</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>z</strong></td>
<td>___</td>
<td>___</td>
<td><strong>-1</strong></td>
<td>___</td>
<td>___</td>
<td>___</td>
<td><strong>1</strong></td>
<td>___</td>
<td>___</td>
</tr>
</tbody>
</table>
<li>
Assume <span class="math inline">\(X\)</span> is approximately normal. What percent of male heights fall between 65 and 71 inches?
</li>
</ol>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Sketch the normal curve and shade the region of interest for the following probabilities
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(Z &lt; 1.5)\)</span></li>
<li><span class="math inline">\(P(Z &gt; -1)\)</span></li>
<li><span class="math inline">\(P(-0.75 &lt; Z &lt; 0.5)\)</span></li>
</ol></li>
<li>Use a computer to find the following probabilities
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(Z &lt; 1.5)\)</span></li>
<li><span class="math inline">\(P(Z &gt; -1)\)</span></li>
<li><span class="math inline">\(P(-0.75 &lt; Z &lt; 0.5)\)</span></li>
</ol></li>
<li>For what value of <span class="math inline">\(a\)</span> will <span class="math inline">\(P(-a &lt; z &lt; a) \approx 0.95\)</span>? Hint: remember the normal distribution is symmetric!</li>
<li>Let <span class="math inline">\(X\)</span> be the height of a randomly selected adult man. Globally, <span class="math inline">\(\mu = 68\)</span> and <span class="math inline">\(\sigma=3\)</span>. Use this information to calculate the following probabilities. Hint: the table from (1) may be helpful.
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(X &lt; 70)\)</span></li>
<li><span class="math inline">\(P(64 &lt; X &lt; 72)\)</span></li>
</ol></li>
<li>Suppose <span class="math inline">\(\mu=20\)</span> and <span class="math inline">\(\sigma=4\)</span>. Draw, shade, and label the normal curve, and then determine the probability.
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(X &lt; 23)\)</span></li>
<li><span class="math inline">\(P(X &lt; 19)\)</span></li>
<li><span class="math inline">\(P(19 &lt; X &lt; 23)\)</span></li>
<li><span class="math inline">\(P(X &lt; 15 \text{ OR } X &gt; 22)\)</span></li>
</ol></li>
<li>Suppose <span class="math inline">\(\mu=15\)</span> and <span class="math inline">\(\sigma=5\)</span>. Draw, shade, and label the normal curve, and then determine the percentile.
<ol style="list-style-type: lower-alpha">
<li>90th percentile</li>
<li>45th percentile</li>
<li>17th percentile</li>
</ol></li>
<li>ACT scores are well-approximately by a normal distribution with mean 20.8 and standard deviation 5.8.
<ol style="list-style-type: lower-alpha">
<li>Find the probability that a randomly selected test taker scores below a 19.</li>
<li>Find the probability a randomly selected test taker score above a 23.</li>
<li>Find the probability a randomly selected test taker scored between and 18 and a 22.</li>
<li>Find the ACT score associated with the 90th percentile.</li>
</ol></li>
<li>The average retirement age for an NFL player is 27.6 years old, with a standard deviation of 3.1.
<ol style="list-style-type: lower-alpha">
<li>Draw a normal distribution for the age of retirement of NFL players. Mark <span class="math inline">\(\mu\)</span>, along with <span class="math inline">\(\mu \pm \sigma\)</span>, <span class="math inline">\(\mu \pm 2\sigma\)</span>, and <span class="math inline">\(\mu \pm 3\sigma\)</span>.</li>
<li>Find the probability an NFL player retires before age 25.</li>
<li>Tom Brady retired from the NFL in 2023 at age 45. Is it unusual for a player to stay in the NFL until such an age? Explain, and support your answer using math.</li>
<li>Find the 75th percentile for NFL retirement age.</li>
</ol></li>
<li>The notation <span class="math inline">\(z_{\alpha}\)</span> means the <span class="math inline">\(z\)</span>-value such that the area of the <em>right</em> tail (the area to the right of <span class="math inline">\(z_{\alpha}\)</span>) is <span class="math inline">\(\alpha\)</span>. That is, <span class="math inline">\(P(Z &gt; z_{\alpha}) =\alpha\)</span>. For each <span class="math inline">\(z_{\alpha}\)</span> below, draw, shade, and label the normal curve, then determine the value of <span class="math inline">\(z_{\alpha}\)</span>.
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(z_{0.5}\)</span> <span class="math display">\[P(Z &gt; z_{0.5}) =0.5\]</span></li>
<li><span class="math inline">\(z_{0.1}\)</span></li>
<li><span class="math inline">\(z_{0.05}\)</span></li>
<li><span class="math inline">\(z_{0.01}\)</span></li>
</ol></li>
</ol>
</div>
</div>
<div id="r-lab-probabilities-and-percentiles" class="section level2 unnumbered hasAnchor">
<h2>R Lab: Probabilities and Percentiles<a href="random-variables.html#r-lab-probabilities-and-percentiles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="binomial-probabilities" class="section level3 unnumbered hasAnchor">
<h3>Binomial Probabilities<a href="random-variables.html#binomial-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When it comes to calculating binomial probabilities, hand calculations can be cumbersome. Fortunately, this is another thing we can do in R!</p>
<p>Approximately 66% of US adults take prescription medications. Find the probability that, in a sample of 100 adults, exactly 65 take prescription drugs.</p>
<p>We want to find <span class="math inline">\(P(X = 65)\)</span> where <span class="math inline">\(X\)</span> has a binomial distribution with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(p=0.66\)</span>. (Take a moment on your own to make sure you can convince yourself that this satisfies the conditions for a binomial setting and that you understand how we got here from the prompt above.)</p>
<p>Instead of doing this by hand (the larger <span class="math inline">\(n\)</span> is, the more difficult this tends to get!), we will use the <code>dbinom</code> command in R. The <code>dbinom</code> command takes in the following information:</p>
<ul>
<li><code>x</code> the value <span class="math inline">\(x\)</span> takes on in the expression <span class="math inline">\(P(X=x)\)</span></li>
<li><code>size</code> the value of <span class="math inline">\(n\)</span></li>
<li><code>prob</code> the probability <span class="math inline">\(p\)</span></li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="random-variables.html#cb55-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">65</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> <span class="fl">0.66</span>)</span></code></pre></div>
<pre><code>## [1] 0.0815753</code></pre>
<p>So without doing any hand calculations, I find that <span class="math inline">\(P(X=65) = 0.082\)</span>; the probability that exactly 65 of 100 randomly selected US adults take prescription medication is 0.082.</p>
<p>Suppose now we want to find <span class="math inline">\(P(63 &lt; X &lt; 68)\)</span>. How can we manage that? We can figure out that this probability includes numbers between 63 and 68, but does not include 63 or 68. In fact, it is the numbers 64 through 67. SO we can break this up as <span class="math display">\[ P(63 &lt; X &lt; 68) = P(X=64) + P(X=65)+ P(X=66) + P(X=67) \]</span></p>
<p>In R, we can get a sequence of whole numbers using the format <code>a:b</code>. For example</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="random-variables.html#cb57-1" tabindex="-1"></a><span class="dv">64</span><span class="sc">:</span><span class="dv">67</span></span></code></pre></div>
<pre><code>## [1] 64 65 66 67</code></pre>
<p>gives all whole numbers from 64 through 67.</p>
<p>I can then put this directly into the <code>dbinom</code> command!</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="random-variables.html#cb59-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">64</span><span class="sc">:</span><span class="dv">67</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> <span class="fl">0.66</span>)</span></code></pre></div>
<pre><code>## [1] 0.07587601 0.08157530 0.08397457 0.08272122</code></pre>
<p>This produces each individual probability <span class="math inline">\(P(X=64)\)</span>, <span class="math inline">\(P(X=65)\)</span>, <span class="math inline">\(P(X=66)\)</span>, and <span class="math inline">\(P(X=67)\)</span>. To quickly add these up, I am going to use the <code>sum</code> command. Notice that I put the entire <code>dibnom</code> command <em>in the parentheses</em> of the <code>sum()</code>.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="random-variables.html#cb61-1" tabindex="-1"></a><span class="fu">sum</span>(</span>
<span id="cb61-2"><a href="random-variables.html#cb61-2" tabindex="-1"></a>  <span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">64</span><span class="sc">:</span><span class="dv">67</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> <span class="fl">0.66</span>)</span>
<span id="cb61-3"><a href="random-variables.html#cb61-3" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## [1] 0.3241471</code></pre>
<p>And so <span class="math inline">\(P(63 &lt; X &lt; 68) = 0.324\)</span>; the probability that between 64 and 67 (inclusive) US adults in a sample of 100 take prescription medication is 0.324.</p>
</div>
<div id="normal-distribution-probabilities-1" class="section level3 unnumbered hasAnchor">
<h3>Normal Distribution Probabilities<a href="random-variables.html#normal-distribution-probabilities-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Standard normal probabilities are found using the command <code>pnorm</code>. This command takes arguments</p>
<ul>
<li><code>q</code>: the value of <span class="math inline">\(x\)</span>.</li>
<li><code>mean</code>: the mean of the normal distribution. (If you leave this out, R will use <span class="math inline">\(\mu=0\)</span>.)</li>
<li><code>sd</code>: the standard deviation of the normal distribution. (If you leave this out, R will use <span class="math inline">\(\sigma=1\)</span>.)</li>
<li><code>lower.tail</code>: whether to find the lower tail probability.
<ul>
<li>When this equals <code>TRUE</code>, R will find <span class="math inline">\(P(X &lt; x)\)</span>.</li>
<li>When this equals <code>FALSE</code>, R will find <span class="math inline">\(P(X &gt; x)\)</span>.</li>
</ul></li>
</ul>
<p>Suppose <span class="math inline">\(X\)</span> is a normal random variable with mean <span class="math inline">\(\mu=8\)</span> and standard deviation <span class="math inline">\(\sigma=2\)</span>. To find <span class="math inline">\(P(X &gt; 4)\)</span>, I would write</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="random-variables.html#cb63-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">4</span>, <span class="at">mean=</span><span class="dv">8</span>, <span class="at">sd=</span><span class="dv">2</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9772499</code></pre>
<p>So <span class="math inline">\(P(X &gt; 4) = 0.9772\)</span></p>
<p>Because R will use the standard normal distribution if we leave out the <code>mean</code> and <code>sd</code> commands, it’s even easier to find probabilities for <span class="math inline">\(Z\)</span>, To find <span class="math inline">\(P(Z&lt;1)\)</span>, I would type:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="random-variables.html#cb65-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q=</span><span class="dv">1</span>, <span class="at">lower.tail=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.8413447</code></pre>
<p>so <span class="math inline">\(P(Z &lt; 1) = 0.841\)</span>.</p>
<p>A quick note about R: R will print very large numbers and numbers close to 0 using <em>scientific notation</em>. However, R’s scientific notation may not look the way you’re used to! Check out the R output for <span class="math inline">\(P(Z &lt; -5)\)</span>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="random-variables.html#cb67-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 2.866516e-07</code></pre>
<p>When you see <code>e-07</code>, that means <span class="math inline">\(\times10^{-7}\)</span>… so <span class="math inline">\(P(Z &lt; -5) = 2.8665 \times 10^{-7} \approx 0.00000029\)</span>.</p>
</div>
<div id="normal-distribution-percentiles" class="section level3 unnumbered hasAnchor">
<h3>Normal Distribution Percentiles<a href="random-variables.html#normal-distribution-percentiles" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Instead of using an applet, we can use the <code>qnorm</code> command in R to find the z-score corresponding to a percentile. In this case, we simply enter the percentile of interest <em>expressed as a proportion</em> in the <code>qnorm</code> command. That is, to find the z score for the 90th percentile, we would enter</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="random-variables.html#cb69-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## [1] 1.281552</code></pre>
<p>which gives the same result as the applet in the example above. Then, we can use R as a calculator to find the value of <span class="math inline">\(x\)</span> (recall <span class="math inline">\(\mu=1100\)</span> and <span class="math inline">\(\sigma=200\)</span>)</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="random-variables.html#cb71-1" tabindex="-1"></a><span class="dv">1100</span> <span class="sc">+</span> <span class="fl">1.281552</span><span class="sc">*</span><span class="dv">200</span></span></code></pre></div>
<pre><code>## [1] 1356.31</code></pre>
<p>This gives us the same result as before, that 90% of SAT test-takers score below 1356.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability-concepts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-confidence-intervals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
