---
title: "4.3 Rules of Probability"
author: "Dr. Lauren Perry"
output:
  ioslides_presentation:
    widescreen: true
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Goals

1. Use the addition rule to calculate the probability of one event *or* some other event occurring. 
2. Use contingency tables to describe relationships between two variables.
3. Use the complement rule to calculate probabilities. 

## Rules of Probability

Consider a six-sided die. $$P(\text{roll a 1 or 2}) = \frac{\text{2 ways}}{\text{6 outcomes}} = \frac{1}{3}$$ We get the same result by taking $$P(\text{roll a 1})+P(\text{roll a 2}) = \frac{1}{6}+\frac{1}{6} = \frac{1}{3}$$ It turns out this is widely applicable!

## Addition Rule for Disjoint Outcomes

If $A_1$ and $A_2$ are disjoint outcomes, then the probability that one of them occurs is $$P(A_1 \text{ or } A_2) = P(A_1)+P(A_2)$$ This can also be extended to more than two disjoint outcomes: $$P(A_1 \text{ or } A_2 \text{ or } \dots \text{ or } A_k) = P(A_1)+P(A_2)+\dots + P(A_k)$$ for $k$ disjoint outcomes.

## Example: A deck of cards. 

- Let $A$ be the event that a card drawn is a diamond.
- Let $B$ be the event it is a face card. 

$A$: $\quad 2\diamondsuit$ $3\diamondsuit$ $4\diamondsuit$ $5\diamondsuit$ $6\diamondsuit$ $7\diamondsuit$ $8\diamondsuit$ $9\diamondsuit$ $10\diamondsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $A\diamondsuit$

$B$: $\quad J\heartsuit$ $Q\heartsuit$ $K\heartsuit$ $J\clubsuit$ $Q\clubsuit$ $K\clubsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $J\spadesuit$ $Q\spadesuit$ $K\spadesuit$

## Example: A deck of cards.

The collection of cards that are diamonds or face cards (or both) is

<center>$\quad A\diamondsuit$ $2\diamondsuit$ $3\diamondsuit$ $4\diamondsuit$ $5\diamondsuit$ $6\diamondsuit$ $7\diamondsuit$ $8\diamondsuit$ $9\diamondsuit$ $10\diamondsuit$ $J\diamondsuit$ $Q\diamondsuit$ $K\diamondsuit$ $J\clubsuit$ $Q\clubsuit$ $K\clubsuit$ $J\heartsuit$ $Q\heartsuit$ $K\heartsuit$ $J\spadesuit$ $Q\spadesuit$ $K\spadesuit$</center>

<br>
Looking at these cards, I can see that there are 22 of them, so $$P(A \text{ or } B) = \frac{22}{52}$$

## Example: A deck of cards.

- If I try to apply the addition rule for disjoint outcomes, $$P(A)=\frac{13}{52}$$ and $$P(B)=\frac{12}{52}$$
- And we get $\frac{13+15}{52} = \frac{25}{52}$.
- But we know $P(A \text{ or } B) = \frac{22}{52}$.

## Example: A deck of cards.

What happened? 

- When I added these, I *double counted* $J\diamondsuit$, $Q\diamondsuit$, and $K\diamondsuit$ 
    - (the cards that are in both $A$ and $B$). 
- I need to subtract off the double count $$\frac{13}{52}+\frac{12}{52}-\frac{3}{52}$$

## General Addition Rule

For any two events $A$ and $B$, the probability that *at least* one will occur is $$P(A \text{ or } B) = P(A)+P(B)-P(A \text{ and }B).$$

- The general addition rule applies to *any* two events, even disjoint events. 
    - For disjoint events, $P(A \text{ and } B) = 0$.

## Inclusive or

- When we say "or", we include the situations where:
    - A is true
    - B is true
    - both A and B are true. 
- This is an *inclusive or*. 

## Contingency Tables

A **contingency table** is a way to summarize **bivariate data**, or data from two variables. 

***

*Smallpox in Boston (1726)*
<center>
<table>
    <tbody>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" colspan="3" width="254">
                <p style="text-align: center;"><strong>Inoculated</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" width="74">
                <p><strong>yes</strong></p>
            </td>
            <td style="text-align: center;" width="84">
                <p><strong>no</strong></p>
            </td>
            <td style="text-align: center;" width="96">
                <p><strong>total</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" rowspan="3" width="72">
                <p><strong>Result</strong></p>
            </td>
            <td style="text-align: center;" width="58">
                <p><strong>lived</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>238</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>
                    <span style="color: #000000; background-color: #fbeeb8;">5136</span>
                </p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #bfedd2;">5374</span>
                </p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>died</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>6</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>844</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>850</p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>total</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>
                    <span style="background-color: #eccafa;">244</span>
                </p>
            </td>
            <td style="text-align: center;" width="84">
                <p>5980</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #c2e0f4;">6224</span>
                </p>
            </td>
        </tr>
    </tbody>
</table>
</center>

<ul>
    <li>
        <span style="background-color: #fbeeb8;">5136</span> is the count of people who lived AND were not inoculated.&nbsp;
    </li>
    <li>
        <span style="background-color: #c2e0f4;">6224</span> is the total number of observations.
    </li>
    <li>
        <span style="background-color: #eccafa;">244</span> is the total number of people who were inoculated.
    </li>
    <li>
        <span style="background-color: #bfedd2;">5374</span> is the total number of people who lived.
    </li>
</ul>

## Contingency Tables

- These are basically two-variable frequency distributions. 
- We can convert to proportions by dividing each count by the total number of observations.

***

<center>
<table>
    <tbody>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" colspan="3" width="254">
                <p><strong>Inoculated</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" width="74">
                <p><strong>yes</strong></p>
            </td>
            <td style="text-align: center;" width="84">
                <p><strong>no</strong></p>
            </td>
            <td style="text-align: center;" width="96">
                <p><strong>total</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" rowspan="3" width="72">
                <p><strong>Result</strong></p>
            </td>
            <td style="text-align: center;" width="58">
                <p><strong>lived</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0382</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>
                    <span style="background-color: #fbeeb8;">0.8252</span>
                </p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #bfedd2;">0.8634</span>
                </p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>died</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0010</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.1356</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>0.1366</p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>total</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>
                    <span style="background-color: #eccafa;">0.0392</span>
                </p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.9608</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #c2e0f4;">1.0000</span>
                </p>
            </td>
        </tr>
    </tbody>
</table>
</center>

<ul>
    <li>
        <span style="background-color: #fbeeb8;">0.8252</span> is the proportion of people who lived AND were not inoculated.&nbsp;
    </li>
    <li>
        <span style="background-color: #c2e0f4;">1.000</span> is the proportion of total number of observations. Think of this as 100% of the observations.
    </li>
    <li>
        <span style="background-color: #eccafa;">0.0392</span> is the proportion of people who were inoculated.
    </li>
    <li>
        <span style="background-color: #bfedd2;">0.8634</span> is the proportion of people who lived.
    </li>
</ul>

***

<center>
<table>
    <tbody>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" colspan="3" width="254">
                <p><strong>Inoculated</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" width="74">
                <p><strong>yes</strong></p>
            </td>
            <td style="text-align: center;" width="84">
                <p><strong>no</strong></p>
            </td>
            <td style="text-align: center;" width="96">
                <p><strong>total</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" rowspan="3" width="72">
                <p><strong>Result</strong></p>
            </td>
            <td style="text-align: center;" width="58">
                <p><strong>lived</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0382</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>
                    <span style="background-color: #fbeeb8;">0.8252</span>
                </p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #bfedd2;">0.8634</span>
                </p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>died</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0010</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.1356</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>0.1366</p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>total</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>
                    <span style="background-color: #eccafa;">0.0392</span>
                </p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.9608</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #c2e0f4;">1.0000</span>
                </p>
            </td>
        </tr>
    </tbody>
</table>
</center>

- The row and column totals are **marginal probabilities**. 
- The probability of two events together ($A$ and $B$) is a **joint probability**.

## Example

<center>
<table>
    <tbody>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" colspan="3" width="254">
                <p><strong>Inoculated</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" colspan="2" width="130">
                <p>&nbsp;</p>
            </td>
            <td style="text-align: center;" width="74">
                <p><strong>yes</strong></p>
            </td>
            <td style="text-align: center;" width="84">
                <p><strong>no</strong></p>
            </td>
            <td style="text-align: center;" width="96">
                <p><strong>total</strong></p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" rowspan="3" width="72">
                <p><strong>Result</strong></p>
            </td>
            <td style="text-align: center;" width="58">
                <p><strong>lived</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0382</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>
                    <span style="background-color: #fbeeb8;">0.8252</span>
                </p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #bfedd2;">0.8634</span>
                </p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>died</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>0.0010</p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.1356</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>0.1366</p>
            </td>
        </tr>
        <tr>
            <td style="text-align: center;" width="58">
                <p><strong>total</strong></p>
            </td>
            <td style="text-align: center;" width="74">
                <p>
                    <span style="background-color: #eccafa;">0.0392</span>
                </p>
            </td>
            <td style="text-align: center;" width="84">
                <p>0.9608</p>
            </td>
            <td style="text-align: center;" width="96">
                <p>
                    <span style="background-color: #c2e0f4;">1.0000</span>
                </p>
            </td>
        </tr>
    </tbody>
</table>
</center>

Find the probability an individual was inoculated OR lived. 

## Complements

The **complement** of an event is all of the outcomes in the sample space that are *not* in the event. For an event $A$, we denote its complement by $A^c$.

## Example

- For a single roll of a six-sided die, the sample space is all possible rolls: 1, 2, 3, 4, 5, or 6. 
- Let event $A$ be rolling a 1 or a 2.
- Then $A^c$ is rolling a 3, 4, 5, or 6. 

In probability notation: $$S = \{1, 2, 3, 4, 5, 6\}$$ $$A=\{1,2\}$$ $$A^c=\{3, 4, 5, 6\}$$

## Property

$$P(A \text{ or } A^c)=1$$ 

- Using the addition rule, $$P(A \text{ or } A^c) = P(A)+P(A^c) = 1$$ 
- Make sure you can convince yourself that $A$ and $A^c$ are *always* disjoint.

## The Complement Rule

$$P(A) = 1-P(A^c)$$

## Example

Use the complement rule to find the probability a person was NOT inoculated. 

## Example

Consider rolling 2 six-sided dice and taking their sum. 

The event of interest $A$ is a sum less than 12. Find

1. $A^c$
2. $P(A^c)$
3. $P(A)$
